### ISSUE TITLE
topology_hiding and dialog contact tag

### ISSUE THREAD

**Issue by StellaTeam** [OpenSIPS/opensips#1014]
Hello,

I wonder about why contact keeps the "did" tag.
I tried a lot of settings but in all cases "did" tag (or its renamed through dialog rr_param parameter equivalent) is always added to contact, and even after topology hiding, it keeps there.

If i well understood the request processing order, topology_hiding reconstruct SIP headers (RR, Via and Contact) from Call-Id (once decoded), and then, the reconstructed packet is usable for other modules like `dialog` and `rr`

so Contact should be clean from any parameter else than:
- th_passed_contact_params if set
- th_passed_contact_uri_params if set

I didn't find any way to tell topology_hiding to hide it from Contact header...  even if playing with
- dlg_match_mode

So either i missed something or that's a bug ?

Thank you for your help

**Comment by bogdan-iancu** [comment]
Hi @darencrew , 
The DID (Dialog ID) is added by the dialog module and is an internal ID of that dialog - to speed-up or to help with the matching of sequential requests to the original dialog, the DID param is placed in the Contact (when TH is performed) or in RR (without TH) headers.
So, did param will help to match the request to the dialog, and the dialog will tell further what to do (like TH or others).
As time as you use dialog support, the did is there. BTW, have you tried dlg_match_mode 2 ?

**Comment by darencrew** [comment]
Hi Bogdan,

That's what i understood, i'm relieved...
I did test `dlg_match_mode 2` but it did nothing on contact, `did` is still present, i suppose it only affects RR patching, not contact patching...
I made some more tests, and the did in contact doesn't appear when topology hiding module is not in use... but appear immediately when topology hiding is on... whatever dlg_match_mode is set...

So i looked a bit in topology hiding code, and, if i well understood, it copies unknown params in contact, and i that's it, it considers rr_param as unknown, and so copies it to Contact (i'm absolutely not sure of it as it seems strange)

**Comment by darencrew** [comment]
Hi Bogdan,

I made some more "code reading", and if i well understood, as always, when uri params are unknown, they are appended to Contact URI by topology_hiding module, and according to parse_uri.c:
```
supported params:
maddr, transport, ttl, lr, user, method, r2
```
and so, `did` or any other dialog specific parameter is unknown, and so, added to contact header...

Hope it might help...

**Comment by bogdan-iancu** [comment]
Hi @darencrew , the `did` param is actually added (and not passed through) to the Contact hdr. 
When using `topology_hiding`, there are 2 options:
a) without `dialog` - the information need to be restored is added to the Route hdr (to be session persistent)
b) with `dialog` - the information need to be restored is added to the dialog internals and the reference to the dialog is added as `did` to Contact (see https://github.com/OpenSIPS/opensips/blob/master/modules/topology_hiding/topo_hiding_logic.c#L459). Still, the TH module does not check the `dlg_match_mode` to see the policy on adding the `did` param.

Not sure if this answered to your question or not :)

**Comment by darencrew** [comment]
Hi @bogdan-iancu 

Thanks for your message

I can't use "non dialog mode" as it would leak some information (Route header should be absent or as standard/neutral/cleaner as possible for OpenSips to be usable for interconnecting), and so:
- either topology hiding to consider dialog tag (`did_param`) to be a well known parameter, and so, to hide it / not adding it to Contact (adding did_param to known parameters?)
- or be `dlg_match_mode` aware as you describe
But on both cases, i don't know of theses two modules can know about each other parameters... if you have some clues to give, that would be great...

There is probably another way that would be very dirty and with unexpectable results, by using well known tags to be used for dialog (instead of `did` or custom) that won't be added to contact, and to clean theses parameters on arrival in order them not to be applied (that would be worse than ever).

**Comment by bogdan-iancu** [comment]
Hi @darencrew . Should I understand that you want this `did` param out ? May I ask why? at the end it is a really opaque ID, nothing more. I'm just trying to understand the reason, to be able to judge the severity of this issue.

**Comment by darencrew** [comment]
Hi @bogdan-iancu 

`did` is not a RFC standardized  contact parameter, and so, not compliant with standardized interconnecting requirements (in France)


Moreover, if i well understood, that's useless (or at least not mandatory) for OpenSIPs to work, either for dialog or topology hiding as the last one use CallId to recover every parameters needed by the first one...

**Comment by vtzan** [comment]
Dear Team,

I would like to add "+" symbol in user part of Contact header as per Vendor requirements. 
So in order to rewrite the contact header and don't brake SIP handling I need a variable to get the did param value that is been added to the contact header by the topology_hiding module 
note: I am using topology_hiding("UC")

The Contact Header that I would like to change is always in this format before going to vendor:  
Contact: <sip:XXXXXXXXXXXX@local_ip_address;did=4c9.a432a1e2>.

If I try to change the Contact Header with subst('/Contact:.*<sip:/Contact: <sip:+/i')
the value becomes : Contact: <sip:+XXXXXXXXXXXX@signaling_ip_address:5065>.
and I loose local_ip_address and did param value.

I have tried $DLG_did, $ct and all $ct.fields but I couldn't get the correct did param value in some script variable. Does this variable exist?

thank you

**Comment by StellaTeam** [comment]
@vtzan Have you tried to change your Contact before calling topology_hiding ?
I suppose if you do it, the "did" would be appended and you won't have your current problem.

Another possibility would be to manage to get the sender using the expected format, that is, indeed, not always possible.

I can't tell you more about a way to get the "did" after topology_hiding, and i suspect changing Contact afterwards to be risky...

But i'm not an expert ;)

**Comment by vtzan** [comment]
I have tried both. If I change contact header in any way, the topology hiding seems to not replace the contact header with proxy ip and also doesn't add the did value! is this a bug?

**Comment by vtzan** [comment]
Hi @bogdan-iancu

Is there any user space variable available on OpenSIPS 2.2.x for the internal ID param (did) of the dialog that is created when using topology_hiding? 
e.g.
Contact: <sip:+xxxxxxxxx@192.168.10.10;did=88d.d758f505>

I would like to reuse that did param further on the script. 
Or any way to catch this whole contact header after applying topology hiding so that I can parse it further and grab the did param?

thank you

**Comment by razvancrainea** [comment]
@vtzan you can fetch the dialog id using [`$DLG_did`](http://www.opensips.org/html/docs/modules/2.4.x/dialog.html#idp5986896), but you'll still need to do some processing to get the did in the format you want. You can try something like this:

```
$var(dentry) = $(DLG_did{s.select,0,:});
$var(did) = $(DLG_did{s.select,1,:});
$var(did) = $(var(dentry){s.dec2hex}) + "." + $(var(did){s.dec2hex});
```

I didn't test it, but it should work. Make sure you are calling this _after_ `create_dialog()` or `loose_route()`.

Best regards,
Răzvan

**Comment by vtzan** [comment]
@razvancrainea thank you for your reply I really appreciate that.

With your code example the real internal did param was 47b.1ef94a74 and the $var(did) returned : b74.47a49fe1 

If you look closely this is the result but needs some more transformation. For example the first section result is 47b and var(did) returned : b74

I didn't knew that there is a connection between those two variables!

thank you

**Comment by vtzan** [comment]
Hi @razvancrainea 

I have made this worked out. Thank your for the tip.
I would like to share it just in case anyone might need it.

        $var(dentry) = $(DLG_did{s.select,0,:});
        $var(didparam) = $(DLG_did{s.select,1,:});

        $avp(didfirst) = $(var(dentry){s.dec2hex});
        $avp(didsecond) = $(var(didparam){s.dec2hex});

        $var(did_first_part_len) = $(avp(didfirst){s.len});
        $var(did_second_part_len) = $(avp(didsecond){s.len});

        # Parse first part letter by letter
        while ( $var(did_first_part_len) >= 0 ) {
                
                $avp(did_first_part_get_char) = $(avp(didfirst){s.substr,$var(did_first_part_len),1});
                $var(did_first_part_len) = $var(did_first_part_len) - 1;
                $avp(did_first_part_final) = $avp(did_first_part_final) + $avp(did_first_part_get_char);
        }

        # Parse Second part letter by letter
        while ( $var(did_second_part_len) >= 0 ) {

                $avp(did_second_part_get_char) = $(avp(didsecond){s.substr,$var(did_second_part_len),1});
                $var(did_second_part_len) = $var(did_second_part_len) - 1;
                $avp(did_second_part_final) = $avp(did_second_part_final) + $avp(did_second_part_get_char);
        }

        $avp(final_did_param) = $avp(did_first_part_final) + "." + $avp(did_second_part_final);
        xlog("Final Converted DID : $avp(final_did_param)\n");

The result is correct but OpenSIPS creates an ERROR Log during both substrs
      ERROR:core:tr_eval_string: substr out of range
Any idea?

opensips 2.2.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 1df7195a1
main.c compiled on 18:08:23 Jun 13 2018 with gcc 5.4.0
