### ISSUE TITLE
uac_replace_from causes TO header to be corrupt in some replies

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1019]
When using uac_replace_from if $T_reply_code is accessed in the global onreply_route responses to requests from the CALLEE will have a corrupt TO header. I am using the "restore_mode" set to "auto" for the uac module and "force_dialog" is set to "yes".

Attached is the text output of a capture showing the issue. When the CALLEE sends a BYE the 200 OK for the BYE has a corrupt TO header after passing through the proxy.

[corrupt_to_in_reply.txt](https://github.com/OpenSIPS/opensips/files/699946/corrupt_to_in_reply.txt)

Took awhile to narrow down the scenario, but it seems to be triggered if a global onreply_route is configured and $T_reply_code is accessed in it (even just doing a conditional check on it will present the bug). If instead of $T_reply_code, $rs is used, the problem does not occur. If you use a stateful onreply_route the problem does not occur.

Example onreply_route causing the problem:
onreply_route {
        xlog("test $T_reply_code");
}

Rest of the config was pretty minimal, just enough to trigger the bug.

It is probably wrong to access $T_reply_code (stateful) in the global onreply_route (stateless), but it should probably return null, or error instead of causing message corruption.

opensips -V
version: opensips 2.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: ac03a5a
main.c compiled on 09:11:56 Jan 11 2017 with gcc 5.3.1

**Comment by razvancrainea** [comment]
The problem seems to be that the transaction is matched twice - once when you access `$T_reply_code` and when the tm module checks the reply. Therefore the To header restore callback is called twice, hence two lumps -> the value appears twice.

I will try to find a nice solution for this and get back to you.

Thanks for reporting it :)

**Comment by razvancrainea** [comment]
After giving some thought, there are three approaches to fix this:

1. Write some code that prevents the restore process to happen multiple times.
2. Do a hack to make sure the transaction is only matched once, using some global variables.
3. Do the 'right' fix and move the transaction in a message context, where it is only matched once.

In my opinion, 1. is not worth investing more time, because it's not a complete fix - other modules that use the same behavior might run into the same problem. 2. is a quick but hackish fix, and it won't live too long in future async design.
Therefore I'd suggest to go with the 3rd option. Although this requires some extra work, the change is already on our timeline for the next OpenSIPS versions.
I guess that until this is sorted out, you can still replace the `$T_reply_code` with `$rs` in your code, correct?

**Comment by rrb3942** [comment]
Yep, I switched over to $rs in the global onreply_route and it has been working fine.

Might just want to make a note in the docs for older versions to avoid the use of tm functions and variables in the global onreply_route? Not sure what other scenarios might trigger it, but it was not obvious what was causing the message corruption other than some sort of interaction with uac_replace_from (and who would suspect checking a reply code).

Thanks for tracking down the root cause.

**Comment by razvancrainea** [comment]
Closing this issue as there's no intent to change the current behavior.

**Comment by liviuchircu** [comment]
Hi folks, I just noticed this thread (a bit too late...), but this issue has already been fixed 6 months ago on versions `2.4` and higher in commit 3a25c0b2.  Basically, accessing `$T_reply_code` or `$T_ruri` within global onreply_route is now considered to be a no-op and will simply return `NULL` instead of matching the transaction.

Unfortunately, @rrb3942 seems to be on `2.2` (unmaintained), so the bug is still there.
