### ISSUE TITLE
mid_registrar and ipv6

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1152]
When I try to convert ipv6 REGISTER into ipv4 with mid_registrar mode=2 it doesn't add rid parameter and complains in logs:

```
Jun 29 18:51:43 opensips-ipv6 /usr/sbin/opensips[22104]: ERROR:mid_registrar:get_match_token: a Contact from main registrar (sip:7018@8.8.8.8:5060) is missing the 'rid' hf parameter
Jun 29 18:51:43 opensips-ipv6 /usr/sbin/opensips[22104]: ERROR:mid_registrar:restore_reply_contacts: failed to get match token
Jun 29 18:51:43 opensips-ipv6 /usr/sbin/opensips[22104]: ERROR:mid_registrar:mid_reg_resp_in: failed to overwrite Contact header field domain
```

**Comment by rubbermaiden** [comment]
Hi guys. 
I am also with the same problem, but I run only with ipv4.
Aug 14 14:50:18 OpenSIPs opensips: Aug 14 14:50:18 [11200] ERROR:mid_registrar:get_match_token: a Contact from main registrar (sip:7010@192.168.50.106:5061) is missing the 'rid' hf parameter
Aug 14 14:50:18 OpenSIPs opensips: Aug 14 14:50:18 [11200] ERROR:mid_registrar:restore_reply_contacts: failed to get match token
Aug 14 14:50:18 OpenSIPs opensips: Aug 14 14:50:18 [11200] ERROR:mid_registrar:mid_reg_resp_in: failed to overwrite Contact header field domain
I got the mid_registrar.cfg example and only replaced de ipv4 addresses of the server and the main registrar. 
I am being able to register successfully in the main registrar but when I receive an INVITE from the main registrar and the script try lookup the mid registrar, I get the above error.
In the docs says that a header field named "rid" should be added to the Contact, this is correct ? because in my case is not being added.
My opensips.cfg is as follows:
#
# $Id$
#
# OpenSIPS residential configuration script
#     by OpenSIPS Solutions <team@opensips-solutions.com>
#
# This script was generated via "make menuconfig", from
#   the "Residential" scenario.
# You can enable / disable more features / functionalities by
#   re-generating the scenario with different options.#
#
# Please refer to the Core CookBook at:
#      http://www.opensips.org/Resources/DocsCookbooks
# for a explanation of possible statements, functions and parameters.
#


####### Global Parameters #########

log_level=4
log_stderror=yes
log_facility=LOG_LOCAL0

children=4

/* uncomment the following line to enable debugging */
#debug_mode=yes

/* uncomment the next line to enable the auto temporary blacklisting of 
   not available destinations (default disabled) */
#disable_dns_blacklist=no

/* uncomment the next line to enable IPv6 lookup after IPv4 dns 
   lookup failures (default disabled) */
#dns_try_ipv6=yes

/* comment the next line to enable the auto discovery of local aliases
   based on revers DNS on IPs */
auto_aliases=no


listen=udp:192.168.50.106:5061   # CUSTOMIZE ME



####### Modules Section ########

#set module path
mpath="/usr/local/lib64/opensips/modules/"

loadmodule "mid_registrar.so"
modparam("mid_registrar", "mode", 2) 
modparam("mid_registrar", "outgoing_expires", 7200)
modparam("mid_registrar", "insertion_mode", 0) 
#modparam("mid_registrar", "contact_match_param", "rid1") 

#### SIGNALING module
loadmodule "signaling.so"

#### StateLess module
loadmodule "sl.so"

#### Transaction Module
loadmodule "tm.so"
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 30)
modparam("tm", "restart_fr_on_each_reply", 0)
modparam("tm", "onreply_avp_mode", 1)

#### Record Route Module
loadmodule "rr.so"
/* do not append from tag to the RR (no need for this script) */
modparam("rr", "append_fromtag", 0)

#### MAX ForWarD module
loadmodule "maxfwd.so"

#### SIP MSG OPerationS module
loadmodule "sipmsgops.so"

#### FIFO Management Interface
loadmodule "mi_fifo.so"
modparam("mi_fifo", "fifo_name", "/tmp/opensips_fifo")
modparam("mi_fifo", "fifo_mode", 0666)


#### URI module
loadmodule "uri.so"
modparam("uri", "use_uri_table", 0)

#### USeR LOCation module
loadmodule "usrloc.so"
#modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "db_mode",   0)

#### REGISTRAR module
#loadmodule "registrar.so"

/* uncomment the next line not to allow more than 10 contacts per AOR */
#modparam("registrar", "max_contacts", 10)

#### ACCounting module
loadmodule "acc.so"
/* what special events should be accounted ? */
modparam("acc", "early_media", 0)
modparam("acc", "report_cancels", 0)
/* by default we do not adjust the direct of the sequential requests.
   if you enable this parameter, be sure the enable "append_fromtag"
   in "rr" module */
modparam("acc", "detect_direction", 0)


#### UDP protocol
loadmodule "proto_udp.so"

####### Routing Logic ########

# main request routing logic

route{
	if (!mf_process_maxfwd_header("10")) {
		sl_send_reply("483","Too Many Hops");
		exit;
	}

	if (has_totag()) {
		# sequential requests within a dialog should
		# take the path determined by record-routing
		if (loose_route()) {
			
			if (is_method("BYE")) {
				# do accunting, even if the transaction fails
				do_accounting("log","failed");
			} else if (is_method("INVITE")) {
				# even if in most of the cases is useless, do RR for
				# re-INVITEs alos, as some buggy clients do change route set
				# during the dialog.
				record_route();
			}

			# route it out to whatever destination was set by loose_route()
			# in $du (destination URI).
			route(relay);
		} else {
			
			if ( is_method("ACK") ) {
				if ( t_check_trans() ) {
					# non loose-route, but stateful ACK; must be an ACK after 
					# a 487 or e.g. 404 from upstream server
					t_relay();
					exit;
				} else {
					# ACK without matching transaction ->
					# ignore and discard
					exit;
				}
			}
			sl_send_reply("404","Not here");
		}
		exit;
	}

	# CANCEL processing
	if (is_method("CANCEL"))
	{
		if (t_check_trans())
			t_relay();
		exit;
	}

	t_check_trans();

	if (is_method("REGISTER")) {
		xlog("*************************************\n");
		xlog("REGISTER received\n");
		xlog("*************************************\n");
		mid_registrar_save("location");
		switch ($retcode) {
		case 1:
			rewritehostport("192.168.50.159:5060");
			xlog("*************************************\n");
			xlog("forwarding REGISTER to main registrar ($$ru=$ru)\n");
			xlog("*************************************\n");
			#$ru = "sip:192.168.50.159:5060";

			if (!t_relay()) {
				send_reply("500", "Server Internal Error 1");
			}
			break;
		case 2:
			xlog("*************************************\n");
			xlog("absorbing REGISTER! ($$ci=$ci)\n");
			xlog("*************************************\n");
			break;
		default:
			xlog("*************************************\n");
			xlog("failed to save registration! ($$ci=$ci)\n");
			xlog("*************************************\n");
			send_reply("500", "Server Internal Error 2");
		}

		exit;
	}

	# preloaded route checking
	if (loose_route()) {
		xlog("L_ERR",
		"Attempt to route with preloaded Route's [$fu/$tu/$ru/$ci]");
		if (!is_method("ACK")){
			xlog("*************************************\n");
			xlog("Attempt to route with preloaded Route's [$fu/$tu/$ru/$ci]!\n");
			xlog("*************************************\n");
			sl_send_reply("403","Preload Route denied");
		}
		exit;
	}

	# record routing
	if (!is_method("REGISTER|MESSAGE"))
		record_route();

	# account only INVITEs
	if (is_method("INVITE")) {
		do_accounting("log");
	}

	if (!uri==myself) {
		append_hf("P-hint: outbound\r\n"); 
		route(relay);
	}

	# requests for my domain
	if (is_method("PUBLISH|SUBSCRIBE"))
	{
		xlog("*************************************\n");
		xlog("PUBLISH or SUBSCRIBE not available!\n");
		xlog("*************************************\n");
		sl_send_reply("503", "Service Unavailable");
		exit;
	}

	if ($rU==NULL) {
		# request with no Username in RURI
		xlog("*************************************\n");
		xlog("RURI empty, sending 484!\n");
		xlog("*************************************\n");
		sl_send_reply("484","Address Incomplete");
		exit;
	}

	# initial requests from main registrar, need to look them up!
	if (is_method("INVITE|MESSAGE") && $si == "192.168.50.159" && $sp == 5060) {
		xlog("*************************************\n");
		xlog("looking up $ru in mid registrar!\n");
		xlog("*************************************\n");
		if (!mid_registrar_lookup("location")) {
			xlog("*************************************\n");
			xlog("AOR Not Found, sending 404!\n");
			xlog("*************************************\n");
			t_reply("404", "Not Found");
			exit;
		}

		t_relay();
		exit;
	}

	# when routing via usrloc, log the missed calls also
	do_accounting("log","missed");
	route(relay);
}


route[relay] {
	# for INVITEs enable some additional helper routes
	if (is_method("INVITE")) {
		t_on_branch("per_branch_ops");
		t_on_reply("handle_nat");
		t_on_failure("missed_call");
	}

	if (!t_relay()) {
		send_reply("500","Internal Error");
	};
	exit;
}




branch_route[per_branch_ops] {
	xlog("new branch at $ru\n");
}


onreply_route[handle_nat] {
	
	xlog("incoming reply\n");
}


failure_route[missed_call] {
	if (t_was_cancelled()) {
		exit;
	}

	# uncomment the following lines if you want to block client 
	# redirect based on 3xx replies.
	##if (t_check_status("3[0-9][0-9]")) {
	##t_reply("404","Not found");
	##	exit;
	##}

}

**Comment by liviuchircu** [comment]
@rubbermaiden I suggest trying the latest `2.3` branch mid_registrar. There have been a few fixes prior to the ClueCon OpenSIPS training concerning this issue. Same thing for @nikbyte - let me know if the errors persist.

**Comment by nikbyte** [comment]
Sorry, cannot check now because we avoided of use mid_registrar in that configuration because of problems.

**Comment by rubbermaiden** [comment]
Hi Liviu.
Thanks lots.
I made a git clone of the latest 2.4-dev branch and the calls started to go thru.
I found some bugs in the mid_registrar module and fixed it. 
I had some segfaults due to null pointer exception when dealing with mid_registrar and replication using clusterer module with binary interface.
So feel free to apply my patch if you want.
