### ISSUE TITLE
Opensips 2.5 : Not able to set the multiple cipher list in default tls domain

### ISSUE THREAD

**Issue by varghesepaul** [OpenSIPS/opensips#1185]
Hi Team,

We are not able to set the multiple cipher list in default tls domain. 

modparam("tls_mgm", "ciphers_list","AES128-SHA256:AES256-SHA")

In this case , opensips parser setting  AES128-SHA256 as domain since we have a ssl cipher seperation by ':'. 

int tlsp_set_cplist(modparam_t type, void *in)
{
        str id;
        str val;
        split_param_val( (char*)in, &id, &val);
        if (tls_db_enabled && id.s)
                return -1;
        set_domain_attr( id, ciphers_list, val.s);
        return 1;
}

So we should modify the default profile to parse the ':' in case of cipher list. 

Server domain is working fine , but not in the default profile.

**Comment by bogdan-iancu** [comment]
@varghesepaul , what OpenSIPS version are you using ?

**Comment by bogdan-iancu** [comment]
This issue was fixed in 2.3, see README http://www.opensips.org/html/docs/modules/2.3.x/tls_mgm.html#idp5633360, so you can do:
`modparam("tls_mgm", "ciphers_list", "[dom]AES128-SHA256:AES256-SHA")`

There is no conflict between the chipher list and the TLS domain name.
Still the problem exists in 2.2.x as the fix cannot be done without breaking the backword compatibility when comes to syntax.
