### ISSUE TITLE
OpenSIPS 2.2.x - 477/TM Error

### ISSUE THREAD

**Issue by linuxpakistan** [OpenSIPS/opensips#1221]
Dear Sir,

I am using OpenSIPs version 2.2 and when we register we have no issue but when i try to make call i get error message 477/TM. I have searched about it but i could not got any solution to this problem.

I am attaching my opensips configuration file.

[https://dpaste.de/FBAO](url)

Looking forward for response from your side.

Thank you.

**Comment by razvancrainea** [comment]
This seems to be a configuration issue, not an issue with the code. Please use the [Users mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users) for such issues. I will close this issue here.
When writing a report, please provide all the information you can get: i.e. the customer is behind TCP, the syslog ERRORs, etc.

PS: the url you have posted is invalid
