### ISSUE TITLE
JSON: remove whitespaces when convert JSON to string

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1241]
Sometimes whitespaces in JSON eat up to 30% space. I added this small patch to have "compression" parameter. When this parameter enabled, whitespaces removed. Please apply it to master. Need to be added into docs (patch not included docs).

[json_compression.patch.txt](https://github.com/OpenSIPS/opensips/files/1592984/json_compression.patch.txt)

**Comment by razvancrainea** [comment]
I find this approach too robust - in case you sometimes want to have a readable json, but other times you don't. That's why I came up with a different approach: add two different variables `$json_compact` and `$json_pretty`, which indicate how the json should be printed. I pushed this in feature in commit 596271ae13bb28669a4d907885c0303165b708fb and updated the [docs](http://www.opensips.org/html/docs/modules/2.4.x/json#idp5498576).
