### ISSUE TITLE
db_default_url doesn't work with permissions module

### ISSUE THREAD

**Issue by Jeffrey2019** [OpenSIPS/opensips#1246]
Dear Sir/Madam
I am using OpenSIPS 2.3
I unified db URL using db_default_url, it works fine until I add permissions module.
db_default_url = "postgres://opensips:opensipsrw@localhost/opensips"

I must add below line to start opensips.
modparam("permissions", "db_url", "postgres://opensips:opensipsrw@localhost/opensips")

`root@OpenSIPS12:/home/app# service opensips status
[0m opensips.service - LSB: Start the OpenSIPS SIP server
   Loaded: loaded (/etc/init.d/opensips)
   Active: active (exited) since Thu 2018-01-04 01:26:16 CST; 3s ago
  Process: 31914 ExecStop=/etc/init.d/opensips stop (code=exited, status=0/SUCCESS)
  Process: 31925 ExecStart=/etc/init.d/opensips start (code=exited, status=0/SUCCESS)

Jan 04 01:26:16 OpenSIPS12 OpenSIPS12[31942]: ERROR:permissions:check_src_addr_fixup: check_source_address needs db_url to be set!
Jan 04 01:26:16 OpenSIPS12 OpenSIPS12[31942]: ERROR:core:fix_actions: fixing failed (code=-1) at /etc/opensips/opensips.cfg:587
Jan 04 01:26:16 OpenSIPS12 OpenSIPS12[31942]: CRITICAL:core:fix_expr: fix_actions error
Jan 04 01:26:16 OpenSIPS12 OpenSIPS12[31942]: ERROR:core:main: failed to fix configuration with err code -1
Jan 04 01:26:16 OpenSIPS12 OpenSIPS12[31942]: INFO:core:cleanup: cleanup`

**Comment by bogdan-iancu** [comment]
Hi @Jeffrey2019 , maybe the README is not clear on this, but the db_url parameter in permissions module is optional, as the module provides functionality which is not DB dependent. So, the default value of the db_url is NULL and not the default_db_url (otherwise we will end requesting a DB url even if we use only non-DB functions in the module).
I will try to improve the docs on the db_url. But you still have to explicitly set the db_url in the module.
