### ISSUE TITLE
real install prefix missing last character -- OpenSIPS 2.3

### ISSUE THREAD

**Issue by Jeffrey2019** [OpenSIPS/opensips#1248]
Dear Sir
When I repeat "compile and install" action in make menuconfig.
The real install prefix is change from configured "/usr/local/" to "/usr/loca", and then to "/usr/loc".
I mean the final installed file is located under "/usr/loca", "/usr/loc".
The real final install path is keeping on eliminating last character.

I met several times today when I repeating the compile and install action. 
Of course, I didn't change install prefix at all.

**Comment by liviuchircu** [comment]
I cannot reproduce this issue. I set `PREFIX ?= /home/liviu/opensips-test/`in `Makefile.conf`, then did `Compile and Install OpenSIPS` + `Press any key to return to menuconfig` 4-5 times. Nothing was installed to anything else but `/home/liviu/opensips-test`. Any suggestions?

**Comment by Jeffrey2019** [comment]
It do happens, but sometimes not, I haven't observed the conditions it happens.

**Comment by Jeffrey2019** [comment]
OK, I successfully repeated the issue, please strictly follow below steps:
make menuconfig
press Down arrow key four time, until it point to "Exit & Save All Changes"
press Enter key five time, until it returns to shell.

make menuconfig
Press Down arrow key
Press Enter to "Compile And Install OpenSIPS"
Wait ......
Press Enter
Press q to return to shell

The issue occures!

**Comment by liviuchircu** [comment]
Yes! Thanks for that - reproduced it now. The bug is in `"Exit & Save All Changes"`. Every time, it strips off a char out of the `Makefile.conf` prefix, following this pattern:

* `PREFIX ?= /home/liviu/opensips-test/`
* `PREFIX ?= /home/liviu/opensips-test`
* `PREFIX ?= /home/liviu/opensips-tes/`
* `PREFIX ?= /home/liviu/opensips-tes`
* `PREFIX ?= /home/liviu/opensips-te/`
...
