### ISSUE TITLE
replace /usr/local/lib/opensips to /usr/local/lib64/opensips in all files 

### ISSUE THREAD

**Issue by Jeffrey2019** [OpenSIPS/opensips#1261]
Dear Sir / Madam
Since most opensips are installed on 64 bit OS, is it reasonable to change default /usr/local/lib/opensips to  /usr/local/lib64/opensips?

**Comment by Jeffrey2019** [comment]
I have made pull request for 2.2 2.3 and master respectively.

https://github.com/OpenSIPS/opensips/pull/1256
https://github.com/OpenSIPS/opensips/pull/1257
https://github.com/OpenSIPS/opensips/pull/1258

**Comment by bogdan-iancu** [comment]
Hi @Jeffrey2019, 
when you install opensips (via "make install"), the lib directory is automatically replaced with a value reflecting the installation directory (PREFIX option) and the system architecture - see this part https://github.com/OpenSIPS/opensips/blob/master/Makefile.defs#L339 where based on the `uname -r` the arch is detected and `LIBDIR` properly set to `lib64` or `lib` .
Now, the example cfg files - not sure if they should be aligned to any architecture, as they are not installed as part of "make install".
Still the `etc/opensips.cfg` is properly updated with the lib path suring installation - see https://github.com/OpenSIPS/opensips/blob/master/Makefile#L495

As I see it, everything is ok :)

**Comment by liviuchircu** [comment]
It seems like Red Hat-based systems use both `/usr/local/lib64/` and `/usr/local/lib/`, while Debian-based ones only use `/usr/local/lib/`.

**Comment by bogdan-iancu** [comment]
Does anyone see anything that actually needs to be fixed?  IMHO everything is fine as it is.

**Comment by liviuchircu** [comment]
Resolution:  Plenty 64-bit C libraries and projects still install to `/usr/local/lib` upon running `make install` (at least on Ubuntu/Debian).  Unless proven otherwise, I consider it is fair to assume that continuing to do so is not at all harmful.  Moreover, by merging this change (especially the backports), I feel that there is a good chance we break some existing workflows and automated CI software that's already out there.

Finally, if we do decide some day to proceed with the `/usr/local/lib64` philosophy, the following one-liner will be enough to replicate the changes behind all this discussion:

```
find . -mindepth 1 -type f -exec sed -i 's#/usr/local/lib/#/usr/local/lib64/#g' '{}' \;
```

Closing for now.
