### ISSUE TITLE
Ul_dump don't show how many records are there when 50 or more records are in usrloc

### ISSUE THREAD

**Issue by sekil75** [OpenSIPS/opensips#1265]
Opensipsctl fifo ul_dump command (or its alias - opensipsctl ul show) shows how many records are there in usrloc RAM table. Before I got to more than 50 records, it showed properly the number (i.e. Domain:: location table=512 records=33), but after that no records number is shown.

I reported this to bogdan_vs on irc, it was confirmed as bug. Fix is pending.

**Comment by bogdan-iancu** [comment]
Well, there is no way to fix this actually. Keep in mind that the usrloc data is highly dynamic and it is stored into a hash table with multiple locks (for data access). 
So, if we want to display how many records are before actually displaying them, it means we need to iterate twice the hash (first to count, then to display). But because of the dynamic nature of the data, the 2 iterations may produce different results, as new records may be added, old one may be removed.
So either we display the number of records at the end of the listing (which makes no sense to me) or we do not display it all (at the end you can iterate the MI output to see how many they are).
So, my suggestion is to simply get rid of that number of records info in the usrloc dump as it cannot be really fixed and it does not provide really useful info.

**Comment by bogdan-iancu** [comment]
After giving some thoughts here, we should simply discard this "super" feature of displaying in advance the number of records. It is useless and more or less impossible to do it in a right way.
