### ISSUE TITLE
b2b scenario with protocols TCP/TLS

### ISSUE THREAD

**Issue by arttemk** [OpenSIPS/opensips#1275]
Hello !

I try use b2b scenario with TLS or TCP protocol
and found a one problem with back contact to opensips (2.2.3-1)

it's always use contact with transport UDP
Contact: <sip:10.0.2.22>

And other part start send SIP packet by UDP in case we use TLS i see packet UDP on port 5061
that can not be handled by opensips

i suppose that in b2b_logic we need use get_local_contact_with_transport
instead of get_local_contact 
may be there are exists more correct way
i try like this
static inline int get_local_contact_with_transport(struct socket_info *sock, str* contact)
{
    int res = get_local_contact(sock,contact);
    if (res < 0 )
    {
        return res;
    }
    if (sock->proto == PROTO_TLS)
    {
        memcpy(contact->s+contact->len, ";transport=tls", 14);
        contact->len+= 14;
    }
    if (sock->proto == PROTO_TCP)
    {
        memcpy(contact->s+contact->len, ";transport=tcp", 14);
        contact->len+= 14;
    }
    return 0;
} 

in methods
file: logic.c b2b_process_scenario_init,
file: records.c b2bl_insert_new

in my case it work fine

may be there are exists another way to fix it ?

**Comment by bogdan-iancu** [comment]
@arttemk thank you for the report and suggestion. In order to evaluate the fix you suggested I need to fully understand your B2B scenario in the context of TCP protocol. In your cases, are all the B2B legs over TCP ? and the bogus contact (with UDP) is generated when OpenSIPS is acting as UAS or UAC in terms of B2B - maybe a small pcap showing the signaling will really be helpful here.

**Comment by bogdan-iancu** [comment]
Hi @arttemk , any chance to share the scenario or the pcap, so I can understand the failures ?

**Comment by arttemk** [comment]
Thank you !

**Comment by bogdan-iancu** [comment]
Tests and backports done, closing
