### ISSUE TITLE
benchmark problem in 2.3

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1277]
Hello!

I use benchmark in different scenarios and it works good.
However I have one simple scenario where I receive strange results.
I do bm_start_timer() right before relay in main route and then do bm_log_timer() in failure route.
In this case I receive sometimes strange results like this:
LOOKUP_RATE
	4/3036898418384464/79521/1518449209110426/759224604596116.000000
	5/3036898418444410/59946/1518449209110426/607379683688882.000000

sometimes just wrong values:
LOOKUP_RATE
	7/4736419/32031/2032535/676631.285714
	469/18221392648173736/31155/1518449398592701/38851583471585.789062

I mean 676631.285714. In dumps I see that my SIP transaction takes not more than 20 msec.

It looks like something wrong with counters.

module parameters:
modparam("benchmark", "enable", 1)
modparam("benchmark", "granularity", 0)

opensips version: latest 2.3

**Comment by bogdan-iancu** [comment]
@nikbyte , the benchmark module is to be used within the same top route (request route, failure route, branch route, onreply rout, etc). It is *not* design to be used across different types of top routes (like started in request route and ended in failure route). And this was done mainly because the benchmarking is intended to measure the time spent in executing different parts/blocks of the script  and not for measuring the time induced by the SIP signaling. 
I will add an extra note in the module docs to prevent for the future such mis usage.
