### ISSUE TITLE
Transcoding Codecs input to rtpengine...

### ISSUE THREAD

**Issue by pavanps** [OpenSIPS/opensips#1288]
Hi,

I am using Opensips 2.3.3 version and configured it with latest version of rtpengine. In the latest version rtpengine supports trans-coding of codecs. My question is how to negotiate the codec change in offer message from opensips to rtpengine. Means in rtpengine_offer([flags[, sock_pvar[, sdp_pvar]]]) what should be the flag value??. Or does the opensips version supports it or not ?

**Comment by razvancrainea** [comment]
There's currently no way to negotiate codec changes right now, but we will look into a solution to enhance the rtpengine_offer() function to support this.

**Comment by razvancrainea** [comment]
After a coupe of tests, it looks like rtpengine also accepts parameters in a non-dictionary way (as opposed to their [documentation](https://github.com/sipwise/rtpengine#transcoding)).

In order to use the transcoding, you'll have to use the `flags` parameter in the `rtpengine_offer()` function, with one of the following options:
* `transcode` - to transcode a codec towards the B side (ex: `transcode-PCMA`, if you know B "talks" PCMA)
* `codec-strip` - ignore a codec from the A side (ex: `codec-strip-PCMA`, makes sure A will not "talk" PCMA)
* `codec-mask` - use one codec for A side, but don't forward it to B side (ex: `codec-mask-PCMA`, makes A "talk" PCMA, but B will talk something else)

Credits for this [explanation](https://lists.kamailio.org/pipermail/sr-users/2018-February/100414.html) go to @rfuchs.
OpenSIPS 2.3 already supports this, just make sure you pull the lastest sources.

Best regards,
Răzvan

**Comment by razvancrainea** [comment]
Let us know if there are any issues with this. Otherwise, please close the ticket.

**Comment by pavanps** [comment]
Hi,
When am using transcoding am getting this error
"ERROR:rtpengine:parse_flags: error processing flag `codec-mask-opus': unknown error"

It is configures as,
$var(rtpengine_flags) = "RTP/AVP replace-session-connection replace-origin ICE=remove codec-mask-opus transcode-PCMA";
 rtpengine_offer("$var(rtpengine_flags)");

Please let me know if any configuration is required.

**Comment by razvancrainea** [comment]
What version are you running (output of `opensips -V`)? Did you pull the latest sources?

**Comment by pavanps** [comment]
I have updated the code and it is working fine. Am closing this ticket. Thank you.
