### ISSUE TITLE
SIP client on mobile phone receives multiple INVITE requests

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1316]
Hello collegues! Please, can you help me with understand opensips behavior?
I use configuration, similarly https://blog.opensips.org/2017/03/10/advanced-sip-scenarios-with-event-based-routing/
Subscribe on Event:
```
t_newtran();
t_wait_for_new_branches();
$avp(filter) = "aor=" + $tU + "@" + $td;
notify_on_event("E_UL_CONTACT_INSERT","$avp(filter)","INSERT_CT","120");
```
Injected branch:
```
route[INSERT_CT] {
    xlog("L_INFO", "[INSERT_CT] New contact [$avp(uri)] registered for user [$avp(aor)], inserting new branch to ongoing call\r\n");
    usleep("1000");
    t_inject_branches("event");
}
```

I have SIP softphone on mobile phone. SIP softphone registered on opensips. Then i trying to consecutively call twice on softphone and see that:
First call - on softphone sends only one INVITE after his reregistration after receives push notification. In logs, after received REGISTER and do "save("location", "e60")" i see:
```
Mar 21 14:16:46 opensips-pres-test /usr/sbin/opensips[18478]: [INSERT_CT] New contact [sip:sip1@100.100.100.100:56619;ob] registered for user [sip1@domain.com], inserting new branch to ongoing call
```
After the call is established i'm hanging up and call is ended. If i call again within ~30 seconds, i see:
softphone reregistration and opensips send multiple INVITE requests on UAC. Content on INVITE requests as same, only the branches differ. In logs i see [INSERT_CT]:
```
1) after lookup("location", "", "$tu") - after INVITE
Mar 21 14:17:03 opensips-pres-test /usr/sbin/opensips[18477]: [INSERT_CT] New contact [sip:sip1@100.100.100.100:56619;ob] registered for user [sip1@domain.com], inserting new branch to ongoing call
2) after save("location", "e60") - after REGISTER
Mar 21 14:17:03 opensips-pres-test /usr/sbin/opensips[18480]: [INSERT_CT] New contact [sip:sip1@100.100.100.100:45281;ob] registered for user [sip1@domain.com], inserting new branch to ongoing call
Mar 21 14:17:03 opensips-pres-test /usr/sbin/opensips[18480]: [INSERT_CT] New contact [sip:sip1@100.100.100.100:45281;ob] registered for user [sip1@domain.com], inserting new branch to ongoing call

```

**Softphone receives 2 INVITES with different branch, and i don`t understand why, can you help me?** I think 2 messages INSERT_CT after do save() it key key to understanding problem.
Usrloc module work in db_mode=3(DB-Only scheme). Before doing save(), in script i run this command: 
```
avp_db_query("DELETE FROM location WHERE username = '$tU' AND domain = '$td' AND user_agent = '$ua'");
```
In DB at one time may be only one registration at unique sip account and UA.

```
opensips -V
version: opensips 2.3.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, HP_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 5e0f28b
main.c compiled on 14:00:51 Feb 12 2018 with gcc 4.8.3

```

Thanks!

**Comment by kertor** [comment]
Sorry, description is not complete

**Comment by bogdan-iancu** [comment]
@kertor , it is possible to provide a pcap showing your whole experiment (first and second call, including signaling for registrations and calls) ?

**Comment by kertor** [comment]
Attached the pcap file:
[pcap-file-for-ticket.pcap.zip](https://github.com/OpenSIPS/opensips/files/2110390/pcap-file-for-ticket.pcap.zip)

**Comment by kertor** [comment]
Frames 11,12,13,14  - mobile client trying to register on opensips after received push message.
Frames 17,18 - opensips sends INVITE request after new registration. In branch for every these request  i see:
 - Frame 17: Branch: z9hG4bKe737.c2cca1d2.4
 - Frame 18: Branch: z9hG4bKe737.c2cca1d2.5

In logs from mobile client i see these INVITE requests too.

**Comment by Leevoipunlimited** [comment]
Its because mobile application registers with new callid each time (not confirming to normal rfc). 
I am wrestling with the same issue at the moment for how to keep the mobile registrations trim.. seems more and more likely mid-registrar will be the answer (although I would really like to solve this in the one box)

**Comment by atrips** [comment]
```
notify_on_event("E_UL_CONTACT_INSERT","$avp(filter)","INSERT_CT","120");
```
@kertor 120 secs seems to much. I'm considering that default fr_inv_timer default value 30sec. I do not see any logic to have notifiers to the call is already gone from the server. It's seems to me that there are an option (not checked the code) that if you make a second call before 120 sec timer is expired to end up with 2 notifications for the single registration event. This can cause the issue w/ double invite w/ different branches. I'm using timeout that is fr_inv_timer - 5sec.
@Leevoipunlimited : After fast look in the code I think that on every successful call on save() that result on usrloc memory update, notification will be issued and this is the expected behaviour by my perspective.

**Comment by Sandcrawler789** [comment]
I am seeing multiple INVITES sent because of multiple entries in the location table due to new registration on push coming with new callid. Next call arrives - push - new registration - new entry in location - more INVITES. 

NOTE: Our application developer has fixed the expires at 1 month - so they have to be removed manually as we have max_contact 10 and hit the limit in an hour or so. 

There is no way on the REGISTER caused by the push to match to the previous contact in location (due to info changing based on what network etc you are on). This is how the mobile world has implemented SIP.

My working theory at the moment is to immediately remove the registration from location logic is:

REGISTER - store pn
Call in 
Push
Register (now have 2)
INVITE forked on trigger
Remove registration


To solve this issue it would be awesome to have a function in registrar module that allowed us to pull the contacts from cached entries (not just is_contact_registered) something like pull_contact_aor and then can use it to remove or do other bits. 

Or - remove all contacts that are User-Agent XYZ or only allow one user-agent - or update if user agent = XYZ. 

It needs to be from cache and not location table (as we run db_mode 2) so i have a 60 second mismatch.

**Comment by bogdan-iancu** [comment]
@Sandcrawler789, is you mobile device at least preserving the call-id when re-registering (due a PN) ?

**Comment by Sandcrawler789** [comment]
No, on a push the register arriving is a new callid creating a new entry in location and then forking to it. 
I then make another call, a new register with new callid - i have 3 entries and it just keeps growing. Each time I am sending the INVITEs for the previous registrations and then the correct one for forking to new registration. 

At no point will the softphone ever register with the same callid from what I can A) test and B) find from the supplier. 

I have this replicated on my development system currently with all sorts of code trying to remedy this. Can supply any info/details/traces for the exact mechanisms.

**Comment by bogdan-iancu** [comment]
If I understand correctly, your device pushes a new registration (contact) each time, but without ever un-registering -> this will generate a +1 contact leak during each call to the device. Is this correct ?

**Comment by Sandcrawler789** [comment]
100% correct.

**Comment by Sandcrawler789** [comment]
Another item worth considering here.. 

While trying to work around this issue - found that when trying to remove the contacts on the AoR. The pn-uri param was being cut short. This I believe is due to the 'contact' column in location table being limited to char(255) and when db_sync (because we are mode 2) is actioned the cached information was cut short in accordance with what the db could store. 

Extending to varchar(1024) allows storing of full contact header which in turn allows for a match on the removal of the full contact string. 

I dont know whether the default script in opensips setup for char(255) but I would recommend that in any docs for (push or handling mobile) this field may require extending.

**Comment by Sandcrawler789** [comment]
Another issue worth considering...

UA1 and UA2 registered to same AoR. 
UA1 - no nat
UA2 - nat

Call is sent to UA1.
Call for UA2 is injected to branch on REGISTER event. 

ACK arrives to the 200OK to take call to answer. 

Nathelper cannot find the NAT_BFLAG on branch 0 - because its not there.
I cannot interrogate UA2 branch for the NAT_BFLAG - because its not there. 

Call falls apart after 32 seconds.

**Comment by bogdan-iancu** [comment]
@Sandcrawler789 , after doing the inject, why not removing (as you suggested) the contact via the [remove()](https://opensips.org/html/docs/modules/2.4.x/registrar.html#func_remove) function ? this will prevent any leak of contacts, considering that the device will re-register during each PN request.

Also, I got you note on the size of the contact field in `location` table, let me check.

For your last scenario (UA1 and UA2) - which device is pickup up the call ? 1 or 2 ? and could you be more specific on the problem you see with the ACK and the NAT bflag ?

**Comment by Sandcrawler789** [comment]
I had to approach a different way.. 

I split the handset away and am now treating it as a separate handset entirely as the registration issue was causing a number of issues. 

I did try what you had suggested Bogdan.. I had something like:

`# Remove old registration
#$avp(reg_aor_rem) = "sip:" + $avp(aor);
#$avp(reg_con_rem) = "sip:" + $avp(uri);

#xlog("L_INFO", "$avp(callid) FORK: AoR to remove from: $avp(reg_aor_rem) Contact to remove: $avp(reg_con_rem)\n");

#remove("location", "$avp(reg_aor_rem)" , "$avp(reg_con_rem)");
`

I cannot remember what the issue was but it was not 100% removing the registrations. Also this means that each time forked to the registration is removed and nothing appears in the location table.. So our UI that reports user is registered would always show the user not registered. And a bunch of other things (I have been on holiday for a week and worked on a few things since so cannot quite remember). 

I did:

`if($ua=~"^MOBILEAPPUA" && $tU=~"SOMEUNIQUEUSERNAMEPREFIXORSUFFIX"){
        xlog("L_INFO", "DEBUG: Mobile App register\n");
        if(!save("location", "p0vfc1")){
                xlog("L_INFO", "Saving contact failed -11 - M=$rm RURI=$ru F=$fu T=$tu IP=$si ID=$ci\n");
                sl_reply_error();
                exit;
        }
} else {
        xlog("L_INFO", "DEBUG: Not register\n");
        if(!save("location", "p0v")){
                xlog("L_INFO", "Saving contact failed -11 - M=$rm RURI=$ru F=$fu T=$tu IP=$si ID=$ci\n");
                sl_reply_error();
                exit;
        }
}
`

So forcing the registration over its previous one. 
I am then handling the forking elsewhere (if I require to fork). 

I also fixed the length of the URI so as the first invite goes through on the Androids.. since the Google FCM API key is too long. The RURI reaches over 255 bytes and most Cisco firewalls block any URI over 255.

So..

`$var(moboriginURI) = "sip:" + $si + ":" + $sp;

if(dr_is_gw("$var(moboriginURI)", "2") && is_method("INVITE")){
        avp_db_query("select username from dbaliases where alias_username = '$rU' and alias_domain = '$rd'", "$avp(rewrite_ruri)");
        if($avp(rewrite_ruri)=~"SOMEUNIQUEUSERNAMEPREFIXORSUFFIX"){
                xlog("L_INFO", "DEBUG: Regex on RURI\n");
                $avp(regex_replace_1) = "/(.*)TCP(.*)/\1TCP/g";
                $ru = $(ru{re.subst,$avp(regex_replace_1)});
                xlog("L_INFO", "DEBUG: $ru\n");
        }
}
`

So when arriving from a particular node and is INVITE, check for username is a mobile app and then only take up to the transport.
This will result in the PN removed from the URI and the first INVITE will reach the phone.
Subsequently.. NAT works properly when the initial INVITE goes and the injection never occurs. 

This is also required to be done in the fork.

`$avp(regex_replace) = "/(.*)TCP(.*)/\1TCP/g";
$avp(uri) = $(avp(uri){re.subst,$avp(regex_replace)});
`

IMPORTANT NOTE: for those who just dive in.. the fork route has a different set of AVP to action the regex against. Note the avp to which the regex is applied here and from the above code in main routing. 

It would be nice to work out something to nicely handle the complete disregard from the mobile world for the SIP specs. But I think we have a thing that works at the moment with the above few bits.

**Comment by bogdan-iancu** [comment]
@Sandcrawler789 , indeed, there are interesting and valid bits and pieces regarding the mobile world.
Now, I'm trying to focus back on the actual reported issues (bugs). Besides the len of the contact field, is anything else to be labeled as bug/problem here ?

**Comment by Sandcrawler789** [comment]
@bogdan-iancu 

I believe there are 2 issues.

1) Is the length of the contact header that seems to cause issues when trying to pass back out the URI. 

Something like Opensips having options to handle pn fields would be cool and strip them or handle them better when passing the contact back out for use.

2) The registrations arriving with different callid and filling an AoR, not overwriting. 

If overwriting is turned on then any other handsets (like desk phones also will be overwritten by the unrelenting mobile registrations).
Handling this better would allow for nice use of forking within Opensips in combination with Event. 


These are the 2 core issues i perceive as being blocking factors to a nice solution. 

As I say we split ours away and handle forking elsewhere. BUT, we would like to do it the way that Opensips documents and are keen to see a resolution to these items within Opensips.

**Comment by bogdan-iancu** [comment]
Thanks @Sandcrawler789 . For (1), the fix is clear ;)

For (2), it is more delicate. Ignoring the implementation details, do you have any logical solution for that? how to overwrite a previous PN registration, but without touching a regular one ?

**Comment by Sandcrawler789** [comment]
2) Is an interesting problem.. 

I can think of a number of ways to fix it and a number of ways to again break it with that in place. 

Simple ways:

a) UA match flag which would break all specs and just match on username/pass/ua (I feel dirty typing it). This same flag would switch off contact and/or callid matching. 
Please do not do this. 

b) Prefix/Suffix on username that is stripped before checking so as to be able to provision mobile phones with Username prefix.

if register
if !save <prefix_flag>'mob_' 
then strip mob_ and register with username.
By having detected mob_ can register over last record that registered with mob_ (this would limit the account to having only 1 mobile contact). Would also require new column in location for flagging for persistence.
This is limiting but an intermediary fix.. bit meh though. 

Getting trickier:
 
c) Index contacts within AoR.
Within index of contacts within AoR you could:

modparam enable_save_flag

if register
if ua <some_ua>
save_flag([0])
else if ua <some_other_ua>
save_flag([1])
else if ct.param=rinstance
save_flag([2])
else 
save_flag([3-N])
if !save
then uses flag as index to register into. 

This lifts the logic for what to overwrite out into the script. 

This is ok.. but i imagine handling the indexing of those records underneath to be a big job. 

d) Something a bit more off the wall.. (not sure I like this). 
Doing it on the flags in the save function by defining overwrite groups of contacts within the max. 

cnn - max contacts

modparam <contact_change>

cann - max all contacts
c1nn - define how many of the contacts in the AoR are the first group
c2nn - define how many of the contact in the AoR are in the first group.
rest are group 3 or none or error if 1nn+2nn>nn

(Add as many groups required - although I think 2-3 only).

c1=f - group 1 is forced
c2=n - group 2 not forced

if ct.param rinstance 
save c1
else if ct.param ! rinstance 
save c2


A lot of my ideas (above and not here) suggest that indexing the contacts and elevating the logic into the script for where to apply the 'force' option (ie a specific index based on the developers choice), seems to be the answer.. although this does open up the platform to abuse of registration mechanisms (adding/removing of headers from user end could screw some logic).

For me option c) is most akin to what I would feel comfortable with.. might need a bit of thinking about though.

**Comment by hasanr68** [comment]
@Sandcrawler789 @bogdan-iancu having the same issue. I did search and was wondering if this was implemented/tried/tested pls? And how would save_iflag work?
