### ISSUE TITLE
loose_route can not  get received ip/port when UA is under TCP transport (Path Module)

### ISSUE THREAD

**Issue by futsystems** [OpenSIPS/opensips#1358]
UA1---[Home Proxy]---[Registrar]
UA2---
Home Proxy use path module to stay in path.

if UA1 UA2 use TLS or UDP transport, all works well.
but if UA1 use TCP transport, UA2 make a call to UA1, the invite request can not send to UA1 properly.

script:

loadmodule "path.so"
modparam("path", "use_received",1)

route[1] {
	#request from registrar
	if(($si == "IP_REGISTRAR")&&($sp == "5060")){
		#on net call,registrar send invite to proxy together with path route and received
		if(method=="INVITE")
		{
			loose_route();
			if($hdr(Call-Type)=="OnNet")
			{
				xlog("L_INFO","OnNet invite to UA:$tU,loose route $dd:$dp");
			}
			xlog("L_ERR","-->REQUEST FROM REGISTRAR: FAIL [$rm] ru[$ru] fu[$fu] tu[$tu] s[$proto:$si:$sp] CID[$ci][TIME:$time(%H:%M:%S).$Tsm]\n");
			
		}
		
		if (!t_relay("0x01")) {
			xlog("L_ERR","-->REQUEST FROM REGISTRAR: FAIL [$rm] ru[$ru] fu[$fu] tu[$tu] s[$proto:$si:$sp] CID[$ci][TIME:$time(%H:%M:%S).$Tsm]\n");
			sl_reply_error();
		}
		else
			xlog("L_INFO","REQUEST FROM REGISTRAR: [$rm] ru[$ru] fu[$fu] tu[$tu] s[$proto:$si:$sp] CID[$ci][TIME:$time(%H:%M:%S).$Tsm]\n");
	}
}

so as i understand,
registrar will send invite request form other UA to Home Proxy with route set.
Home Proxy loose_route() will get received ip/port as destionation to send the request.

as in my log:
if callee is UDP or TLS
 OnNet invite to UA:5280003,loose route 117.90xxx.xxx:53751

if callee is TCP
 OnNet invite to UA:62000001,loose route <null>:<null>

so i guess maybe it is a bug or so.

**Comment by liviuchircu** [comment]
I have a feeling that this `use_received` mechanism has slowly become deprecated -- I will get back to you with further findings as I familiarize with it myself. Also, I do not yet understand how TLS works and TCP doesn't (as TLS heavily depends on the TCP engine!) -- a SIP trace of the UDP vs. TCP registration flow would be very helpful here. Lastly, what exact `opensips` version are you using?

Meanwhile, can you please make the following amendments to your setup and let me know if behavior improves:

* on the proxy, use `add_path_received()` instead of just `add_path()` (if not already doing this)
* on the registrar, enable the `"v"` flag of `save()`, which will store the "received" information found inside the Path header. When looking up the contact, this information will automatically be placed in the R-URI, such that the proxy will be able to route out the initial request to the proper source IP:port.

**Comment by futsystems** [comment]
I am using opensips 2.3    5e0f28b.
on the home proxy, i already use app_path_received() to keep received info in the registrar request.
on the registrar i am using these script to save location info.

	if (!save("location","p1v"))
		sl_reply_error();

so now i keep UA2 use UDP, chagne UA1 transport TCP,TLS,UDP 

Result: UA1 do not receive invite request under TCP.

from opensips log, after loose_route(), there is no $dd:$dp. maybe opensips send request to contact ip/port.(**private ip/port**).

all the script running  in home proxy and registrar is same. just change UA1's transport.
**Notice:** UA do not rewrite the contact and via address, opensips do not fix contact address too.
just use Path module to send incoming request to received ip/port.
