### ISSUE TITLE
listen 180+ ports will make opensips quit running 

### ISSUE THREAD

**Issue by xiaoluweiba** [OpenSIPS/opensips#1393]
I config opensips-2.3 listen 200 port(include 196 UDP , 2 TCP, 2TLS) then type opensipsctl start, it will run in a short time before exit.

**Comment by bogdan-iancu** [comment]
@xiaoluweiba, do you have any error logs from OpenSIPS in regards to this setup ?

**Comment by xiaoluweiba** [comment]
[test_log.zip](https://github.com/OpenSIPS/opensips/files/2113476/test_log.zip)
Hi, I have tested three times and caught the log in the compressed package, tks

**Comment by xiaoluweiba** [comment]
PS: opensipsctlrc -> STARTOPTIONS="-m512 -M64"

**Comment by razvancrainea** [comment]
@xiaoluweiba from the logs you have sent it looks like mysql starts rejecting new connections because there are too many. OpenSIPS creates a mysql connection from each of its processes, therefore when you start opensips you will have at least 200 connections to your server. Try to increase the number of allowed connections in the mysql server and let us know if this still happens.

**Comment by xiaoluweiba** [comment]
I increased the max_connections to 500 then mysql restart, opensipsctl restart, The problem seems to have disappeared.
I will continue testing
thank you very much @razvancrainea @bogdan-iancu
