### ISSUE TITLE
not enough free pkg memory

### ISSUE THREAD

**Issue by xiaoluweiba** [OpenSIPS/opensips#1439]
opensips log:
/sbin/opensips[32057]: ERROR:core:fm_malloc: not enough free pkg memory **(63119536 bytes left, need 18424)**, please increase the "-M" command line parameter!

As the log show: left memory is enough.

-M:  Various private memory related statistics for each OpenSIPS process

I have a question about that:  config "-M=64" and start  OpenSIPS Process(listen 100 ports use children 1) on 2G memory linux system, I suppose it will can't run(need 6400M,but totol memory is 2048M), but it works well.

**Comment by razvancrainea** [comment]
Most likely your memory becomes very fragmented, and opensips cannot find contiguous space of size `18424` bytes, even though smaller chunks summed up appear to have enough memory. In order to gather more information, can you enable memory dump and next time you get that error, send a `SIGUSR1` signal to the process that reports that error? In order to enable memory dump, you have to add the following lines in your script:
```
memlog=10
memdump=1
```

Regarding your second question, the answer is simple: opensips will ask for 6400M of virtual memory, but the operating system will only allocate the amount of memory opensips will actually use. Therefore, if opensips will only use 10K from 10 processes, the residual memory used will only be 100K. Moreover, even if opensips will use all the 6400M requested, it will still work if you have enough swap space. If you want to understand this behavior better, read more about [virtual memory](https://en.wikipedia.org/wiki/Virtual_memory) and swap space.

**Comment by xiaoluweiba** [comment]
thank for your  answer.

use memlog and memdump flag need to recompile opensips?

Do you have any document  about how to debug opensips memory leak or thread lock ....~.~?

**Comment by bogdan-iancu** [comment]
http://www.opensips.org/Documentation/TroubleShooting-OutOfMem
