### ISSUE TITLE
opensips route  external to internal

### ISSUE THREAD

**Issue by seanchann** [OpenSIPS/opensips#1451]
hi,
   I have the following creations：
   1. opensips behind nat and have one interface bind with internal ip 10.10.10.1
   2. sip message receive from external with public ip(55.13.2.1)
   3. then opensips route this message to internal sip server.
   4. in onreply route, I want to fix 200ok to use public ip. if we use internal ip the ack message can't receive from the external uac.  I use `set_advertised_address(55.13.2.1)` ,but it not work.

   opensips version: 2.2.5
   how to fix it?

**Comment by bogdan-iancu** [comment]
You should not fix the contact in 200 OK, but the RR header in the INVITE - this will drive the ACK and the sequential requests.
In your case OpenSIPS advertises two identities (public and private) via the same listener. To do this, you should user the [record_route_preset()](http://www.opensips.org/html/docs/modules/2.3.x/rr.html#idp5546464) function. And do not forget to add 55.13.2.1 as alias in OpenSIPS, otherwise it will not consider that IP as local.
Anyhow, your issue is not bug, it is more about how to configure OpenSIPS, so I strongly suggest to follow this on the OpenSIPS user's mailing list.

**Comment by seanchann** [comment]
@bogdan-iancu ok! thanks!
