### ISSUE TITLE
drouting not follow database state when update gateways

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1474]
Hello team,

I use drouting. After server started I have all my gateways active.
Then I change state into 1 for some gateways in dr_gateways table.
After dr_reload all my gateways are still active.

Only after opensips restart I have gateways properly loaded.

It's on latest 2.4. Possible to fix?

**Comment by razvancrainea** [comment]
Currently opensips synchronizes the gateway's cache with the database every 30s. This means that if you change the state of a gateway and then reload in less than 30s, you will see that gateway back online. Do you think this is the issue you are experiencing?

**Comment by nikbyte** [comment]
I think you tell about
modparam("drouting", "persistent_state", 1)
correct?

what about if modparam("drouting", "persistent_state", 0) ?
I have persistent state disabled.

I just want to change value in DB and reload it any time.

**Comment by razvancrainea** [comment]
Yes, that's what's happening when you set `persistent_state` to 1. if you set it to 0, you won't get the state of a gw in DB at all.
Unfortunately there's no way to reflect the state immediately in the database right now, but if you really need this, we can mark it as a feature request.

**Comment by bogdan-iancu** [comment]
Just an extra clarification before closing: the `persistent_state` ensures the persistence of GW/carrier in-memory status during an OpenSIPS restart. As @razvancrainea said, the GW/carrier status is pushed back to DB every 30 secs, so after you restart opensips and reading the status from DB, you will have the same in-memory status as before the restart.

If you want to change the GW/carrier status during runtime, changing the DB and doing reload is a bad practice. The correct way to do it is to use the MI command `dr_gw_status` and `dr_carrier_status` - they directly change the in-memory status.

**Comment by nikbyte** [comment]
Bogdan, this ticket is not about what you say.

You both are talking about persistent_state=1. What about persistent_state=0?
Nothing saves into DB (it's ok).

But. Why starting of opensips follows state column, but reload doesn't follow? Something wrong here.
Opensips must ignore this column on startup or must respect it on reload (which is better).

**Comment by bogdan-iancu** [comment]
@nikbyte , yes, if `persistent_state` is disabled (0), no state is loaded from DB, no state is written in DB - this is the exact behavior the module had before adding the "persistent_state" feature.

Now, why reload is not reading status from DB ? because by design the "status" field in DB is to be used only for restart purposes, nothing more. During runtime, the status of GWs/carriers is kept in memory.
And let me give you an example: I have 4 GWs, A, B, C and D - initially they are all enabled, but during runtime C and D are learned as faulty and disabled (or disabled on purpose by admin). Now, I want to add the fifth E GW . After doing the reload (for adding the GW), what do you see as normal behavior:

a) A, B, C and D to preserver they status (C and D disabled)?

b) all GWs are back to enabled ??

Right now is (a), but you suggest (b), which IMHO is wrong - I do not want any reload to change the status of my existing GWs!!

**Comment by nikbyte** [comment]
Ok, I understand your position. Thank you for the explanation.
