### ISSUE TITLE
[usrloc] Crash when un-registering all contacts 

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#1512]
The 2.4 version crashes when handling an un-register all requests in `full-sharing-cluster` mode:
`Contact: * `

**Comment by vasilevalex** [comment]
@bogdan-iancu OpenSIPS 2.4.2 with full-sharing-cluster, with mid_registrar definitely doesn't crash. All the phones configured with "Remove all bindings on unregister", so I always get REGISTER with  `Contact: *`. The only thing I don't like is additional REGISTER request made by mid_registrar to main registrar with `Contact: <sip:200@proxyIP:5060>;expires=0` after forwarding first REGISTER from phone. Because this doesn't make sense as first message already unregister endpoint. With SIP-trace here: http://opensips-open-sip-server.1449251.n2.nabble.com/mid-registrar-remove-all-bindings-td7611229.html

**Comment by bogdan-iancu** [comment]
The setup I had is not mid-registrar related. Regular registrar + `full-sharing-cluster`.

**Comment by liviuchircu** [comment]
Fixed in 3650af33bf4
