### ISSUE TITLE
Replicating dialogs in a multi-homed environment

### ISSUE THREAD

**Issue by vladpaiu** [OpenSIPS/opensips#1514]
Hello,

Currently working in a multi-homed environment, where I have a public interface with a floating IP, and a private interface, which is local to each OpenSIPS server. Calls are flowing in either direction ( public to private, or private to public ).

When replicating dialogs through the cluster, I get rejections due to the private IPs not matching any listening sockets on the receiving servers. 

Need an approach to be able to 'fix' such private IPs appearing in binary replicated packages.

Best Regards,
Vlad

**Comment by razvancrainea** [comment]
IMO, I wouldn't call this a bug, but rather a limitation coming from your setup, which has a different private IP for each instance. This does not sound such a good idea, because in case of a failover, the endpoint behind the private network will send sequential messages to the old IP. Unless we make OpenSIPS update the routing set when a failover occurs, using pinging or something similar when the server becomes active.
On the other hand I find this request useful too, because it will support other setups (such as yours), but we also need to add some logic to update the routing set - and the endpoint has to accept it!
My proposal for this is to have a set of IPs and ports which map to a listener. And whenever `grep_sock_info()` is called for one of the aliases, the function shall return the listener which maps with that alias. Moreover, when a tag becomes active, it shall send updates for all the dialogs tagged with it to update the route set of the endpoints.
In the meantime, I will swap the label for this to `improvement`.

**Comment by petekelly** [comment]
I think this would be a huge improvement if it can be achieved. The classic situation I can think of here is an AWS instance, where you are forced to be behind a 1-1 NAT and have no ability to control the "private" IP addresses of your machines.

**Comment by nathanleyton** [comment]
This would be a great addition, along with the AWS/cloud environment use cases (Failing between availability zones), it would allow opensips to be set up as a Deployment in K8S along with all the auto-scaling etc that would come along with that. Glad to see this is being looked at.

**Comment by bogdan-iancu** [comment]
Hi all, 

Check this ticket #1597 and its solutions - https://github.com/OpenSIPS/opensips/issues/1597#issuecomment-459400155 . I think is solve this too.

**Comment by petekelly** [comment]
@bogdan-iancu check my comment in #1597 , I think you introduced a bug! Or perhaps a new feature.
