### ISSUE TITLE
cache_fetch vs cache_raw_query

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1564]
Hi Team,

why cache_fetch supports any variables as result, but cache_raw_query only avp?
isn't this an error?

**Comment by liviuchircu** [comment]
Because `cache_fetch()` cannot produce a list (it's a specific key/value interface function), while `cache_raw_query()` may, for example, fetch all documents of a given MongoDB collection -- to make it easiest for the user to process their data, it's best to just force an `$avp` output variable argument.

**Comment by nikbyte** [comment]
I've got you. Reasonable. Thanks.
