### ISSUE TITLE
[BUG] Opensips 3.0.0-beta B2B Instance + db_cachedb + MongoDB

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1606]
Dear Team,

I am using Latest OpenSIPS 2.4.4 as B2BUA + db_cachedb + MongoDB.

If I try to restart the OpenSIPS B2BUA Instance if there is an ongoing call through the B2BUA , the
instance doesn't start.

If I clear the table b2b_entities from MongoDB then the B2BUA can be started again.

I have separated the logs 
1) B2B Call Initiate --> https://pastebin.com/TdN8S6uP
2) B2B Call Reply --> https://pastebin.com/B8jKKUbm
3) after Instance restart --> https://pastebin.com/nvhci4H6
 
opensips.cfg (not any special config just topology hiding)

### Mongo CacheDB
loadmodule "db_cachedb.so"
loadmodule "cachedb_mongodb.so"
modparam("db_cachedb","cachedb_url","mongodb:b2b_entities://MONGODB_IP:27017/opensipsDB.b2b_entities`'MY_CLUSTER_ID")
modparam("db_cachedb","cachedb_url","mongodb:b2b_logic://MONGODB_IP:27017/opensipsDB.b2b_logic`'MY_CLUSTER_ID")

#### B2BUA module
loadmodule "b2b_entities.so"
loadmodule "b2b_logic.so"
loadmodule "uac.so"
loadmodule "uac_auth.so"

modparam("b2b_entities", "db_url", "cachedb://mongodb:b2b_entities")
modparam("b2b_entities", "db_mode", 1)
modparam("b2b_entities", "replication_mode", 1)
modparam("b2b_entities", "script_req_route", "b2b_request")
modparam("b2b_entities", "script_reply_route", "b2b_reply")

modparam("b2b_logic", "db_url", "cachedb://mongodb:b2b_logic")
modparam("b2b_logic", "db_mode", 1)
modparam("b2b_logic", "use_init_sdp", 1)
modparam("b2b_logic", "update_period", 2)
modparam("b2b_logic", "max_duration", 10800)
modparam("b2b_logic", "cleanup_period", 10)
modparam("b2b_logic", "custom_headers", "P-Asserted-identity;Privacy;Diversion")

The idea behind this use of MongoDB is to be able to read call states if for some reason the service is restarted (update / or crash) so it can be able to handle again the calls.

Thank you in advance

Vasilios Tzanoudakis

**Comment by bogdan-iancu** [comment]
@vtzan , have you tried the same scenario but using the SQL support rather than NoSQL (via the db_cachedb) ? I'm asking as this SQL to noSQL coversion has its limitations and it doesn't work out of the box in all scenarios.
The test I suggested may point if the issue is in the B2B or in the db_cachedb .

**Comment by vtzan** [comment]
@bogdan-iancu thank you for your reply.

I have changed the db url to mysql for b2b_entities & b2b_logic (if this is what you meant to try)

```
modparam("b2b_entities", "db_url", "mysql://opensips:password@localhost/opensips")
modparam("b2b_logic", "db_url", "mysql://opensips:password@localhost/opensips")
```

and restarting opensips instance while there is an on going call is working fine!

I have a setup where 2 opensips instances are running on the same host (one edge proxy and one b2bua) and the whole edge proxy db config is configured with  cachedb_mongodb and would be great to be able to handle the b2bua instance also on the same MongoDB too. 

Thank you in advance
Vasilios Tzanoudakis

**Comment by bogdan-iancu** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Vasilios Tzanoudakis <notifications@github.com> Date: 3/10/19  23:30  (GMT+02:00) To: OpenSIPS/opensips <opensips@noreply.github.com> Cc: Bogdan Andrei IANCU <bogdan@opensips.org>, Mention <mention@noreply.github.com> Subject: Re: [OpenSIPS/opensips] B2B Instance + db_cachedb + MongoDB (#1606) @bogdan-iancu thank you for your reply.
I have changed the db url to mysql for b2b_entities & b2b_logic (if this is what you meant to try)
modparam("b2b_entities", "db_url", "mysql://opensips:password@localhost/opensips")
modparam("b2b_logic", "db_url", "mysql://opensips:password@localhost/opensips")

and restarting opensips instance while there is an on going call is working fine!
I have a setup where 2 opensips instances are running on the same host (one edge proxy and one b2bua) and the whole edge proxy db config is configured with  cachedb_mongodb and would be great to be able to handle the b2bua instance also on the same MongoDB too.
Thank you in advance
Vasilios Tzanoudakis

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSIPS/opensips","title":"OpenSIPS/opensips","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSIPS/opensips"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vtzan in #1606: @bogdan-iancu thank you for your reply.\r\n\r\nI have changed the db url to mysql for b2b_entities \u0026 b2b_logic (if this is what you meant to try)\r\n\r\n```\r\nmodparam(\"b2b_entities\", \"db_url\", \"mysql://opensips:password@localhost/opensips\")\r\nmodparam(\"b2b_logic\", \"db_url\", \"mysql://opensips:password@localhost/opensips\")\r\n```\r\n\r\nand restarting opensips instance while there is an on going call is working fine!\r\n\r\nI have a setup where 2 opensips instances are running on the same host (one edge proxy and one b2bua) and the whole edge proxy db config is configured with  cachedb_mongodb and would be great to be able to handle the b2bua instance also on the same MongoDB too. \r\n\r\nThank you in advance\r\nVasilios Tzanoudakis\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenSIPS/opensips/issues/1606#issuecomment-471355809"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OpenSIPS/opensips/issues/1606#issuecomment-471355809",
"url": "https://github.com/OpenSIPS/opensips/issues/1606#issuecomment-471355809",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bogdan-iancu** [comment]
Hi @vtzan , so having the B2B modules pointing to a mysql DB fixes the problem. If so, we can logically say that the db_cachedb module (in combination with Mongo) has some issues when being used for B2B.

**Comment by vtzan** [comment]
Hi @bogdan-iancu yes indeed!
If there is something I can do to help you to debug this problem let me know. 
I will proceed with mysql for now.

Best Regards
Vasilios Tzanoudakis

**Comment by bogdan-iancu** [comment]
Hey @vtzan , do you have a backtrace from that crash ?

**Comment by vtzan** [comment]
Dear @bogdan-iancu ,

I have abandoned MongoDB and 2.4.x
I have moved to Cassandra and I would like to test that case with Cassandra if its possible but I can run a test with 3.0.0 version and mongo if you are interested in this case. Let me know.

**Comment by vtzan** [comment]
Dear @bogdan-iancu,

I have just reproduced the issue with the latest master code.

I have sent you the full debug logs to your email.

`version: opensips 3.0.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 022166a51
main.c compiled on 13:03:30 May 30 2019 with gcc 6.3.0
`

Regards
Vasilios Tzanoudakis

**Comment by bogdan-iancu** [comment]
Working offline with @vtzan to get a backtrace here

**Comment by bogdan-iancu** [comment]
@vtzan , let me know if you have any progress with getting the core file and the backtrace.

**Comment by vtzan** [comment]
@bogdan-iancu I have emailed you all the information

**Comment by bogdan-iancu** [comment]
After a `gdb` session with @vtzan , we found that even if the `b2b_entities` modules inserts an empty string for display To/From, when using the `db_cachedb` + `cachedb_mongodb`, the value is read / returned as NULL - and the code does not expect a NULL value there - this is even stranger as the sql definition of the table has no `not NULL` enforcement for those columns...
The fix will be to check for NULL values when reading for restore.

**Comment by bogdan-iancu** [comment]
@vtzan , if you could give me a confirmation of the fix, it would be great ;)

**Comment by vtzan** [comment]
@bogdan-iancu Yes it's working!!! thank you
