### ISSUE TITLE
[Feature] split the geoip module for v2 and leagacy version.

### ISSUE THREAD

**Issue by netaskd** [OpenSIPS/opensips#1618]
By default geoip module in the packages is only legacy version, because the package "maxminddb" is not exists on the build machine: https://github.com/OpenSIPS/opensips/blob/0bb4c66480c583a7587cfe52a89bb669d7a8b0b9/modules/mmgeoip/Makefile#L32
So it would be grate to split the pakage "opensips-geoip-module" to two versions "opensips-geoip2-module" and "opensips-geoip-module" for the back compatibility.
https://github.com/OpenSIPS/opensips/blob/6a6da348b76d510d530e075b53ca8ef7edfed37f/packaging/debian/rules#L138

**Comment by razvancrainea** [comment]
The current build mode does not allow us to build two different packages. Therefore the solution I am thinking of is to somehow prioritize the build against the V2 version. This way, whoever builds the debs, can choose to install one version or another, depending on their requirements.
I've also added the `libmaxminddb-dev` Build dependency in the debian packages, so that whoever runs `apt-get build-dep`, will get the V2 if nothing else has been installed. @nikbyte , could you please add this dependency on RedHat/CentOS specs as well?
Also, I'd say we should prioritize V2 in public packages too. Therefore, @nikbyte, could you please add the `libmaxminddb-dev` requirements to the building logic?

**Comment by nikbyte** [comment]
rpm is already using maxmind.

**Comment by razvancrainea** [comment]
You're right, the interface has changed, therefore it will break current installs. Let's leave it like that now, as the current system does not allow us to build both versions.
