### ISSUE TITLE
[Crash] Opensips 3.0 Crashing on startup after 2.4 upgrade

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#1757]
Hi,

We are trying to install Opensips 3.0, please find the crash file.

**OpenSIPS version**

```version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d80949d46
main.c compiled on  with gcc 7
```

**Crash Core Dump**
Here is the core dump file http://tiny.cc/amfg9y

Regards
Rizwan

**Comment by liviuchircu** [comment]
Hi, @syedrizwansrs !  How have you performed the upgrade:  by installing the `3.0` packages, or by switching to the latest `3.0` branch and recompile/reinstall?

I'm asking because this smells like a module exports misalignment issue, which is a compilation issue and can be easily solved by doing a `make proper` and `make install`.

**Comment by syedrizwansrs** [comment]
Hi @liviuchircu, this was done using 3.0 packages & was a clean install (on a fresh OS install), tried both stable and nightly version.

**Comment by liviuchircu** [comment]
Thank you for the report @syedrizwansrs, the issue should be fixed now.
