### ISSUE TITLE
[BUG] cluster info  configured in the script(via my_node_info and neighbor_node_info) have no effect

### ISSUE THREAD

**Issue by tangshiixang** [OpenSIPS/opensips#1775]
My opensips version is 3.0.
two instances of cluster never communicate with each other;
if I use mysql for storing node info, It can only work well!

**Comment by bogdan-iancu** [comment]
@tangshiixang , you say if you provision your cluster via DB it works, but if you provision it via modparams it doesn't ?
If so, post here the `my_node_info` and `neighbor_node_info` for both instances.

**Comment by bogdan-iancu** [comment]
> If so, post here the my_node_info and neighbor_node_info for both instances.

**Comment by tangshiixang** [comment]
@bogdan-iancu ：
instance 1：
modparam("clusterer", "my_node_info", "cluster_id=1, url=bin:192.168.1.2:3111, state=1, no_ping_retries =3, priority=50,sip_addr=NULL, flag=NULL")
modparam("clusterer", "neighbor_node_info", "cluster_id=1, node_id=2, url=bin:192.168.1.2:3222, state=1, no_ping_retries=3, priority=50,sip_addr=NULL, flag=NULL")

instance 2：
modparam("clusterer", "my_node_info", "cluster_id=1, url=bin:192.168.1.2:3222, state=1, no_ping_retries =3, priority=50,sip_addr=NULL, flag=NULL")
modparam("clusterer", "neighbor_node_info", "cluster_id=1, node_id=1, url=bin:192.168.1.2:3111, state=1,  no_ping_retries =3, priority=50,sip_addr=NULL, flag=NULL")

**Comment by tangshiixang** [comment]
@bogdan-iancu ：
instance 1：
modparam("clusterer", "my_node_info", "cluster_id=1, url=bin:192.168.1.2:3111, state=1, no_ping_retries =3, priority=50,sip_addr=NULL, flag=NULL")
modparam("clusterer", "neighbor_node_info", "cluster_id=1, node_id=2, url=bin:192.168.1.2:3222, state=1, no_ping_retries=3, priority=50,sip_addr=NULL, flag=NULL")

instance 2：
modparam("clusterer", "my_node_info", "cluster_id=1, url=bin:192.168.1.2:3222, state=1, no_ping_retries =3, priority=50,sip_addr=NULL, flag=NULL")
modparam("clusterer", "neighbor_node_info", "cluster_id=1, node_id=1, url=bin:192.168.1.2:3111, state=1,  no_ping_retries =3, priority=50,sip_addr=NULL, flag=NULL")

**Comment by bogdan-iancu** [comment]
Also the definition of the `bin` listeners in each instance, please.

**Comment by pasanmdev** [comment]
@bogdan-iancu I'm using 2.4 and having same issue. It appears to be a bug in param parse function in clusterer_mod.c#L271

If I have just below info opensips pickups up the cluster config. But can't init any additional params like sip_addr , flags etc and it'll break the cluster config.

Node 1

listen=bin:10.20.12.37:5566

loadmodule "clusterer.so"
modparam("clusterer", "db_mode", 0)
modparam("clusterer", "current_id", 1)
modparam("clusterer", "current_info", "cluster_id=1,url=bin:10.20.12.37:5566")
modparam("clusterer", "neighbor_info", "cluster_id=1,node_id=2,url=bin:10.20.76.204:5566")


Node2 

listen=bin:10.20.76.204:5566   # CUSTOMIZE ME

loadmodule "clusterer.so"
modparam("clusterer", "db_mode", 0)
modparam("clusterer", "current_id", 2)
modparam("clusterer", "current_info", "cluster_id=1,url=bin:10.20.76.204:5566")
modparam("clusterer", "neighbor_info", "cluster_id=1,node_id=1,url=bin:10.20.12.37:5566")


Following config breaks the cluster config just like for @tangshiixang .

Node 1
listen=bin:10.20.12.37:5566

loadmodule "clusterer.so"
modparam("clusterer", "db_mode", 0)
modparam("clusterer", "current_id", 1)
modparam("clusterer", "current_info", "cluster_id=1,url=bin:10.20.12.37:5566,flags=seed,sip_addr=10.20.12.37")
modparam("clusterer", "neighbor_info", "cluster_id=1,node_id=2,url=bin:10.20.76.204:5566,flags=seed,sip_addr=10.20.76.204")


Node 2

listen=bin:10.20.76.204:5566   # CUSTOMIZE ME

loadmodule "clusterer.so"
modparam("clusterer", "db_mode", 0)
modparam("clusterer", "current_id", 2)
modparam("clusterer", "current_info", "cluster_id=1,url=bin:10.20.76.204:5566,flags=seed,sip_addr=10.20.76.204")
modparam("clusterer", "neighbor_info", "cluster_id=1,node_id=1,url=bin:10.20.12.37:5566,flags=seed,sip_addr=10.20.12.37")

issue seems to be in https://github.com/OpenSIPS/opensips/blob/cfbd704945481c97a241892da50efcb3dd84eead/modules/clusterer/clusterer_mod.c#L271

But I'm not quite sure, not that good at understanding c :). ALso I notice it only pickups sip_addr
only if I mention it as last param in the config line. otherwise it pickups whatever after url param.

Let me know if you need more info, Happy to put it here. Thanks

**Comment by pasanmdev** [comment]
output from both nodes with just clusterid,node_id and url params

admin@ip-10-20-12-37:~$ s opensipsctl fifo clusterer_list
Cluster:: 1
        Node:: 2 DB_ID=-1 URL=bin:10.20.76.204:5566 Enabled=1 Link_state=Up      Next_hop=2 Description=none

admin@ip-10-20-76-204:~$ s opensipsctl fifo clusterer_list
Cluster:: 1
        Node:: 1 DB_ID=-1 URL=bin:10.20.12.37:5566 Enabled=1 Link_state=Up      Next_hop=1 Description=none


output from both nodes with extra params

admin@ip-10-20-12-37:~$ s opensipsctl fifo clusterer_list
Cluster:: 1

admin@ip-10-20-76-204:~$ s opensipsctl fifo clusterer_list
Cluster:: 1
