### ISSUE TITLE
[BUG] Memory Leak on OpenSips 3.0

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#1795]
Hi There,

We are experiencing memory leak on Opensips 3.0, free memory is gradually reducing resulting in a crash about every 24 hour.
The below log has run time leak and during restart.

https://shorturl.at/OQUY7

**OpenSIPS version**
```
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 478291e2e
main.c compiled on  with gcc 7
```

Thanks

**Comment by johandeclercqdemocon** [comment]
You are right,   after x time I see below error lines:
Aug 12 07:34:49 hendrix /data/opensips/sbin/opensips[20422]: ERROR:core:fm_malloc: not enough free pkg memory (0 bytes left, need 16), please increase the "-M" command line parameter!
Aug 12 07:34:49 hendrix /data/opensips/sbin/opensips[20422]: INFO:core:fm_malloc: attempting defragmentation...
Aug 12 07:34:49 hendrix /data/opensips/sbin/opensips[20422]: INFO:core:fm_malloc: unable to alloc a big enough fragment!

**Comment by johandeclercqdemocon** [comment]
Hello, can somebody please give some hints on how to troubleshoot this ?

Best regards, Johan.

**Comment by bogdan-iancu** [comment]
@syedrizwansrs , I checked the dump and there is no indication of a leak (shm or pkg)

**Comment by bogdan-iancu** [comment]
@syedrizwansrs , do you get in the logs any reports of OOM ?

**Comment by digipigeon** [comment]
Hi Bogdan,

On behalf of @syedrizwansrs. 

I thought that we did get the OOM reports, as the lock up seems to happen when the memory got low, however looking back I don't see the OOM messages in the logs. What we do see is that the UDP queue goes very high, the server stops processing and CPU load skyrockets.

I was quite sure that it was a memory issue though, as there is a noticeable continued decrease in available memory as reported by opensips stats this never recovers even when traffic is stopped, but is on continuous decline.

Since this last report I tried throwing an extra GB of memory to shared memory and it no longer crashes in the same way, but another side affect seems to have happened, this may or may not be related.

We have a timer route that emits stats every 60 seconds via rabbitmq, after a while it stops emitting. It also stops being a member of the cluster correctly.

I see a few errors in the logs:

```
ERROR:tm:_reply_light: failed to generate 200 reply when a final 200 was sent out
ERROR:tm:tm_anycast_cancel: cannot handle auto-CANCEL here - send to script!

ERROR:nathelper:fix_nated_sdp_f: Unable to get bodies from message

ERROR:proto_bin:tcpconn_async_connect: poll error: flags 1c
ERROR:proto_bin:tcpconn_async_connect: failed to retrieve SO_ERROR [server=45.63.XXX.XXX:8688] (111) Connection refused
ERROR:proto_bin:proto_bin_send: async TCP connect failed
ERROR:clusterer:msg_send: send() to 45.63.XXX.XXX:8688 for proto bin/7 failed
ERROR:clusterer:flood_message: Failed to flood message to node [2599]
ERROR:event_rabbitmq:rmq_error: closing channel: a socket error occurred
ERROR:event_rabbitmq:rmq_error: closing connection: a socket error occurred
ERROR:core:receive_msg: Unable to parse msg received from [115.59.XXX.XXX:30301]
```

We get a few warnings as follows:
```
WARNING:core:init_reactor_size: shrinking reactor size from 262144 (autodetected via rlimit) to 163840 (limited by memory of 10% from 50Mb)
WARNING:core:init_reactor_size: use 'open_files_limit' to enforce other limit or increase pkg memory
WARNING:event_rabbitmq:amqp_check_status: Socket error
WARNING:core:handle_timer_job: timer job <rl-timer> has a 70000 us delay in execution
WARNING:core:handle_timer_job: timer job <tm-timer> has a 70000 us delay in execution
WARNING:core:handle_timer_job: timer job <clstr-heartbeats-timer> has a 70000 us delay in execution
WARNING:core:handle_timer_job: timer job <blcore-expire> has a 70000 us delay in execution
WARNING:event_rabbitmq:amqp_check_status: Socket error
WARNING:event_rabbitmq:amqp_check_status: Socket error
WARNING:core:handle_timer_job: utimer job <tm-utimer> has a 70000 us delay in execution
```

Please let me know if you have any suggestions on what to try next.

**Comment by digipigeon** [comment]
I can confirm that the issue above with emitting stats is NOT with the timer route or with the rabbitmq module. The stats appear to become inaccessible via the mi interface as well.

No ERROR lines appear when doing a stats request.

**Comment by bogdan-iancu** [comment]
The investigation continued offline and proved not be a leak, but rather an excessive memory fragmentation (due the default defrag policy in F_MALLOC).
