### ISSUE TITLE
[BUG] event_rabbitmq & event_virtual

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#1836]
**OpenSIPS version you are running**

```
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 661ae58bb
main.c compiled on  with gcc 7

```

**Describe the bug**

`event_virtual` fails to provide availability when using `FAILOVER` and `sync_mode=1`

**To Reproduce**

```
opensips.cfg
modparam("event_rabbitmq", "heartbeat", 30)
modparam("event_rabbitmq", "sync_mode", 1)
```

```
startup_route {
	subscribe_event("E_LOG", "virtual:FAILOVER rabbitmq:user:pass@10.10.10.10/log rabbitmq:user:pass@10.10.10.20/log");
}
```

If server 10.10.10.10 is offline (or goes offline), OpenSIPs pretty much grinds to a halt, many timer events, stops responding to SIP packets, even SIP pings.

**Expected behavior**

The `event_virtual` modules should detect that the primary server has failed and correctly connect to the secondary server.

**Comment by rvlad-patrascu** [comment]
Hi @digipigeon

The root of the problem here was that event_rabbitmq would block indefinitely when trying to connect to an unresponsive server. A feasible solution involved both introducing a connect timeout for event_rabbitmq and improving the behavior of event_virtual to not try to notify a failed subscriber every time.
Can you confirm that this fixes you problem ? Note that you will probably have to set a much smaller value for the "connect_timeout" parameter (eg. 500 ms) than the default setting (which is 10 seconds).

**Comment by digipigeon** [comment]
I can confirm that this problem is now fixed, thank you.
