### ISSUE TITLE
Clustering presence services on 2.4

### ISSUE THREAD

**Issue by sekil75** [OpenSIPS/opensips#1848]
**OpenSIPS version you are running**

```version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9c49b09
main.c compiled on 17:20:10 Oct  5 2019 with gcc 4.8.5
```

**Describe the bug**

I have classic active-backup HA scenario (two servers, Centos 7, with pacemaker/corosync for HA/VIP failover). Clustering for usrloc works great.
I'm trying to make HA scenario for presence as well. I use a shared MySQL db both servers can write and read to/from. Now, an active server picks up SUBSCRIBEs and PUBLISHes from UAs, puts that data in its memory and also writes them to db. Active server has vip tag set to 'active' and backup server to 'backup'. 
If for some reason I need to reload backup server (changes in cfg etc), it will pick up pres data from shared DB and act upon it even though it's not active one. It will load pres data in its memory and upon upcoming aging of that data (re-SUBSCRIBE period which should occur) it will try to send 408 (it won't though since the VIP address is not active on it), but will effectively end those subscriptions and delete them from DB. This doesn't prohibit and interfere with presence operation on active server, since it's all in memory but:
 Active server can't do anything anymore to write new real re-SUBSCRIBE data to DB, since they don't exist in it (it mostly only needs to change version, but the subscription is not there, it cannot UPDATE the row which is not there anymore).
My question is therefore, how can I make backup server not to mess with the DB at all when it should not? I guess whole purpose of backup server is not to do this (create DB issues on which this setup depends).

These parameters are what I use:

modparam("presence", "fallback2db", 1)
modparam("presence", "cluster_id", 1)
modparam("presence", "cluster_sharing_tags", "vip=active") 

Now this param when set (end_sub_on_timeout) to 0, will not delete the subs from DB, but this also means real SUBSCRIBEs which have aged out will be there indefinitely, so this is not a proper solution.

**Comment by gmaruzz** [comment]
I have also found same problem, and maybe some additional ones, in 3.0 (nightly)

You can reproduce this way:

have dialoginfo working

then have some calls up

while calls are up, failover the servers (A/B)

entries in presentity table, and in pua table, stay there forever, and the "old" active opensips will continue to try to act on them (and will fail because has no more the VIP address)

**Comment by gmaruzz** [comment]
14:54:11) sekil: gmaruzz: this is basically same behaviour I'm seeing
(14:55:00) gmaruzz: is actually a pity
(14:55:03) gmaruzz: :))
(14:55:28) sekil: gmaruzz: I haven't found a way to solve this since 2.3
(14:55:31) gmaruzz: failover, with rtpengine and redis, is able to shift the live calls without a hitch
(14:56:04) gmaruzz: I am trying to understanmd...
(14:56:06) sekil: gmaruzz: but you can't use redis with presence can you?
(14:56:15) gmaruzz: nope
(14:56:21) gmaruzz: redis for rtpengine
(14:56:29) sekil: gmaruzz: right
(14:56:36) gmaruzz: my suspect is:
(14:56:53) gmaruzz: the old opensips write the presentity
(14:57:06) gmaruzz: the new opensips do not delete the presentity
(14:57:12) gmaruzz: when the call is over

**Comment by gmaruzz** [comment]
(14:59:19) gmaruzz: maybe we can avoid writing in the db altogheter
(14:59:30) gmaruzz: because anyway there is clustering...
(14:59:37) gmaruzz: no need for db backing
(15:00:25) sekil: gmaruzz: hmm...afaik..presence data is not clustered...but has to use shared db
(15:01:04) gmaruzz: in 3.0 presence is clustered
(15:01:42) gmaruzz: not sure about its data...
(15:01:46) sekil: gmaruzz: you mean presence data is sent through cluster engine
(15:01:47) sekil: ?
(15:02:05) gmaruzz: not sure... I was thinking that...
(15:02:28) sekil: gmaruzz: I don't think so
(15:02:51) sekil: gmaruzz: https://opensips.org/html/docs/modules/3.0.x/presence.html#presence_clustering
(15:02:58) sekil: gmaruzz: this is the same thing as 2.4
(15:03:14) gmaruzz: naaaa, that is changed
(15:03:20) gmaruzz: lazy docs :D
(15:03:22) gmaruzz: moment
(15:03:26) sekil: gmaruzz: subs and publs are sent to memory then goes to db
(15:03:36) sekil: gmaruzz: in 2.4
(15:04:07) gmaruzz: maybe you right...
(15:04:28) gmaruzz: but... I see the presentity from the other opensips
(15:04:58) gmaruzz: I was thinking is bninary streamed by ckusterer module
(15:05:15) sekil: gmaruzz: https://blog.opensips.org/2019/03/07/achieving-service-redundancy-in-two-steps-with-unified-clustering-in-opensips-3-0/
(15:05:16) gmaruzz: and db is just a backup if both A/B are down
(15:05:26) sekil: gmaruzz: this mentions db as well
(15:06:25) gmaruzz: I even have no fallback_db 
(15:06:39) sekil: gmaruzz: which means it will use memory only
(15:06:49) gmaruzz: that I would like
(15:06:56) gmaruzz: but is written to db anyweay
(15:07:47) sekil: gmaruzz: fallback2db is needed for backup to load subs/publs to its memory
(15:09:07) gmaruzz: anyway, I just checked: after a while, the opensips that writes the presentities in the db, delete them from db
(15:09:19) gmaruzz: if you failover, presentities stay forever
(15:09:41) sekil: gmaruzz: and also if you have failover...old server will continue working on subs/publs
(15:09:48) sekil: gmaruzz: which is not what I want
(15:09:53) gmaruzz: exact
(15:10:00) sekil: gmaruzz: it will expire those data from db
(15:10:19) sekil: gmaruzz: and new active won't be writing new re-SUBs
(15:10:25) sekil: gmaruzz: so this is wrong
(15:10:36) gmaruzz: in my case (3.0) it try to do things with socket VIP and fails
(15:10:47) gmaruzz: never delete from DB

**Comment by sekil75** [comment]
Can anybody comment on this?
Is this a bug or my misunderstanding?
Regards,

**Comment by bogdan-iancu** [comment]
@gmaruzz , I think you experience a different issue that @sekil75 . What @gmaruzz reports is the same as #1869 and is about data replication.
On the other hand, what @sekil75 reports is conflict upon which server is `active` on the presence data.

So, @sekil75, after you restart the backup server, what is the status of the presence sharing tag on backup ?

**Comment by sekil75** [comment]
After I restart backup, sharing tag is set to 'backup', because this is how it's hardcoded in the opensips.cfg. So there's no situation where backup supposedly takes over presence functions on active.

**Comment by bogdan-iancu** [comment]
OK, so the backup server restarts as "backup" for the tag, but it starts managing the subscriptions (as it would be active) ?

**Comment by sekil75** [comment]
After restart, backup server loads subs from db to its memory and even though it don't have VIP set to it...or is 'promoted' to active it starts to handle subscriptions (what it will do is try to send SIP messages to the phones involved ...and fail because of VIP non-configured to the box) but it will also 'eat' all the db stuff and expire those subscriptions making for active not able to act upon them anymore in the db.

**Comment by bogdan-iancu** [comment]
In the DB accessible for the backup server, do you see the right tag in the `sharing_tag` column of `active_watchers` table ? Just to be sure the backup loads and attaches the right tag to the loaded subscriptions

**Comment by sekil75** [comment]
Yes, I add the tag "vip" to all the subscribes:
 handle_subscribe("1","vip");
It's there also on the db, on sharing_tag field.

**Comment by bogdan-iancu** [comment]
@sekil75, I added some small patch to expose during `subs_phtable_list` MI command the `sharing_tag` of the subscription also.

So, after the backup restart check : 
1) the status of the sharing tag `opensipsctl fifo pres_list_sharing_tags`
2) the sharing tag of the presentities via `opensipsctl fifo subs_phtable_list`

**Comment by sekil75** [comment]
1) Tag:: vip State=0
2) sharing_tag=vip

**Comment by bogdan-iancu** [comment]
So, before and after the restart of backup, on backup:
1) the sharing tag value/state is the same
2) the subscriptions have the same tag attached

Right ? or do you see a difference somewhere ?

**Comment by sekil75** [comment]
1) Correct
2) Correct, but have just now expired because backup handled them:

Nov  8 11:29:59 db1 /usr/local/sbin/opensips[22436]: CRITICAL:core:proto_udp_send: invalid sendtoparameters#012one possible reason is the server is bound to localhost and#012attempts to send to the net
Nov  8 11:29:59 db1 /usr/local/sbin/opensips[22436]: ERROR:tm:msg_send: send() to 172.27.1.182:5060 for proto udp/1 failed
Nov  8 11:30:01 db1 /usr/local/sbin/opensips[22410]: WARNING:presence:p_tm_callback: completed with status [408] and to_tag [4995-65cf0d4b54b72b7bf6bbb42e3d0d91f4], cseq [CSeq: 568]
Nov  8 11:30:01 db1 /usr/local/sbin/opensips[22410]: WARNING:presence:p_tm_callback: completed with status [408] and to_tag [4995-19ad802e1da701d01770103f47994602], cseq [CSeq: 613]
^C
 
mysql> select * from active_watchers;
Empty set (0.00 sec)

**Comment by bogdan-iancu** [comment]
OK, the errors you see are form presence trying to sent a `NOTIFY` within a subscription. You say the `NOTIFY` is triggered because the "watched" presentity expired and all the watchers must be notified on that (this is the `presence-wclean` timer routine in presence module) ?

**Comment by sekil75** [comment]
Yes, if I'm not mistaken, the server is not seeing re-SUBSCRIBEs because of course it's not coming to it (no VIP on it). Therefore, old subs expire, backup tries to send notifies, and deletes those subs in db.
The problem is, it's not his thing to do all this in the first place. 
One thing that mitigate this is "end_sub_on_timeout" set to 0, but that of course has implications on regular SUBSCRIBEs expiring.

**Comment by sekil75** [comment]
I wonder if backup should load data from db upon restart, therefore it will not respond to it.

**Comment by bogdan-iancu** [comment]
@sekil75 , if a subscription/watcher expires, there is no SIP NOTIFY to be sent out. The subscription is simply deleted from DB and that's it.
Only the expiring of a presentity will trigger NOTIFY'es (on the subscription watching the given presentity).

Conclusions:
* I suspect the deleting ALL expired subscription (in `timer_db_update` timer routine) may be wrong, we should delete only for the active tags
* the failing NOTIFY'es are not related to subscription expiring. Somehow there is a publishing event on the presentity, that may trigger the NOTIFY

**Comment by sekil75** [comment]
IMO, why should backup handle any db operations at all? IMO, what is needed is not to allow backup to mess with db (while being backup of course).
Is that what you mean in your first conclusion?

**Comment by bogdan-iancu** [comment]
Well, the backup (for a certain sharing tag) should not do any DB ops - that;s the idea behind point 1).
Nevertheless, the problem mentioned at 1) may not explain your reported issue.

But I can work out a fix for 1) and let see how it goes ;)

**Comment by sekil75** [comment]
Ping bot...not stale

**Comment by bogdan-iancu** [comment]
take it easy bot, we are in holiday season ;)

**Comment by bogdan-iancu** [comment]
OK, trying to recap here - during the restart of the backup, the backup may load from DB some records (presentities and watchers/subscriptions) which it didn;t had before in memory, as they were written to DB by primary.
Now, let's take it one at at time:
1) backup loads in memory a **presentity** originally written into db by primary. As the backup will not receive any further PUBLISH'es (for the presentity), it will expire it. When a presentity disappears, all its watchers must be notified, but the code sends notifies only the subscriptions with an active tag (see [this](https://github.com/OpenSIPS/opensips/blob/2.4/modules/presence/publish.c#L201) and [this](https://github.com/OpenSIPS/opensips/blob/2.4/modules/presence/publish.c#L334). So, if the `vip` tag is inactive on backup, no notifies will be sent out and the presentity will be silently be discarded.
2) backup loads in memory a **watcher/subscriptions** originally written into db by primary. When the subscription expires (as no re-SUBSCRIBE is received by backup) ( see [this](https://github.com/OpenSIPS/opensips/blob/2.4/modules/presence/subscribe.c#L1306) and [this](https://github.com/OpenSIPS/opensips/blob/2.4/modules/presence/subscribe.c#L1324)), some callback will be called (see [this](https://github.com/OpenSIPS/opensips/blob/2.4/modules/presence/subscribe.c#L1508) which is defined [here](https://github.com/OpenSIPS/opensips/blob/2.4/modules/presence/subscribe.c#L1284) - and this callback sends a notify, depending on the event definition; and the `presence` event has this `mandatory_timeout_notification` set .....so a NOTIFY will be sent out, without checking the shtag status. So, we found the source of the culprit notify :D .

Let me work out a fix for this, so you can run a test and confirm!

**Comment by sekil75** [comment]
The consequence of 2) is that all the db "saved" subscriptions are expired hence new subscribe coming to primary are not handled/UPDATEd in the db.
Thanks, 1) and 2) are just what the resume of issues is.

**Comment by bogdan-iancu** [comment]
@sekil75, please see my above commit that should be the problem you reported. I have to say that the patch is highly untested, so please help with this and let me know if it does the trick or not (so I can do the backport).

**Comment by sekil75** [comment]
Thank you. Presence works just fine now.

**Comment by bhanukarumudi** [comment]
@sekil75 , Do you have cluster federation enabled in your configurations?.
Because I am seeing the exact same issue, that backup node is deleting the subscription though its not the owner even with this fix, when cluster federation is enabled.

**Comment by sekil75** [comment]
@bhanukarumudi , no I don't have federation enabled. With this fix, I don't see backup node doing anything with MySQL on restart anymore.
