### ISSUE TITLE
[Question] How to route bogus BYE with missing Totag?

### ISSUE THREAD

**Issue by ryanembregts** [OpenSIPS/opensips#1866]
**OpenSIPS version you are running**
```
root@home:~# opensips -V
version: opensips 2.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```
**Describe the bug**

I see opensips does not relay BYE towards destination when 200 ok, gets overlaped with Cancel. Please, check below picture.

![outbound](https://user-images.githubusercontent.com/50750796/67126196-f461eb80-f20f-11e9-845c-182681a67ac9.PNG)

I see no issue in BYE, it contains proper `Route` header. Also, strangely i don't see any error in opensips while dropping this. 

My in-dialog route.
```
        if (has_totag()) {
                if ( is_method("ACK") && t_check_trans() ) {
                        t_relay();
                        exit;
                }
                if ( !loose_route() ) {
                        send_reply("404","Not here");
                        exit;
                }
                route(RELAY);
                exit;
        }
```

It works fine for other calls but in above scenario it behaves abnormally. 
**To Reproduce**

1. Start OpenSIPS with dialog module
2. Cancel the call while media servers answered the call. 

Thanks for the awesome work. 

Ryan.

**Comment by ryanembregts** [comment]
Silly, i could not spot the bogus BYE sent by the sonus uac with missing totag. What would be the best way to handle this? using `fix_route_dialog()` function ?

Thanks again.

**Comment by razvancrainea** [comment]
If the BYE message does not have a `to_tag`, it will not go through your big `if` in the snippet, therefore there won't be any `loose_route()` called for it. So probably your `BYE` message gets dropped somewhere else in the script. Please attach some debugging logs for processing that message for further details.

Unfortunately `fix_route_dialog()` will not work either, because that function is called on a matched dialog. But since you're missing the `to_tag`, the request can't be matched against a dialog. Moreover, that `BYE` message is built against RFC 3261, which states in [Section 15.1.2](https://tools.ietf.org/html/rfc3261#section-15.1.2):

> This rule means that a BYE sent without tags by a UAC will be rejected.  This is a change from RFC 2543, which allowed BYE without tags.

The best you can do is to run `loose_route()` on that `BYE` and treat the Route header as a pre-loaded route, that will get delivered to the UAS. But note that BYE will not match the dialog, so you can't fetch any dialog information for it, you'll only be able to relay it down to the UAS>
