### ISSUE TITLE
[BUG] rtpproxy module rewriting SDP incorrectly on re-INVITE

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1881]
**OpenSIPS version you are running**
2.4.6, 3.0.1-1 both from apt.opensips.org repository for Bionic.

**Describe the bug**
When Opensips is configured to support both IPv4 and IPv6, and IPv4 and IPv6 addresses are set explicitly for rtpproxy_offer and rtpproxy_answer, SDP origin field is re-written badly leaving "IP6" followed by an IPv4 address, for example;
```
o=........... IN IP6 10.47.16.5
```

**To Reproduce**
Have Opensips configured to bridge IPv4/IPv6 networks with rtpproxy in bridge mode for media and explicitly set the addresses in rtpproxy_offer/rtpproxy_answer.

If we start a call between two UACs on IPv6 networks (Alice and Bob) SDP is rewritten correctly with the RTPProxy IPv6 address.

If Alice switches bearer from IPv6 to IPv4 and sends a REGISTER and re-INVITE, rtpproxy_offer with "forced" on, will re-write the origin field o= to an IPv4 address for the rtpproxy, but it's keeping the "IP6" part and thus the line is invalid;

**Expected behavior**
If origin field is re-written to IPv4 address, addrtype should also be re-written to "IP" and vice versa.

**OS/environment information**
 - Ubuntu 18.04 (Docker)
 - apt.opensips.org bionic

**Comment by razvancrainea** [comment]
I believe the problem is that RTPProxy is returning an IPv6 address for your request, but you are overwriting it with an IPv4, that's why you get this problem. If that's the case, even if you do manage to get a right SDP, RTPproxy will not work correctly, simply because it will receive traffic on a different socket than it is supposed to.

If that's not the case, could you attach the communication trace and logs between OpenSIPS and RTPProxy?

**Comment by hamid-elaosta** [comment]
I'm not quite sure then how this is supposed to work. If a client switches address family, and does a re-INVITE, should Opensips not inform RTPProxy of the new address and address family?

Obviously, if a client switches address, it will continue sending to RTPProxy on the same endpoint, and RTPProxy will receive traffic from a different source and presumably update the source address.

If the address family changes, the client is no longer able to send to RTPProxy on the IPv6 address it had originally but now needs to send to the IPv4 address. The SDP is updated to notify the client of this, but how is RTPProxy notified that this has happened and the session needs updating?

**Comment by razvancrainea** [comment]
For every INVITE/re-INVITE, OpenSIPS sends to RTPProxy a command saying what IP and address family that client is going to send RTP from. Based on that info, RTPProxy creates a "listener". Whenever that changes, OpenSIPS will inform RTPProxy about the changes.
So you are absolutely right, this does already happen in your scenario.

However, when OpenSIPS sends a request, besides the client's IP and port, it should also need to tell RTPProxy what listener it should use for the other leg. That's what you do with the `e` and `i` flags.

So if your client receives an IPv4 request, and you want to bridge it to IPv6, you have to inform RTPProxy about the bridging by using the `e` or `i` flags, depending on your setup. If for example RTPProxy believes that it needs to use an IPv6 socket for outgoing, but you overwrite the address selected by RTPProxy with an IPv4 one, that will obviously not work. That's why it is important to choose the right "direction" in RTPProxy, and based on that, you will also get the proper address family.

The forced address that OpenSIPS uses to overwrite RTPProxy's response only makes sense as an "advertised" address, to solve NAT problems (such as port forwarding). But you can't change the interface/IP RTPProxy is using to communicate, nor the address of the family.

**Comment by hamid-elaosta** [comment]
Thanks for the explanation @razvancrainea.

So I'm confident that the "direction" is configured correctly; My setup allows my to makes calls IPv4 to IPv6, IPv6 to IPv4, IPv4 to IPv4 and IPv6 to IPv6. That is, I have offers and answers for "ii", "ie, "ei", "ee".

If I understand your last paragraph correctly, you're telling me that I cannot tell RTPProxy that one of the endpoints for the current session has changed IP family by moving from "external" to "internal" or vice versa?

If Alice is sending media to RTPProxy on the "external" IPv6 address, and Alice arrives at the office and connects to WiFi and thus changes to the "internal" IPv4 network, she will lose her call, and I cannot indicate to RTPProxy that Alice has moved?

How am I supposed to solve this problem then?

**Comment by razvancrainea** [comment]
@hamid-elaosta, no, you can tell RTPProxy to do bridging between IPv4, that's just fine. And you can update that on an ongoing call (I guess, I've never tried that, but it should work).

What I am saying you should not use the forced address in OpenSIPS. Unless RTPProxy is behind a NAT and you should advertise different IP(s) for its listener(s). And if RTPProxy is behind NAT, you can still do that, but you have to make sure that if RTPProxy returns an IPv4 private address, you will overwrite the IP with an IPv4 public address, and *not* an IPv6 one, or the other way around.

**Comment by hamid-elaosta** [comment]
@razvancrainea Thanks for explaining. I had tried not forcing the address but that didn't appear to work.
How do I check in Opensips whether RTPProxy returned an IPv4 address or an IPv6 one? My RTPProxy will sit behind NAT so it's necessary to re-write the address.

**Comment by razvancrainea** [comment]
You can't check in OpenSIPS what type of IP RTPProxy returns, but you should be able to "know" based on the flags you pass to RTPProxy.

**Comment by hamid-elaosta** [comment]
Thanks. I did some further checking, my flags in Opensips are correct, however, RTPProxy is returning the IPv6 address and IPv6 family even when I send it IPv4 flags. Is there something else in the command from Opensips that indicates to RTPProxy which IP it should return? I guess this could be an RTPProxy bug now but I guess it's not an Opensips one.

Feel free to close this and I'll look into other options.

**Comment by hamid-elaosta** [comment]
@razvancrainea I've re-written my Opensips configuration from scratch and attempted to resolve this issue again with Opensips 3.0.1.

If my caller switches from IPv4 to IPv6 (thus switching the call from a non-bridged to bridged in RTPProxy, RTPProxy does not return an IPv6 address when this switch happens. I'm not sure if that's due to the information in the command from Opensips or whether RTPProxy just refuses to do this.

Can you offer any assistance with figuring out the issue?

**Comment by razvancrainea** [comment]
My assumption is that the flags you are sending to RTPProxy are not entirely correct.
Could you tell us how you configured RTPProxy listening sockets (`-l` parameter)?

**Comment by hamid-elaosta** [comment]
rtpproxy is configured -l ipv4-address/

**Comment by razvancrainea** [comment]
If that's the setup, try setting the `iee` flags for IPv4 to IPv6 bridging and `eii` for IPv6 to IPv4.

**Comment by hamid-elaosta** [comment]
@razvancrainea Thanks. I understand that `ee` and `ii` are used for 4-4 and 6-6, but what does `eii` and `iee` mean?

**Comment by razvancrainea** [comment]
Its used to specify the transition between external and internal (`eii`) and internal and external (`iee`).

**Comment by hamid-elaosta** [comment]
Thanks again. Is there any reading material on this? I found any authoritative source at all on how this works to be absent.

**Comment by razvancrainea** [comment]
TBH, I didn't find any either, I just read the code and figured out how to configure it.
