### ISSUE TITLE
[BUG] uac_redirect reuses the original branch for the first contact of a redirect, but all others get new branches

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#1887]
**OpenSIPS version you are running**
```
3.0
```

**Describe the bug**

In uac_redirect, shmcontact2dset(), called from get_redirects(), the first contact of the redirect is not appended as a new branch, it instead reuses the original branch which causes it to inherit information from this branch such as route set of the request, if there was one present.  

https://github.com/OpenSIPS/opensips/blob/3.0/modules/uac_redirect/rd_funcs.c#L250

**Steps to reproduce**

In the case of a non-adjacent registrar sending a request to a UAS, upon performing a location lookup that includes a path header of the proxy to traverse to reach the UAS, the initial branch has a route set.

e.g.  UAC -> uac proxy -> registrar (lookup())-> uas proxy -> UAS

If the UAS sends a 302 Redirect in response to this request, it is passed back to the registrar and the first branch will be reused for the highest ranked contact in the redirect, and the routeset injected into the request that is formed as a result of handling the redirect.  This forces the request back to the UAS proxy which may have no ability to process the request as it may only be able to handle requests for user agents it is responsible for.

**Expected behavior**
Each contact from a redirected request should be appended as a new branch which does not inherit from the initial branch.

**Comment by bogdan-iancu** [comment]
Woow, this is a complex one - thanks for the detailed report and explanations @etamme  !

And indeed, the problem is the `path_vec` within the `sip_msg`, which is inherited by the first destination, but not by the next ones (which are created as branches).

A fix will to be reset all the other branch properties (Q, flags, path, socket, etc) when re-using the msg as first destination (here -> https://github.com/OpenSIPS/opensips/blob/3.0/modules/uac_redirect/rd_funcs.c#L256).

Also, I'm wondering if TM shouldn't do that when triggering failure route - like how much data should be inherited from the previous failed destination.

**Comment by bogdan-iancu** [comment]
naughty bot....

**Comment by bogdan-iancu** [comment]
Hi @etamme ,
I put some time into reviewing this issue.
Let me start from mentioning the list of the the so called "per branch" info:
* request URI (ruri)
* destination URI (duri)
* PATH vector
* Q value
* branch flags (bflags)
* socket info ($fs)

 In my opinion, the the big question is what branch information should be exposed when the failure route is triggered ? Should we expose all info related to a certain branch (like the winning branch) or should we provide no per-branch info (like being branch neutral) ?

IMHO, the second will make all the sens in the world - the failure route is a basically a continuation of the request route, after all your attempts/branches failed, so you can create new branches, in a similar way as you did in request route. BUT the biggest problem with this approach is the fact that there is no clear delimitation between per-branch or per-message data when comes to the first branch (mapping on RURI) - the info for the first branch (mandatory branch) is set directly into the `sip_msg` structure, making it hard to distinguishes between what is per-message setting or what is per-first-branch setting. Not sure if I manage to clearly describe the my dilemma here :).

Of course, beside a global fix for the issue, we can do specific fix only for the redirect case and have the code automatically resetting all the per-branch fields when adding the first destination (instead of expecting the TM & failure route to do it for us automatically)

**Comment by bogdan-iancu** [comment]
Short description of the fix. For the existing releases (2.4 and 3.0), the fix is to reset the PATH vector and Q value while entering the failure route - these two values are 100% per-branch values/attributes and they should not be inherited (during serial forking in failure route) by any further branch.
This partial fix was considered to avoid breaking the backward compatibility with the existing releases from the 2.4 and 3.0 families.

For 3.1/dev, the fix will be more aggressive, in the way that *all* the per-branch attributes (including the remaining Forced-Send-Socket and Branch-Flags) are to be reset while entering the failure route. The idea is to avoid any kind of bogus inheriting from the old/previous branches, giving you a clean environment for creating new branches.
