### ISSUE TITLE
replace wouldn't work in sqlite3

### ISSUE THREAD

**Issue by wengzuyang** [OpenSIPS/opensips#1904]
the sql syntax in sqlite3 is "replace into ...",but "replace ..." in fuction "db_do_replace";
![image](https://user-images.githubusercontent.com/11473283/69525423-0bc88d00-0fa3-11ea-8906-3dca326a6c39.png)

**Comment by bogdan-iancu** [comment]
Yeah, indeed, according to https://www.sqlitetutorial.net/sqlite-replace-statement/ it should be an `INTO` over there.
The problem is that the `db_do_replace()` is a common SQL function in OpenSIPS, shared by all the SQL backends for building "replace" statements. So we cannot change in there, as we will break all the other backends. I would say SQLITE is not SQL compliant (or at least not in line with majority of other SQL engines) when comes to the syntax of the "replace" cmd.

**Comment by bogdan-iancu** [comment]
After some more digging, I think the proper way to build a "REPLACE..." SQL statement is with ".. INTO..." - mysql supports that, sqlite also.
Checking what OpenSIPS DB modules provide a REPLACE function (besides mysql and sqlite), we have 'db_http` which does not use the `db_do_replace()` function and `db_unixodbc` and `db_virtual` which are proxying / interfacing to other db backends.

So, let's have this change on trunk for now and see if there are any side effects.
