### ISSUE TITLE
[FEATURE] New return code from mid_registrar_save for successful registration 

### ISSUE THREAD

**Issue by bshirazi** [OpenSIPS/opensips#1913]
Hi
Imagine one opensips in front of many freeswitches. 
ALL freeswitches are acting as registrar and provisioned by same user/pass for sipphones.
Register messages randomly goes to one of freeswitches.
I do NOT want to replicate internal db of freeswicthes but want to all freeswitches have register contact information of all registered phones so I want to : after successful registration in one of freeswitches then from opensips clone/t_replicate/t_uac_dlg Register message to all remaining freeswitches, so I need a new return code( or a function parameter) from mid_registrar_save telling me that register messages sent to registrar and answer was 2xx.

Thank you.
M.Shirazi

**Comment by bshirazi** [comment]
Hi
I used two times mid_register-save, after one second sleeping:

sleep(1);
	mid_registrar_save("location","r"); # second times
	if($retcode==2)
		t_replicate("sip:10.105.80.4:5060");
this works just there is some errors in logs like Invalid cseg for aor<1000>...
is there any solutions ?

Regards
Shirazi

**Comment by bshirazi** [comment]
Hi
Another way to do this is we can call mid_registrar_lookup after mid_register_save (after some sleep) to realize the register message just sent to registrar was successful or not. It seems current mid_registrar_lookup can not process register.

Regards
M.Shirazi

**Comment by liviuchircu** [comment]
What you are trying to do is currently out of the scope of mid-registrar.  The main concept behind `mid_registrar_save()` is that is performs *no signaling* and *does not save anything yet into `location`*.  It just prepares a series of callbacks (e.g. awaiting a reply from downstream), and only then, on success, it will commit the data to the `location` table.  Additionally, it will keep track of the upstream UAC, such that if its battery dies or loses WiFi, it will automatically De-REGISTER it towards FreeSWITCH.

The concept of mid-registering to *N* downstream elements instead of *1* would require a significant rework of the module and we've not seen a high demand for this feature at all.

With what is available right now, you are not able to use `mid-registrar` for your purpose.  Maybe just stick with `registrar`, and `t_replicate()` in a loop to all your FreeSWITCHes and be generally less stateful than with a `mid-registrar`.  It could definitely work.

**Comment by bshirazi** [comment]
Hi @liviuchircu 
Thank you for your explanation.
Please let think the work around I mentioned above for replicating Register to N downstream servers is OK(using mid_registrar_save for second time after one second sleep, it worked for me).
For De-REGISTERing part:
You already implemented my other feature request about Variable route name route[$var(Myroute)] [https://github.com/OpenSIPS/opensips/issues/1934](url)
If we have optional custom Route, called when Opensips sends De-REGISTER signals it has 2 benefits: 
1- We can put credentials needs to authenticate Opensips in registrar in this custom Route so no need to whitelist opensips IP in registrar as you mentioned here:[https://www.opensips.org/Documentation/Tutorials-MidRegistrar](url) 
2-I can put my custom replicating  De-REGISTER signals to all N downstream servers.

Regards
Shirazi

**Comment by liviuchircu** [comment]
> Please let think the work around I mentioned above for replicating Register to N downstream servers is OK(using mid_registrar_save for second time after one second sleep, it worked for me).

That worked because you had a free SIP worker to handle the 200 OK reply and save the contact into mid-registrar while the INVITE worker was stuck in `sleep()` after you did `t_relay()`.  But the mid-registrar is meant to process hundreds (thousands?) of registrations per second!  What if all workers are **each** processing one REGISTER?  It would only take 10-20 concurrent REGISTERs to block your entire OpenSIPS, and your 2nd `mid_registrar_save()` would fail.  Your approach may have worked for your use case, but we do not encourage it or recommend it as a best practice.

> optional custom Route, called when Opensips sends De-REGISTER signals

I believe you can catch them already using the [`local_route`](https://www.opensips.org/Documentation/Script-Routes-3-1#toc6), then you can both do [`append_hf()`](https://opensips.org/docs/modules/3.1.x/sipmsgops.html#func_append_hf) with some custom, "X-NoAuth" header, and also do your `t_replicate()` magic from there onwards.  Let me know if this worked for you, I'm quite curious! :)

**Comment by bshirazi** [comment]
Hi @liviuchircu 
For De-Registering part local_route can help.
For avoiding using sleep work around for realizing successful registration may this works:
when on success, mid_registrar_save() wants to commit data to location table it also calls an optional costume route introduced by modparam:
modparam("mid_registrar", "Success_Register_extra_works", "MyCustomeRoute")
in this case may be we need to use t_uac_dlg REGISTER in MyCustomeRoute instead of t_replicate.

Regards
M.Shirazi
