### ISSUE TITLE
[BUG] HP_MALLOC ever increasing memory usage under 2.4.8

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#2180]
After updating to 2.4.8 while using HP_MALLOC we are showing ever increasing memory usage, not present under F_MALLOC.

![Opensips_memory_usage](https://user-images.githubusercontent.com/197956/88079013-fad01b80-cb31-11ea-803b-0666cbcac724.png)

On Friday July 10 we initially put 2.4.8 into use before reverting mid day and opening issue #2168. After the fix was made available we put 2.4.8 (w/hp_malloc) back into use the following Tuesday. On both of these days you can see memory usage on the system shot up.

After Tuesday we switched to 2.4.8 with f_malloc and you can see the memory usage returned to normal.

The increased memory usage was mirrored in the OpenSIPS memory statistics (shm real_used_size, used_size).

Under 2.4.8 and hp_malloc we did eventually get a crash but I can't tell if it was related to memory issues. Log line (no other i informative logs around it):
2020-07-14T17:58:13.155688-07:00 proxy1 /usr/sbin/opensips[235510]: CRITICAL:dialog:_unref_dlg: bogus ref -1 with cnt 1 for dlg 0x7f643775da68 [15607:699419588] with clid '(removed)' and tags 'as3fa13fec' 'NULL'

I also noticed that CPU usage appeared higher under hp_malloc on 2.4.8 vs previous versions, though not as drastic a difference as the increase in memory usage.

![Opensips_cpu_usage](https://user-images.githubusercontent.com/197956/88079021-fdcb0c00-cb31-11ea-8863-fb56f7e77f5b.png)

This is on CentOS 8.

**Comment by liviuchircu** [comment]
Hey, @rrb3942!  I expect commit 3803441bb to definitely increase CPU usage for `HP_MALLOC` due to the fragment coalescing logic, but at least this fixed the algorithm so it won't fragment your SHM pool gradually until it runs out of memory (the original problem)!  To put it simply: the pre-2.4.8 HP_MALLOC was so optimized/over-simplified... that it was not correct anymore, and it caused lots of issues because of memory fragmentation!

Thank you for the graphs, could you also disclose how much shared memory (`-m` switch) you are providing to OpenSIPS, how many cores are available on your system, as well as how much CPS you are planning to push through it?  Thank you!

**Comment by rrb3942** [comment]
We are using -m 5120 for the shared memory. It stayed within this until that random crash (haven't seen it crash again since going to f_malloc).

System is 8 cores and we push 300-600 cps through it.

**Comment by liviuchircu** [comment]
OK, and for the PGK memory?  (`-M` switch).  It looks like you are over-provisioning shared memory, which is allocated all at once (all OpenSIPS allocators do so), but each allocator will "touch" the pool in all sort of places, thus the Operating System sees it as "relinquished" or not.  My advice is to just look at the OpenSIPS statistics, because the OS memory usage will eventually stabilize.

Oh, and for 300-600 CPS: 1GB of shared memory should be enough (with tm + dialog + topo hiding).  If you want to be on the safe side, go for 2GB and retry an `HP_MALLOC` build.  I am confident that it should behave nicely, as it cannot leak memory (there are no `malloc` internal calls).  Many thanks!

**Comment by rrb3942** [comment]
@liviuchircu Thanks for the advice. I'll do some testing with lower memory limits and see how it behaves.

I will close this for now until I can do some more testing and re-open if I find anything.
