### ISSUE TITLE
[BUG] Dialog module does not rewrite 200 OK Contact on re-INVITES after fix_nated_contact

### ISSUE THREAD

**Issue by atrips** [OpenSIPS/opensips#2315]
```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: f0bd15d54
main.c compiled on  with gcc 8
```

Maybe I'm wrong but I think the issue is related to  #1625. Fix applies only on the request direction but 200 OK handling is missing.

What I'm observing is missing ACK on re-INVITE caused by wrong Contact port. fix_nated_contact is made on both initial request and response and call is established. 

P.S.
I'm not calling fix_route_dialog() as dialog is validated by validate_dialog()

**Comment by bogdan-iancu** [comment]
@atrips, please describe the full call scenario/msg flow in order to reproduce this. Also mention all the contact-related ops you may do in script for each SIP message of the call.

**Comment by atrips** [comment]
Hi @bogdan-iancu,

Simplified scenario:

- Both clients are behind NAT.
- topology is: A - OpenSIPS - B2BUA - B

A calls B:
- fix_nated_contact on both request and onreply route
- dialog create
- ...
- 200 OK from B
- ACK form A
(at this stage everything is fine)
(all subsequent messages are in dialog)
- re-INVITE from B (dialog is matched and validated)
- 200 OK from A - 200 OK. Here Contact port is not fixed by OpenSIPS. Message goes to B via B2BUA.
- ACK from B delivered via B2BUA to OpenSIPS. ACK does not reach A and A keeps to retransmit 200 OK
- ...

**Comment by liviuchircu** [comment]
Hi, folks!  As I see things, the dialog module is not expected to "fix" any Contacts from mid-dialog requests.  This is because two critical things happen during the "initial INVITE - 200 OK" phase:

1. each party has the Contact of the opposite party and can build a proper R-URI from now on, on each mid-dialog request
2. each party has the full routing set, thus it can build a request that reaches all interested proxies on its way back (record routing!)

So, in my opinion, subsequent Contact headers exchanged during mid-dialog requests are pretty much **irrelevant**.  My guess is that your B2BUA is re-learning the dialog routing set during that Re-INVITE, so maybe you should `record_route()` yourself back in, just for the sake of it, to be compliant with it.  But I am 90%+ sure that RFC 3261 doesn't mandate that you include a "Record-Route" header on each mid-dialog request, as the route set should be **locked in**, rather than being **dynamic**.

[Here is an example](https://chunk.io/liviuc/f9ee36fe616041128bb0eeef3b1334e0) "sipp <-> OpenSIPS <-> sipp" .pcap file (just rename it to foo.pcap) with a mid-dialog Re-INVITE sequence that routes perfectly, including the BYE, despite **all** mid-dialog Contact headers (caller, callee, kitchen sink, etc.) are NAT'ed and non-routable!

**Comment by liviuchircu** [comment]
Resolution:  the fix was to simply perform `fix_nated_contact()` during mid-dialog requests requests or replies, as dictated by `nat_uac_test()`.

**Comment by atrips** [comment]
@liviuchircu , many thanks and sorry on time spent here.
