### ISSUE TITLE
stale[bot] is a bit aggressive while closing tickets

### ISSUE THREAD

**Issue by lemenkov** [OpenSIPS/opensips#2352]
I believe if a PR is still mergeable it shouldn't scare people with treats to close it down. Warn yes but close mergeable PR - certainly not.

Also look at the issue #2273 which linked to the PR #2316 where stale[bot] issued just warning. I would expect an action synchronization here - e.g. issuing warnings (and maybe closing) simultaneously. On the contrate issue #2273 was closed while PR #2316 was received just a warning.

**Comment by liviuchircu** [comment]
Hi, @lemenkov!  If you look at the stale bot [configuration file](https://github.com/OpenSIPS/opensips/blob/master/.github/stale.yml), there are some **labels** we can use in order to shut it up, i.e.:

  - fixed
  - improvement
  - low-priority
  - high-priority
  - feature request

In your case, I flagged your WIP with **improvement**, so the bot will stop harassing you.  What do you think?

**Comment by lemenkov** [comment]
@liviuchircu yes, I think this will work. Thanks!
