### ISSUE TITLE
[FEATURE] b2b 3.2 respect $du

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#2374]
Hi the opensips team,

I have a question about b2b.
b2b_init_request("top hiding") supports $du which set before it.

shouldn't another scenarios support $du too?
now if I use string which is not equal of "top hiding", $du doesn't work.

**Comment by nikbyte** [comment]
If this is acceptable, next patch works good for me. Tested.

```
diff --git a/modules/b2b_logic/logic.c b/modules/b2b_logic/logic.c
index faff32ff7..e4e25843e 100644
--- a/modules/b2b_logic/logic.c
+++ b/modules/b2b_logic/logic.c
@@ -3172,6 +3173,7 @@ str* b2b_process_scenario_init(struct sip_msg* msg, b2bl_cback_f cbf,
        ci.to_uri        = new_entity->dest_uri;
        ci.from_uri      = from_uri;
        ci.from_dname    = from_dname;
+       ci.dst_uri       = msg->dst_uri;
        ci.extra_headers = tuple->extra_headers;
        ci.client_headers= hdrs;
        ci.body          = (body.s?&body:NULL);
```

**Comment by rvlad-patrascu** [comment]
Hi @nikbyte ,

I'm not sure this a good idea since the destination should be already set via a parameter of `b2b_client_new()`, which is required to be called before doing `b2b_init_request()`. Moreover, if we are using `b2b_client_new()` at a later point in the scenario, in the b2b_logic dedicated routes, `$du` will not be available anyway (since we are no longer in "proxy mode"). On the other hand, "top hiding" is a simpler scenario and we don't have to call `b2b_client_new()` anyway.

Let me know if I'm missing something and you have a different requirement.

**Comment by nikbyte** [comment]
For me this is a use case. I need to have in ruri domain and pass the invite into local IP. This helps.

**Comment by nikbyte** [comment]
btw, every b2b can do this. it's called `proxy` there.

**Comment by rvlad-patrascu** [comment]
Ok, you have a point. But I still think the best approach would be for example to have an extra "outbound proxy" parameter to `b2b_client_new()` instead of using `$du`. And this is for the same reason I stated above, to be able to similarly do this in the b2b_logic dedicated routes. I would discourage using `$du` in those routes since most routing operations you'd normally do in a standard request route are not available (due to the fact that the b2b_logic/b2b_entities modules still handle and control the traffic and logic, even though script functions instead of old-style XML scripting).

**Comment by nikbyte** [comment]
Hm, I think this can be good, but maybe as a parameter to function.
on complex scenario you may want few proxies. or using dispatcher for it (as I do).

**Comment by rvlad-patrascu** [comment]
Yes, I was referring to a parameter to the function `b2b_client_new` as alternative to relying on setting `$du` directly. If you want to use dispatcher, just note that the messages sent to a b2b entity are newly generated by opensips and is not enough to alter the received message.

**Comment by nikbyte** [comment]
This is ok if I will call dispatcher before b2b_client_new when make a b2b client. Must work well.

**Comment by nikbyte** [comment]
Thank you. I'll test and report.

**Comment by nikbyte** [comment]
Vlad, thank you. Your patch is perfect, however I suggest to delete $du code from "top hiding" scenario. because this code conflict with this new proxy function.

**Comment by nikbyte** [comment]
I mean line `ci.dst_uri       = msg->dst_uri;` in `create_top_hiding_entities()`

**Comment by rvlad-patrascu** [comment]
@nikbyte I don't think this is necessary because for the "top hiding" scenario, the `b2b_client_new()` function is not required and calling it has no effect anyway (the required entities are created automatically). So in this case, using `$du` remains a valid option.

**Comment by nikbyte** [comment]
ok, I've got you. Thank you for the comment.

**Comment by Anjana2463** [comment]
Hi rvlad-patrascu.

I am trying to initiate a new B2B session on topology hiding scenario. In that b2b logic is unable to create its client end.Because  of that invite request is not going to destination.

can you please find what can be the issue...!?

Thanks in advance.

**Comment by Anjana2463** [comment]
I have checked all above provided solutions, still request is not reaching to destination end.
