### ISSUE TITLE
topology_hiding, two proxies in a row with same th_callid_prefix gives junk Call-ID on reply relay of second

### ISSUE THREAD

**Issue by jpyle490** [OpenSIPS/opensips#2395]
I'm running OpenSIPS on Debian 10 installed from the 3.1-nightly repo.
```version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: abe7ab7c7
main.c compiled on  with gcc 8
```

If a request, an INVITE in my case, arrives with a Call-ID that matches the pattern generated by the topology_hiding() module, things go wrong.  The most obvious issue is the Call-ID header on replies gets mangled into a mess.  Something like this from a 180 Ringing:

```
Call-ID: 4.B*>n:#.d.Cu!m9(.,
.qmq>~.4..u59<yF
```

In my case I have two OpenSIPS proxies in the call flow, both using topology_hiding(), and both with the same th_callid_prefix modparam configured.  I think that's the easiest way to duplicate it; perhaps one could use sipp for the same effect.

I've worked around the issue by changing  th_callid_prefix on one of them.

**Comment by razvancrainea** [comment]
This is more or less an expected behavior, as the [documentation](https://opensips.org/docs/modules/2.4.x/topology_hiding.html#param_th_callid_prefix) clearly specifies to make sure to use different values when chaining multiple instances. That's why I would argue this is not a bug.
As there is no way of uniquely identifying an opensips instance, the `th_callid_prefix` parameter has to be unique across all hops, otherwise you might run into these kind of confusions.

**Comment by jpyle490** [comment]
"Make sure to change this value in case your SIP path contains multiple OpenSIPS boxes with topology hiding."  Indeed!  That's on me for not checking the documentation.

Can the potential for this problem be avoided by not using ```th_callid_prefix``` on any proxy in the chain?  Does that remove the risk?

**Comment by razvancrainea** [comment]
Not at all - if you're not setting on any of the proxy chain, you will end up with all using the same thing, thus perpetuating the problem.
