### ISSUE TITLE
[FEATURE] Provide dialog id and db_id in E_DLG_STATE_CHANGED

### ISSUE THREAD

**Issue by kingsleytart** [OpenSIPS/opensips#2463]
**Is your feature request related to a problem? Please describe.**

Dialog ids are in 3 different formats depending on where they appear. In the did header, they're dot-separated hex in "did" in the Record-Route header, a single large integer in the database, and two separate integer values when passed to event_route[E_DLG_STATE_CHANGED].

**Describe the solution you'd like**
Please also include the dialog id in one of the other formats (or both?) in the parameters sent to event_route[E_DLG_STATE_CHANGED],

or (perhaps better) have a setting in the dialog module that you can set with modparam() that allows the user to select which fields they want to be sent as parameters to the event route if they want something different to the default. dialogid_hex and dialogid_bigint (or whatever you decide to call them) would then be useful fields to be able to choose. Also, please allow both of these to be sent if the user configures it. This way it would save adding more and more parameters, still be compatible with older routing scripts and allow the user flexibility to have what they need, eg

modparam("dialog", "event_route_args", "hex_dialogid|int_dialogid|otherfield1|otherfield2") etc

**Implementation**
  - Component: `dialog` module
  - Type: module's parameter
  - Name: dialog id

**Describe alternatives you've considered**

I have to assemble the id string programatically, eg to get the hex string:

$(param(1){s.dec2hex}{s.reverse}{s.tolower}) + "." + $(param(2){s.dec2hex}{s.reverse}{s.tolower});

but this feels bad practice because I haven't found any documentation that says this will always guarantee to produce the correct string.

**Additional context**

Comment from Răzvan Crainea:

I am afraid your approach is the correct one, and currently there's no 
other workaround, rather than the one you already did :(.
Last year I've reworked the did and dlg_id in a few places to have a 
more consistent value, but somehow I missed the event's one. Ideally, we 
should have only two formats: the hex one (the one in Record-Route, 
dlg_list and $DLG_did), and the db_id one (the integer in DB).
I will try to rework this in the master branch, any chance you could 
open a feature request for it?

**Comment by razvancrainea** [comment]
I agree having multiple formats is confusing, that's why in commit d883a0d72ac07353d8c84cdd4ab62265887a56b9 I tried to make the way we are referencing the dialog more uniform. Unfortunately I missed the dialog's event :(.
My proposal is to remove the `hash_entry` and `hash_id` from the event and replace them with `id` (the hex representation, which appears in most of the outputs) and `db_id` (the database identifier, which also appears in the output of `dlg_list`). Basically only these two representations are to be used.

The problem is that we can't replace these in OpenSIPS 3.1 due to backwards compatibility issues - therefore my proposal is, for 3.1, to add these two parameters to the event. This will indeed introduce some issues for those who are using a format that expects a certain number of parameters for an event, but hopefully you will figure it out asap and fix your script.

@kingsleytart will that work for you?

**Comment by kingsleytart** [comment]
Hi,

Yes that would work for me, but did you see my modparam() idea? That
way you could make the change with no backward compatability issues at
all.

-- 
Cheers,
Kingsley.

**Comment by razvancrainea** [comment]
Hi, @kingsleytart !

Yes, I did see your modparam idea, and I agree it would be better to have it done like so. However, I don't see the point of carrying the `hash_entry` and `hash_id` all the way to the master (and future) branches - I simply don't want to remove them to avoid breaking compatibility. Therefore, introducing such a flexible modparam might not worth it.
Instead, I did introduce a new modparam that is a bit different - basically you can use it to specify the format of the dialog id you shall see in the event. It has 3 possible values:

0. (default) advertise `hash_id` and `hash_entry`
1. advertise `id` and `db_id`
2. advertise all 4

Therefore, setting the new `event_id_format` in your script will provide the right format for the id. This was a bit easier to implement, then your idea of modparam, and since we're not supporting this in other branches, I think it should be enough

Let me know if you have any other concerns regarding this.

Best regards,
Răzvan

**Comment by kingsleytart** [comment]
Hi,

thanks. As long as `id` is what is in the did tag (ie the hex value) then I think that covers everything. Thanks :)

Cheers,
Kingsley.
