### ISSUE TITLE
[FEATURE] Redaction of customer sensitive data in error logs

### ISSUE THREAD

**Issue by adamoverbeeke** [OpenSIPS/opensips#2490]
**Is your feature request related to a problem? Please describe.**
The feature is related to the need to comply with industry and government regulations such as PCI, HIPPA, GDPR, etc.

**Describe the solution you'd like**
We would like a way to obscure sensitive customer data in our error logs. This could be a compiler level flag for those who do not wish to use this feature. I've made an example off of branch 2.4
Something like this: https://pastebin.ubuntu.com/p/xyBPS3vsk8/

**Implementation**
 
Core

**Describe alternatives you've considered**
I will implementation design decisions to the core team. 

**Additional context**
GIT diff of branch and 2.4
https://pastebin.ubuntu.com/p/xyBPS3vsk8/

**Comment by adamoverbeeke** [comment]
The main reason for this is that opensips is printing the entire SIP messages, phone_numbers, usernames, etc in some opensips error logs.  We've made attempts to obscure sensitive in our logging. We would like to know that an error occurred, we just don't want the sensitive data along with it.

**Comment by wdoekes** [comment]
I think you cannot place the burden on opensips for this. (My opinion, not necessarily that of the opensips owners.)

- People/countries may have different opinions on what sensitive data are. If you filter out some, it might be too much for one and too little for someone else.
- When new code gets written, "sensitive" data may re-appear in new logs because the author has no idea that you think it's sensitive.
- DEBUG logs need to be precise. If everything is sanitized, it's a _lot_ harded to debug crashes and other problems.

I think you can safely request that:

- passwords and secret keys are not written to logs
- possibly even nonces

But that is about as far as I would go in placing the burden on the application.

**What to do instead?**

Well: you're logging to a log daemon right? Fluentd? Rsyslog?

All the logging applications have filter rules to drop lines. And many (most?) have rules that allow rewriting lines: I would suggest you look into those. Using regular expressions to filter/replace data that _you_ feel is sensitive.

**Comment by adamoverbeeke** [comment]
I don't anyone is suggesting that debug logs are not helpful. The original statement was for ERROR logs that print out the entire SIP message and the main ask. If the core team can put the extra logging data in different log level that would suffice.

**Comment by bogdan-iancu** [comment]
I agree with @wdoekes , we should not consider more than passwords. The rest of them, like users, numbers, etc, are very volatile in terms of being sensitive or not (maybe the FROM username is not a user id in some deployment, but some other part of the SIP request).

**Comment by adamoverbeeke** [comment]
I think the issue is the printing of the entire message/buffer during a parsing error. Can we have an option to just not print the extra data? This could be a compile flag/define

Be well,

Adam

**Comment by bcnewlin** [comment]
I realize this ticket has long been closed, and I accept that the OpenSIPS team does not wish to implement the feature, which is their choice. I don't know whether the reasons provided here are the only basis for that decision (it may just not be a priority), but as I disagree pretty strongly with the reasons provided here I wanted to add my opinion.

1. Different entities will consider different data sensitive
I agree completely. However, not being able to solve the problem perfectly for everyone is an extremely poor reason to not attempt to solve it at all. There is a lot of data that is nearly universally considered sensitive, such as phone numbers, calling/called party names, IP addresses, etc. And in the world of data privacy, the rule of thumb is to assume data is sensitive unless it is explicitly known to be safe.

Any redaction functionality in OpenSIPS need not be a simple on/off. A sophisticated solution could have levels of redaction, just as there are levels of logging that are controllable. It could even have elements of customization around certain common types of data.

2. This can be solved outside of OpenSIPS using logging filters/regexes
This suggestion is either disingenuous or naive. It reminds me a bit of the problem of creating a regex to validate HTML. It can't be done. SIP is a complex, dynamic, variable, and extensible protocol. It is not possible to craft regexes that can reliably remove all possible sensitive information from a SIP message.

But the real problem is OpenSIPS logs themselves, which can contain large amounts of potentially sensitive data in any format. It is necessary to have the context in OpenSIPS of what data is being logged and where it came from in order to make a proper decision about whether it is sensitive or not. Otherwise, you would need to craft individual filters/regexes for every specific OpenSIPS log statement. The computational cost of running all of those against every log would bring any system to its knees. And the development cost to maintain them would be just as extreme.

3. Future development will cause changes and sensitive data may escape
This is true whether the filtering is done in OpenSIPS or externally, so it is irrelevant to the discussion. Data will change, logging will change. Compliance is a continuous, ongoing effort, not a one-time goal.

3. Debugging is harder with redacted information
Yes, it absolutely is. No argument there. Unfortunately, data privacy requirements/regulations don't care how difficult they make troubleshooting. With the current climate of increased scrutiny on data privacy and increasing legislation/regulation in this area the problem will continue to get worse, and the only realistic alternative available now is to disable all OpenSIPS logging, which makes troubleshooting impossible, not just more difficult.

If this were a black box application that people used off-the-shelf to perform some task, then I think the "not our problem" mentality could be acceptable, or more so at least. But OpenSIPS is not just an application that its users run, it is a platform on which its users build. And good platforms have to provide their users with the tools to remain compliant in their industries.
