### ISSUE TITLE
[BUG] [topology_hiding] Incorrect Contact header for REGISTER method after using topology_hiding with mid_registrar

### ISSUE THREAD

**Issue by ccppprogrammer** [OpenSIPS/opensips#2523]
**OpenSIPS version you are running**

```
# opensips -V
version: opensips 3.1.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Describe the bug**

`OpenSIPS` generates an incorrect `Contact` header  for `REGISTER` method after using `topology_hiding` with `mid_registrar`.
Everything works fine with `topology_hiding`, but without `mid_registrar`.

<details>
  <summary>User-Agent: PhonerLite 2.82</summary>

```
Before topology_hiding:
Contact: <sip:712@192.168.1.66:5060>;+sip.instance="<urn:uuid:005BFD56-7EB2-EB11-960C-D34DEA19F35D>" 
After topology_hiding without mid_registrar:
Contact: <sip:712@10.0.0.79:5080;th=SGprdEAkE1FTV2UFQUsAdnlcSloCY1VdXlNnc0BgMi0sGkhFA2NTRVRIYHxKRwJueA-->
After topology_hiding with mid_registrar:
Contact: <sip:712@10.0.0.79:5080;thinfo=VG9JbzAdIFtkYmYvYVZxWmFXa31lQWZZeUFgV2NBVBo0H3lFYE9jfWRBZ1Z5QWBXYw--><sip:2@10.0.0.79:5080;ctid=3007560126153405910>;expires=600
```
</details>

<details>
  <summary>User-Agent: MicroSIP/3.20.3</summary>

```
Before topology_hiding:
Contact: "712" <sip:712@192.168.1.66:12533;transport=TCP;ob>;reg-id=1;+sip.instance="<urn:uuid:00000000-0000-0000-00-0000d30e0000>"
After topology_hiding without mid_registrar:
Contact: <sip:712@10.0.0.79:5080;th=SGpZdEAkE1FTV2UFQUsAdnlcSloCY1VdXldkdkFKCSw6CxwHQyIRH1kyFBVLHVBKSB4RBAl8U0VUSGdrR0sIbXhcQg-->
After topology_hiding with mid_registrar:
Contact: <sip:712@10.0.0.79:5080;thinfo=VG97bzAdIFtkYmYvYVZxWmFXa31lQWZZeUViVGBgbxsiDi0HIA4hJ2k7Ez94GzJzUyc3H2pec1T2N9Y1ZqWnNCYA--><sip:712@10.0.0.79:5080;ctid=3007560126153361592>;expires=300
```
</details>

**OS/environment information**
 - Operating System: Ubuntu 20.04.2 LTS
 - OpenSIPS installation: apt.opensips.org

**Comment by liviuchircu** [comment]
Hi @ccppprogrammer and thanks for the report!  If I understand correctly, on a REGISTER, you are calling both `topology_hiding()` and `mid_registrar_save()`, correct?  Perhaps with the purpose of changing both the Call-ID and act as a registration middle-box?

**Comment by ccppprogrammer** [comment]
Hello @liviuchircu !
The main logic is
```
if (!has_totag()) {
	topology_hiding();
}
if (is_method("REGISTER")) {
	mid_registrar_save("location", "p2v");
}
```

**Comment by liviuchircu** [comment]
Indeed.  The code was never designed to work this way.  The intended use of the functions is as follows:

* on an INVITE, you use `topology_hiding()` to rewrite Contact on the way out
* on a REGISTER, you use `mid_registrar_save()` to rewrite the Contact on the way out

When calling both of these functions, it is expected (and it's a known issue) for the resulting Contact to be broken, due to the way in which the internal "lumps" changes system works.  This is possible through other combinations, such as `topology_hiding()` + `fix_nated_contact()` (see [this](https://github.com/OpenSIPS/opensips/issues/2172) ticket), or maybe others.

Closing this issue for now, as the fix will not be here any time soon, maybe only after we get rid of the entire "lumps" mechanism (OpenSIPS 4.x??).
