### ISSUE TITLE
[BUG] Mid-Registrar forwarding unregister to main registrar

### ISSUE THREAD

**Issue by ryan-netizen** [OpenSIPS/opensips#2615]
**OpenSIPS version you are running**

```
version: opensips 3.1.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 01:46:58 Jun 23 2021 with gcc 4.8.5

```

**Describe the bug**
I am using opensips mid-registrar module in `AOR throttling` mode to handle multiple registrations per user/AOR. It works fine with multiple devices on same AOR until one device sends a unregister request which opensips forwards to main registrar. This results in main registrar thinking that device has unregistered but infact only one contact/device has unregistered on that specific AOR and other are still active with opensips. 

**To Reproduce**
Mid-registrar configurations. 
```
loadmodule "mid_registrar.so"
modparam("mid_registrar", "mode", 2) /* 0 = mirror / 1 = ct / 2 = AoR */
modparam("mid_registrar", "outgoing_expires", 7200)
```
1. Start the opensips using the above mid-registrar configurations
2. Register two devices on the same AOR.
3. Send unregister from any device

**Expected behavior**
1. I think if any other device is registered with opensips on same AOR,  opensips should not forward the unregister to main registrar but should absorb it.
2. If device going to un-register is the only device registered on that AOR, then opensips should forward it to main registrar.

Thanks for awesome work. !

**Comment by cruzccl** [comment]
Hi Liviu,

This error still happens in latest 3.2 version when using module in `AoR throttling` mode. This causes main registrar losing registration quite often in environments with parallel-forking and softphones that send deregistration requests when closed.

Debugging the code, we see that logic in [trim_to_single_contact](https://github.com/OpenSIPS/opensips/blob/50d714eaa6bc3ed8446eb21e8acadebba130904f/modules/mid_registrar/save.c#L121) sends `;expires=0` in any de-REGISTER request that reaches OpenSIPS and is not absorbed by [process_contacts_by_aor logic](https://github.com/OpenSIPS/opensips/blob/50d714eaa6bc3ed8446eb21e8acadebba130904f/modules/mid_registrar/save.c#L2507), no matter if AoR has any other active registered contact:
```
	for (c = ((contact_body_t *)ct->parsed)->contacts; c;
	     c = get_next_contact(c)) {
		calc_contact_expires(msg, c->expires, &e, 1);
		if (e != 0)
			is_dereg = 0;

		LM_DBG("deleting Contact '%.*s'\n", c->len, c->name.s);
		anchor = del_lump(msg, c->name.s - msg->buf, c->len, HDR_CONTACT_T);
		if (!anchor)
			return -1;
	}
```

This logic doesn't seem to take into account if remaining contacts exist for current AoR and it only sends `;expires=outgoing_expires` in case current REGISTER has at least one contact has non-zero expires value. A regular deregistration REGISTER is always forwarded to main registrar maintaining this 0 value for expiration, no matter if AoR has any other active registered contact.

We have prevented this issue saving a flag in the event of last contact deregistration and keeping 0-value expires in `trim_to_single_contact` only in this particular case. Deregistration of non-last contacts or regular registrations gets expires set to _outgoing_expires_ value.

You can see this PoC patch in https://github.com/irontec/opensips/commit/ad06c322ab6098e66dd0c9ef83a3abc43019ae19.

We don't know if it is the right way to do it or if could lead to problems in any other scenario, but seems to prevent the problem with unregistrations.


Thank you and regards,

**Comment by cruzccl** [comment]
Hi Liviu,

We are testing proposed PoC patch in our OpenSIPS based SBC, as this issue was causing lots of problems in our environments, where multi-device and unregistrations are frequent. You can see the patch [here](https://github.com/irontec/opensips/blob/isbc/packaging/debian/patches/000-mid_registrar_fix_deregistration_handling.patch)

We will report any problem that should arise :)

Thank you and regards,

**Comment by liviuchircu** [comment]
Hi, all!  And my apologies for the long time to respond here.  Initially, I remember I couldn't reproduce the scenario (my De-REGISTERs were getting absorbed properly, with 2+ Contacts on the mid-registrar), which is why the issue went stale.  But now, looking deeper into `process_contacts_by_aor()`, I finally understood your bug and how to replicate it (it was basically just timing-related).

In short, towards the end of [`process_contacts_by_aor()` ](https://github.com/OpenSIPS/opensips/blob/50d714eaa6bc3ed8446eb21e8acadebba130904f/modules/mid_registrar/save.c#L2503), we have the _"max contacts diff"_ logic, which tries to absorb Re-REGISTERs across multiple contacts as much as possible, but _no further than that_, otherwise we risk causing "no registration" state on the backend.

But when processing a De-REGISTER which leaves at least `1` healthy contact, this _"max contacts diff"_ logic shouldn't even be considered ("Do I forward or do I absorb?"), because no matter what are the current expiration timings, you **never** want to forward that De-REGISTER.  So I will push a patch (and all the way down to `3.1`) which implements this exact logic + 1 extra corner case (proper handling for single REGISTER which de-registers 2+ contacts -- I've never actually seen such packets in real life, but w/e).

Small comment regarding your patch:  I understand the idea behind it, but the patch actually _amplifies_ the amount of REGISTER packets sent downstream, by converting De-REGISTERs with `;expires=0` which should be absorbed into REGISTERs with `;expires=600`, for example.  And while it solves the problem, I think it is suboptimal -- please let me know if you see things differently!

Thank you again for your patience!

**Comment by cruzccl** [comment]
Hi Liviu,

Totally agree, our patch was suboptimal causing unneeded REGISTER requests downstream, but solved undesired de-registrations that were quite problematic in our environment.

We wait until 3.2.10 is tagged including your fix and we remove our quick-n-dirty patch :)

Thank you very much and regards,
