### ISSUE TITLE
[BUG]I am compiling on version 3.2. After the compiling, there are no scripts such as opensipsctl, opensipsdbctl, opensipsunix, etc. What is wrong with my compiling?

### ISSUE THREAD

**Issue by huangqingbiao8831** [OpenSIPS/opensips#2619]
I am compiling on version 3.2. After the compiling, there are no scripts such as opensipsctl, opensipsdbctl, opensipsunix, etc. What is wrong with my compiling?

**OpenSIPS version you are running**

```
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by liviuchircu** [comment]
Hi, please read the docs for the new [`opensips-cli` project](https://github.com/opensips/opensips-cli), which is the new and better way of managing OpenSIPS 3.0+ instances.  The `opensipsctl` project has been fully deprecated, mostly because bash projects are significantly more difficult to extend and maintain that their Python equivalents.
