### ISSUE TITLE
[BUG] b2b_client_new() with proxy doesn't use proxy post-authentication

### ISSUE THREAD

**Issue by jpyle490** [OpenSIPS/opensips#2759]
```
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 35dfd3a20
main.c compiled on  with gcc 10
```
I'm using uac_auth with the b2b modules. I execute b2b_client_new() with an outbound proxy defined, and the proxy route is used for the first INVITE, but not on the second one that contains auth header. On that one, the request is routed to the domain of the RURI instead, as if no proxy had been specified.

**To Reproduce**
```
# load uac_auth.so and define relevant AVPs

[route] {
...
# set those AVPs with authentication values
$var(outbound_proxy) = "sip:10.1.2.3";
b2b_server_new("caller");
b2b_client_new("callee", $ru, $var(outbound_proxy));
b2b_init_request("refer", "t125");
...
}
```

The first INVITE routes to 10.1.2.3, but the second INVITE (with the auth information) routes to the domain of the RURI as if no proxy had been specified.

**Expected behavior**
That the second INVITE with auth routes via the defined proxy as well.

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: apt.opensips.org 3.2-nightly

**Comment by rvlad-patrascu** [comment]
Currently, the outbound proxy is stored only temporarily at b2b_logic level, until the B2B session is initialized. Also, we cannot pass any info to b2b_entities when the INVITE with the auth header is retried since it happens transparently for the b2b_logic module.

I think the best solution here is to save the proxy in the entity info, at b2b_entities level, and use it for any further requests for that entity.
