### ISSUE TITLE
[BUG] cachedb_id.c in db_url parsing process.

### ISSUE THREAD

**Issue by xuxin010033** [OpenSIPS/opensips#2786]
**OpenSIPS version you are running**
3.2

```
```

**Describe the bug**
When there is ',' in password in a db_url, it'll be parsed as CACHEDB_ID_MULTIPLE_HOSTS instead as a char in password.

**To Reproduce**
Setup a db with a ',' in its password.

**Expected behavior**
Module cachedb_sql loading.

**Relevant System Logs**
Mar 18 17:37:44 [123] ERROR:cachedb_sql:dbcache_new_connection: bogus url for local cachedb

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by liviuchircu** [comment]
Hey, @xuxin010033!  I definitely see how this issue can be in there, so we should be able to reproduce and push a fix for this fun bug _relatively_ soon.  I'll do my best to make some time for this issue as I've worked on that code at some point, but if other devs can find the time to work on this sooner, I'd be happy for this to happen! (that's why I un-assigned myself for the time being)
