### ISSUE TITLE
[CRASH] Segmentation Fault

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2826]
**OpenSIPS version you are running**

```
version: opensips 3.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d2c4bebc4
main.c compiled on 01:23:54 Apr 13 2022 with gcc 7
```

**Crash Core Dump**

https://pastebin.com/pQ7Q38tQ

**Describe the traffic that generated the bug**

Normal call traffic

**To Reproduce**

Single crash. Not reproduced at this time.

**Relevant System Logs**

https://pastebin.com/1RcKTbxY

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

Possibly related to the crash I reported in #2724

**Comment by bogdan-iancu** [comment]
@bcnewlin , this looks like a memory corruption, that stroke back when a mem dump was done via MI. Check the address of the fragment (top frame):
````
63 2d 76 63 67 2d 78 0a
 c  -  v  c  o  -  x \n
````
It is not an address, but rather a string, some kind of sip hdr or so.

I see no other way to investigate this further rather than enabling the memory debugging.

**Comment by bcnewlin** [comment]
@bogdan-iancu I can enable memory debugging and see if it reproduces. Do you know what MI command was executed to cause the memory access? That could help.

**Comment by bogdan-iancu** [comment]
Frames 0 and 1 show that the process was already running the handler for a received signal. Based on frame1 (https://github.com/OpenSIPS/opensips/blob/3.2/signals.c#L202), I assume it was a seg fault :). So the proc got a SIGSEGV, the signal handler was trigger and the process attempted to do a memory dump, where it crashed again  - no logs this time as we are already in the signal handler. Sorry for the false hint on the MI cmd, first I wrongly suspected the `mem_pkg_dump` cmd :(.
Now, the problem is that we have no clue and no core file for the original crash  :((((

**Comment by bcnewlin** [comment]
So would the memory debugger still help?

**Comment by bogdan-iancu** [comment]
As we have 0 info on the original crash, hard to say :(...

**Comment by bogdan-iancu** [comment]
Yes, there are good chances to help with.
