### ISSUE TITLE
[BUG] Opensips keeps route execute order despite reload_routes

### ISSUE THREAD

**Issue by man1207** [OpenSIPS/opensips#2872]
**OpenSIPS version you are running**

version: opensips 3.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 9

**Describe the bug**
When change order of sub-routes call in main route, and then do reload_routes, execution order of sub-route still keeping old.
For, example
`route {
   ...
   if (has_totag()) {
       route(HANDLE_SEQUENTIALS)
   }     
   route(HANDLE_INITIALS)
   ...
}

route[HANDLE_SEQUENTIALS] {
...
}

route[HANDLE_INITIALS] {
...
}`

When reordering sub-route execution in main route, like

`route {
   ...
   route(HANDLE_INITIALS)
   
   if (has_totag()) {
       route(HANDLE_SEQUENTIALS)
   }     
   ...
}`
and then reload_routes, **route(HANDLE_INITIALS)** statement calls 
route[HANDLE_SEQUENTIALS] route

**To Reproduce**
Example:
1. Start OpenSIPS
2. Change order of execution of two named sub-routes in main route
3. Run opensips-cli -x mi reload_routes
4. Run script_trace from script and look what route is being executed indeed.

**Expected behavior**
When reordering sub-routes calling in main script, and then making reload_routes, opensips should call right route correctly, like it generates when restart  service.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Ubuntu 20.04
 - OpenSIPS installation: from debs
 - other relevant information:

**Comment by liviuchircu** [comment]
The problem here is related to the `reindex_all_new_sroutes()` function call (e.g. if you try to comment it, the `reload_routes` will correctly work after you switch the two functions).  The main purpose of the function, it seems, is to try and fix bugs related to other modules referencing route indexes which have **moved** after the reload, which is quite an interesting problem.

Imagine you have:

* a `route(drouting_callback)` route which receives index `6` initially, so the `drouting` module looks the route name up and stores integer `6` internally (never to be changed until a `dr_reload`)
* meanwhile, you write a new route in the middle of your file and hit `reload_routes`.  The `route(drouting_callback)` now receives index `7` when looking up the route name, but drouting will still using route `6` until you reload it, which is a **dirty** bug!
* the `reindex_all_new_sroutes()` function tries to do a last-ditch effort and save the day by _digging_ for a route named `"drouting_callback"` and **swapping it** to still make use of index `6` instead of `7`!

So, fundamentally, reindexing the routes can only do **good** things, although there are still plenty of edge-cases causing the afore-mentioned route-referencing bugs.  For example:

* deleting the drouting route from the script, then calling `reload_routes`.  Now, until the next `dr_reload`, the drouting module will invoke route `6` on every prefix routing callback.  On the new script, this index `6` could either point to `NULL` or a random route (??), both of which are bogus states.
* refactoring route names: similar scenario to above, where you **rename** a route instead of **delete**, but also keep the old name for another route!  For a while, after only reloading the routes and not the module data, the routing will invoke the _refactored_ route instead of the proper (new) one.

But let's see if we can fix the original bug in this issue, and we can dig into those edge-cases afterwards in some other issue!

**Comment by bogdan-iancu** [comment]
The problem is more complex here, as we need to keep in sync the route triggering inside the script and the route triggering from other parts of the code (like TM related routes, etc).
The currently reported issue is a result of a logical conflict between:
- reindexing the routes so that we preserve the index of the routes after a reload (meaning changing the idx of a route after reload)
- having the routes and sub-routes linking consistent - during the reload, the full cfg is loaded, so re-parsing it from scratch will automatically correlate the sub-route idx'es with the triggering from script (so no re-indexing is needed).

The correct and complete approach will be keep the indexes as generated by the reload (even if different from the original set) and to avoid preserving the route's idx's in different parts of the code

**Comment by bogdan-iancu** [comment]
For the sake of completion via 35bb59e0949efd4166d68643de6c923313a86c0c
