### ISSUE TITLE
[BUG] OpenSIPS accepting 404 For a OPTION message

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#2903]
**OpenSIPS version you are running**

```
version: opensips 3.2.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Describe the bug**

When OpenSIP receives an OPTIONS message response, we find that it accepts 404 rather than 200 OK & continues to progress the call.

**To Reproduce**

1. Start OpenSIPS
2. Send a Standard Call
3. Make the Other Party to reply 404 for a OPTION Message
4. Notice the call continues to progress.

**Expected behavior**

We Expect OpenSIP's to tear down the call with a "Ping Timeout" release reason.

**Relevant System Logs**

Please find the pcap & logs from here, thanks : https://bit.ly/3ASHZMG

**Comment by syedrizwansrs** [comment]
@bogdan-iancu yes, that's correct.

**Comment by syedrizwansrs** [comment]
Commenting to avoid auto closing.

**Comment by digipigeon** [comment]
Commenting to avoid auto closing.

**Comment by syedrizwansrs** [comment]
Commenting to avoid auto closing.

**Comment by syedrizwansrs** [comment]
Commenting to avoid auto closing.

**Comment by razvancrainea** [comment]
The INVITE/OPTIONS replies that tear down the call are:
* 408 - the request was sent, but there was no reply back - endpoint no longer reachable
* 481 - the request was sent, but the other endpoint did not recognize the call

The 404 reply code is not explicitly handled, and is treated like any other request, that has reached the endpoint, but was mishandled. In fact, most devices we've seen are replying with this code just because they don't handle in-dialog OPTIONS/re-INVITES properly. Not sure why it should teardown the call, and definitely not with a timeout reason.
Can you provide more information about why you expect this call to be thorn down? 

Best regards,
Răzvan
