### ISSUE TITLE
[BUG] Syntax error in core function xlog 

### ISSUE THREAD

**Issue by ot-i-to** [OpenSIPS/opensips#2922]
**OpenSIPS version you are running**
version: opensips 3.3.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 10

Linux os-rtp 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
Description:	Debian GNU/Linux 11 (bullseye)
```
```

In the syntax described here https://www.opensips.org/Documentation/Script-CoreFunctions-3-3#toc56
you can use service string characters like "\n", but in fact we get that they do not work and we see `#012` in the logs.
And the label "log_level" is simply ignored :(

**To Reproduce**
--- opensips.cfg 
```
...
xlog("L_INFO", "My-INFO >>>>>\n $avp(MSG)\n <<<<<\n");
...
```

**Expected behavior**
**Relevant System Logs**
--- opensips.log
```
...
Oct 12 11:42:58 os-rtp osTEST[8463]: My-INFO >>>>>#012 192.168.45.29 | 50060 | 10.11.12.201 | 5060 | Test_PhoneL4 | nil | DLINK DPH-400S FRU2.2.15.8 | nil#012 <<<<<
...
```

**Comment by liviuchircu** [comment]
Hi @ot-i-to, the "# 012" issue you're experiencing while viewing the newlines in your logs is entirely related to your log management software (e.g. `rsyslog`), which may automatically convert the `\n` characters in the input received from OpenSIPS.

Regarding your `log_level` being ignored, please work with the new [`xlog_level`](https://www.opensips.org/Documentation/Script-CoreParameters-3-4#xlog_level) setting instead of `log_level` in order to control the logging level of your `xlog()` statements from the opensips.cfg file.  This global parameter was added in version 3.0.

**Comment by ot-i-to** [comment]
Yes, rsyslog was really to blame ... it was necessary to add the `$EscapeControlCharactersOnReceive off` parameter in the config and everything was fixed :)

Thanks for the help!
