### ISSUE TITLE
[BUG] opensips 3 does not appear to support RFC-2069 response for SIP Auth

### ISSUE THREAD

**Issue by rrevels-bw** [OpenSIPS/opensips#2995]
**OpenSIPS version you are running**

```
version: opensips 3.2.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e2fd673d9
main.c compiled on 04:01:29 Oct 29 2022 with gcc 4.8.5

```

**Describe the bug**

When using opensips 3.2 if a REGISTER or INVITE is received with an Authorization header that does not contain qop param (indicating rfc-2069 was used to generate response param) the message is rejected with stale nonce indicator.
This is not the case when running this call flow in opensips 2.4 and appears to be a bug as it looks like support for the older method of creating the response-digest was intended to be supported.
 
**To Reproduce**

1. Start OpenSIPS with a config that will support SIP auth.
2. Send REGISTER or INVITE that gets challenged and respond with auth header that does not contain qop param and formats response according to rfc-2069.
3. server responds with 401 Unauthorized and stale=true

**Expected behavior**

REGISTER or INVITE will be accepted provided username and password are correct in response and the nonce isnt indeed stale.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Cent OS version 7
 - OpenSIPS installation:  source
 - other relevant information: 

**Additional context**

**Comment by rrevels-bw** [comment]
i had a problem trying to attach (upload) my patch file here so will leave it as a code block instead.  this resolves the issue and i havent seen any backlash from it yet.


```--- modules/auth/api.c	2023-01-20 10:39:48.199598476 -0500
+++ modules/auth/api.c-modified	2023-01-20 15:09:08.468255069 -0500
@@ -229,11 +229,17 @@
 		goto stalenonce;
 	}
 	qop_type_t qop = dcp->qop.qop_parsed;
-	if ((np.qop != qop) &&
-	    (np.qop != QOP_TYPE_BOTH || (qop != QOP_AUTH_D && qop != QOP_AUTHINT_D))) {
-		LM_DBG("nonce does not match qop\n");
-		goto stalenonce;
+	if( qop != QOP_UNSPEC_D ) {
+		if ((np.qop != qop) &&
+			(np.qop != QOP_TYPE_BOTH || (qop != QOP_AUTH_D && qop != QOP_AUTHINT_D))) {
+			LM_DBG("nonce does not match qop\n");
+			goto stalenonce;
+		}
+	}
+	else {
+		LM_DBG("skipped qop test due to not having one in response");
 	}
+
 	if (is_nonce_stale(&np, nonce_expire)) {
 		LM_DBG("stale nonce value received\n");
 		goto stalenonce;

```

**Comment by liviuchircu** [comment]
Hi, @rrevels-bw!  Few thoughts on this, to put things in perspective before reviewing the patch:

1. RFC-2069 has been superseeded by RFC-2617 (Digest Authentication), in a backwards-compatible way.
2. The `qop` parameter becomes mandatory for an implementation supporting RFC-8760 ([source](https://www.rfc-editor.org/rfc/rfc8760.html#name-updates-to-the-sip-digest-a).
3. Still, to maintain backwards-compatibility with previous, RFC-2617 digest auth implementations, RFC-8760 mentions in § 2.6-4.8.1  that _"... the "qop" parameter is optional for clients and servers based on [[RFC3261](https://www.rfc-editor.org/rfc/rfc8760.html#RFC3261)] to receive. If the "qop" parameter is not specified, then the default value is "auth"."_ ([source](https://www.rfc-editor.org/rfc/rfc8760.html#section-2.6-4.8.1)).

So: if I understand correctly, the bug is that part (3) is not well-implemented, so the current RFC 8760 implementation is too strict, not allowing an _unspecified_ `"qop"` anymore, thus breaking backwards-compatibility with RFC-2617, which your patch aims to fix?

Cheers!

**Comment by sobomax** [comment]
I agree with @liviuchircu that check might be bit restrictive, however the proposed patch does not look to be correct, as it would allow UAC to "downgrade" the UAS-mandated qop policy by simply not providing qop parameter in its challenge-response a behavior that we wanted to prevent in the scope of that work. What perhaps needs to be happening instead, is that as per RFC8760 missing qop parameter should be considered to be the same as if it's QOP_AUTH_D and the rest of the logic will stay intact. So that if we challenge with qop=authint and the challenge-response has no qop the request would be rejected.

**Comment by rrevels-bw** [comment]
Ah.  I think that suggestion would meet our needs on this as well.

**Comment by rrevels-bw** [comment]
I struggled a bit over the QOP_TYPE_BOTH case but in the end decided to go with this for our use case and I have no issue if you guys decide to be more restrictive.

```
--- modules/auth/api.c
+++ modules/auth/api.c
@@ -230,7 +230,8 @@ auth_result_t pre_auth(struct sip_msg* _m, str* _realm, hdr_types_t _hftype,
	}
	qop_type_t qop = dcp->qop.qop_parsed;
	if ((np.qop != qop) &&
-	    (np.qop != QOP_TYPE_BOTH || (qop != QOP_AUTH_D && qop != QOP_AUTHINT_D))) {
+	    (np.qop != QOP_TYPE_BOTH || (qop != QOP_AUTH_D && qop != QOP_AUTHINT_D)) &&
+	    (qop == QOP_UNSPEC_D && np.qop == QOP_AUTHINT_D)) {
		LM_DBG("nonce does not match qop\n");
		goto stalenonce;
	}
```
I also couldn't figure out a way to test with the auth-int only and not returning a qop param but as I type this I suddenly realize I dont have to actually need to be able to auth.  I just need to make sure i get stale indicator if i dont send the qop param.  I'll try again later.

**Comment by sobomax** [comment]
I've added PR #3001 to fix the issue in master.

**Comment by rrevels-bw** [comment]
Even better.  Thank You!

**Comment by liviuchircu** [comment]
Hey guys, the PR looks good, so I've merged it to `master` and will also backport down to `3.2`, so it gets as much testing as possible before the minor releases on Feb 20th.  Cheers!

**Comment by rrevels-bw** [comment]
Our regression testing, for both 3.2.10 and this patch, looked good.   Thank You both very much!
