### ISSUE TITLE
[BUG] Lock (related to TLS & t_reply?) is holding up processes

### ISSUE THREAD

**Issue by Matt-Hapner** [OpenSIPS/opensips#3034]
**OpenSIPS version you are running**

```
version: opensips 3.2.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4dc436ebf
main.c compiled on 11:08:57 Mar  8 2023 with gcc 7
```

**Describe the bug**

OpenSIPs runs well for a period of time until this situation is encountered in which the CPU usage spikes from normal levels (~10%) to 100% in a matter of a minute or so. Threads are deadlocked while attempting to grab a lock that appears to be related to the t_reply method of the tm module. This occurs only for very specific calls that use a tls transport and are rejected with a 477 that is then relayed back to the UAC. The same Call-Id is evident in many of the thread backtraces.

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

`opensips-cli -x trap` contents: https://pastebin.com/pu94Kgzy
PIDs 7095, 7099, 7100, 7101, 7111, 7112 appear to be deadlocked and the rest appear to be idle

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@Matt-Hapner , this is really strange as each process is dead-locking itself. The BT shows an incoming negative reply that triggers failure route (see frame 27 doing `run_failure_handlers()`) - this failure route is run with the transaction locked.
Now, in failure route, you get to a point where `send_reply(404)` is done, translating in `t_reply(404)` - and this tries to lock (again) the transaction. This situation is foreseen and in order to avoid such deadlocks, the `t_reply()` code is checking the type of the current route, to see if locking is or not necessary. If FAILURE_ROUTE is detected, the locking will be skipped.
So, to explain the posted BT, I guess that somehow the `t_reply()` does not see the correct type of route, so it does the locking.
Please attache with gdb (to any of the locked processes) and print the `route_type` global variable - let's see what is there.

**Comment by bogdan-iancu** [comment]
Thank you @Matt-Hapner for all the help in troubleshooting this issue. The backports are available on all the maintained branches.
