### ISSUE TITLE
Failed to init TLS_DOMAIN

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3153]
**OpenSIPS version you are running**

```
version: opensips 3.5.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9376d60c7
main.c compiled on 06:47:18 Aug 11 2023 with gcc 11
```

**Describe the bug**

ERROR:tls_mgm:init_tls_domains: Failed to init TLS domain 'erss.in'
Aug 14 11:23:11 ip-172-31-34-24 /sbin/opensips[92405]: ERROR:core:init_mod: failed to initialize module tls_mgm
Aug 14 11:23:11 ip-172-31-34-24 /sbin/opensips[92405]: ERROR:core:main: failed to initialize modules!
**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Ubuntu 22
 - git
**Additional context**

**Comment by prathibhacdac** [comment]
I've posted this issue in users mailing list. It is not yet approved by the moderator. Can someone help?

**Comment by razvancrainea** [comment]
I do not see any problem in your report, other than the fact that you opened an issue without providing details why this is an bug/problem with OpenSIPS. If you do think this is a problem with OpenSIPS, please detail why, how you tested, what is the information/certificates you are using and what is the expected behavior. The template of the ticket is a good start, try to fill in as accurate as possible.
