### ISSUE TITLE
[BUG] retransmission BYE can't match topology_hiding

### ISSUE THREAD

**Issue by chenyw11** [OpenSIPS/opensips#3162]
My Opensips version:
```
2.4.11
```

I use topology_hiding module in the cfg. When opensips received a BYE, it execute `topology_hiding_match` sucessfully. But if the first BYE lost, the **retransmission** BYE excute topology_hiding_match **failed** because the dialog is destroyed.

I saw `The dialog is automatically destroyed when a “BYE” is received.` in the dialog.html. Can opensips destroy the dialog after received 200 OK of BYE?

**Comment by bogdan-iancu** [comment]
The 2.4 version is not maintained anymore, so fixes are not possible here. In the latest version you have this [delayed delete](https://opensips.org/html/docs/modules/3.4.x/dialog.html#param_delete_delay) to help with such situations.

Anyhow, for the sole purpose of retranmissions, use t_newtran() before the topo matching in order to catch and consume the retransmissions.
