### ISSUE TITLE
[FEATURE] deactivation of E164 verification in stir_shaken_verify (for France)

### ISSUE THREAD

**Issue by Mickaelh51** [OpenSIPS/opensips#3181]
**Is your feature request related to a problem? Please describe.**

Hi, in France it's possible to sign stir and shaken with portability prefix in `dest`
Ex:
RURI: +33**10200**123456789
TO: +33**10200**123456789

```json
{
  "attest": "C",
  "dest": {
    "tn": [
      "3310200123456789"
    ]
  },
  "iat": 1693986416,
  "orig": {
    "tn": "33987654322"
  },
  "origid": "55555-f270-444-7bb9-c5c6262122e7"
}
```

With this format, I have an issue in `stir_shaken_verify` function.
logs:
```
Sep  6 13:39:48 am-scr-001 /usr/local/sbin/opensips[622409]: ERROR:stir_shaken:check_passport_phonenum: number is not in E.164 format: 3310200123456789
Sep  6 13:39:48 am-scr-001 /usr/local/sbin/opensips[622409]: ERROR:stir_shaken:w_stir_verify: failed to validate Destination number (3310200123456789)
```

**Describe the solution you'd like**

I found a solution, and I will post a PR soon.
The idea is to reuse `require_plus` variable in _is_e164 function

**Comment by Integration-IT** [comment]
@Mickaelh51,

Unfortunately this is the intended result.
Number 3310200123456789 is not E164 format because.
- start with "+" : FALSE
- first number 1-9 : TRUE
- extra number 0-9, 1 to 14 : FALSE

The STIR module help to solve the "+" case" with the [check_passport_phonenum](https://github.com/OpenSIPS/opensips/blob/20e540d00eb0bedf37144bda9575c01d9a64ee3c/modules/stir_shaken/stir_shaken.c#L1115) function and did the job for you.
But the root cause is probably the number of digits of 15 without including the first one after the "+".


If you want bypass the E164 check you should probably focus here **at module level** and not inside ut.h **at core level** with **extra border effects**, but I think that's a false good idea:
```
/*
	if (_is_e164(num, e164_strict_mode) == -1) {
		LM_GEN(log_lev, "number is not in E.164 format: %.*s\n", num->len, num->s);
		return -1;
	}
*/
```

I am reading the APNF documentation (FR regulation process) and no E164 bypass is allowed.
Why not open the mind and focus around LNP and portability parameters and follow the RFC4694 to provide npdi and rn extra param to get ready with SIP to SS7 interworking to sign the call with the actual number and inform your gateway with the portability informations ?

The LNP RURI could avoid lot of troubles:
```
INVITE sip:+33110203040;rn=10200;npdi=yes@1.2.3.4:5060 SIP/2.0
```

rn is number that should be used for routing the call as LRN.
npdi indicates a lookup in the NPDB has been done.

Finally, no effort required to isolate the username in request's URI now.
Regards.

**Comment by Mickaelh51** [comment]
Hi,
Thanks for your answer.
But this format (sign with portability prefix) is sent by a big french provider (not by me), so, it's not possible to use your solution.

After that, it's legal in France to sign without E164 format.
APNF is writing a new version of MAN documentation.

Cf: https://www.mail-archive.com/frnog@frnog.org/msg73317.html

**Comment by Integration-IT** [comment]
@Mickaelh51 ,

MAN_Regles techniques : 2.5.1.5
```
contient un numéro de téléphone (TN) valide.
```

RFC8224 8.1, 8.2, 8.3
```
bearing in mind that the telephone number may be a valid E.164 number.

```

You are breaking the RFC to please an operator who is not making any efforts, RFC4694 and RFC8224 are probably the bests ways to fix this case.

**Comment by Mickaelh51** [comment]
Hi,
I think you are future old version of MAN_Regles techniques.
You can see, the project of MAN_Regles techniques modifications (sended by a person who participate to MAN meetings)
![unnamed (1)](https://github.com/OpenSIPS/opensips/assets/9885404/e877a4b1-840a-42d3-813e-2b5649e60fd3)

Moreover, I asked to APNF and the official response is:
```
Après vérification et échange, cet opérateur a bien raison.
```

So for now, in France it's legal to sign with portability prefix. So we need to deactivate E164 length.
I'm not happy to bypass E164 verification, but in France it's possible :(
Maybe in the future it will be changed...
