### ISSUE TITLE
[BUG] e164_strict_mode is not initialized

### ISSUE THREAD

**Issue by tcressonKeyyo** [OpenSIPS/opensips#3224]
**OpenSIPS version you are running**
```
version: opensips 3.3.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 11:12:36 Sep 14 2023 with gcc 7
```

**Describe the bug**
The parameter `e164_strict_mode` in the stir shaken module is not initialized and should be initialized to 0. Which makes the signature verification fails with numbers not beginning with a `+` sign.

**OS/environment information**
Operating System: openSUSE Leap 15.4

**Comment by liviuchircu** [comment]
Hi @tcressonKeyyo!

The `e164_strict_mode` is a global variable, which gets initialized to `0`, ever since the C89 standard.  Moreover, since `3.1`, all _stir_shaken_ documentation hints that the default value is `0`, which is in accordance to the code.

So I am under the impression your problem is in a different area, e.g. maybe your numbers are longer than `15` digits, for example, which could also get the E164 verfication to fail.  So please provide more information on how to reproduce your issue -- from the looks of it, you have installed version `3.3.7` from standard packages, correct?

**Comment by liviuchircu** [comment]
> The variable `e164_strict_mode` is only defined in the `stir_shaken.c` and is only visible to this translation unit (it is declared `static`) and not initialized anywhere.

There is no other translation unit requiring it, hence why the code compiles and also the shared library gets successfully loaded on startup.  Regarding initialization, I just wrote above: "all globals get initialized to `0`, according to the C standard".

> Therefore I cannot understand how this variable can be global 

In C, "global" refers to the scope of the variable:  it's either function-local or non-local.  Whether the global itself is restricted to the local translation unit or not, that's a different story.

> And for the failed verification, the number itself is a French, 11 digits long number (international format without the `+` sign => 33123456789) so it should not fail for the length.

OK, please provide a **full** sample PASSporT and sample OpenSIPS logs, showing the error.  It's possible other number is failing:  maybe the R-URI, or From number, or To number.

**Comment by tcressonKeyyo** [comment]
Yes you are right I forgot about the global scope variable initialization. And sorry but the problem was not during the verification but the authentication

**Comment by tcressonKeyyo** [comment]
OK, the problem is from what I give to `stir_shaken_auth`, sorry for the inconvenience I close this issue.
