### ISSUE TITLE
[CRASH] Opensips 3.4.4 crash

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#3322]
**OpenSIPS version you are running**

```
version: opensips 3.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 036d02961
main.c compiled on  with gcc 11

```

**Crash Core Dump**
please find the [link](https://drive.google.com/file/d/1R_TtVoSmiG0ZF2o0Pm-B9qpLyg61P-oj/view?usp=sharing) 

**Describe the traffic that generated the bug**

During high-volume traffic scenarios, an anomaly in the rate-limiting mechanism was observed. Specifically, it was noted that the rate limit counter failed to reset correctly, leading to unexpected behavior in SIP traffic processing.

**OS/environment information**
 - Operating System: Ubuntu 22.04.4
 - OpenSIPS installation: debs 

**Additional context**
Please let us know if you need any more details. thanks

**Comment by bogdan-iancu** [comment]
Hi @syedrizwansrs , in gdb, please do:
```
f 1
p *map
```

**Comment by bogdan-iancu** [comment]
@syedrizwansrs , this looks like a memory corruption of the `rl_htable.maps` array, where the `map` address comes from. Its `0x7f7800000001` address is broken (not 8-bytes aligned) - it looks like an 4 byes (int?) was written over it at the end ( probably an int of `1` value).
Somehow I suspect this mem corruption was also caused by [this overflow](https://github.com/OpenSIPS/opensips/commit/07e063c443ffa467db5d5f51210b76783632ba64) which was recently fixed. I see your report was prior to the fix. So, please try using some code with the fix and let's see if the crash happens again.

**Comment by syedrizwansrs** [comment]
Hi @bogdan-iancu We are no longer experiencing this rate limit issue after the update.
