### ISSUE TITLE
[CRASH ] We got a segfault here

### ISSUE THREAD

**Issue by ar45** [OpenSIPS/opensips#3464]
https://github.com/OpenSIPS/opensips/blob/bb41e4beaf9947482978063b2850bbe532e1c7ba/modules/rest_client/rest_methods.c#L584

Perhaps this is supposed to be `(unsigned int *)(unsigned long *)(*connected_ts) < curl_conn_lifetime))`

**Comment by liviuchircu** [comment]
Hi @ar45!  I'm afraid the fix in #3467 might not be entirely accurate, could you please pull to latest and test out the following _additional_ patch, available [here](https://gist.githubusercontent.com/liviuchircu/2fd29529c06680b3eebac34c85eaa1f3/raw/0d1fbf9cb1e6ded98fee8957a9a60d6b4297fb96/rest-client-ptr-management-quickfix)?

Long story short:

* the `map_get()` gives you a changeable 8-byte _holder_ (hence `void **`), so you can store arbitrary data inside the map
* here, I only needed to store an `unsigned int` as map value (the "last used" timestamp), so I abused the `void *` holder and only stored a 4-byte `unsigned int` as being the holder _itself_, casted as `unsigned long`.
* there is no need to check for `*connected_ts`, as there is no point in testing the timestamp value itself, only the holder (`(void **)connected_ts`)
* indeed, the bug was in the line you suggested above, because of extra `*` (fixed by attached patch)

Let me know how it goes, thank you!

**Comment by ar45** [comment]
@liviuchircu  Attached is a corrected patch based on what you provided.
[rest-client-ptr-management-quickfix-2.patch](https://github.com/user-attachments/files/16967761/rest-client-ptr-management-quickfix-2.patch)

Besides that. I see the way it is implemented, the `curl_conn_lifetime` is just an arbitrary value which says every `curl_conn_lifetime` we expect to reconnect and therefore, grab a lock until done. The `connected_ts` is also not updated on subsequent requests within `curl_conn_lifetime`.

I would expect that `curl_conn_lifetime` would control the `CURLOPT_MAXLIFETIME_CONN` or `CURLOPT_MAXAGE_CONN` or `CURLOPT_TCP_KEEPIDLE`.

while `no_concurrent_connects` would control that whenever curl does not have an exiting connection, the connect phase would be wrapped within the `hash_lock(rcl_parallel_connects, he);`

**Comment by liviuchircu** [comment]
Thank you for the feedback, @ar45!  Indeed, I updated the gist afterwards, but the RAW URL (linked in the email) seems to be unique for each revision, so you still got sent to the old one.  Now that part is functional -- all in all, there was just an extra `*` to be removed in order to fix the logic, once you add up both of our fix-patches.  I will take care of backporting it.

With regards to the connection "LRU timestamping" logic, I just wanted to put out a starting point, which we could then adjust based on various cURL library behaviors we find out.  For example, I haven't found any way to control the long-lived connection timeouts in the cURLs I tried, so I assumed they default to the OS settings (documented in [curl_conn_lifetime](https://opensips.org/docs/modules/3.6.x/rest_client.html#param_curl_conn_lifetime)).  So if a shared timestamp isn't updated at all within `curl_conn_lifetime` seconds on a given hostname (no OpenSIPS worker has used it), the module assumes all cURL long-lived TCP connections will have been dropped at that point and will re-activate the "one process connects at a time, others get an error" logic.

Cheers!

**Comment by ar45** [comment]
Thanks @liviuchircu for the quick response and updates.

I think that using the following callbacks we can keep track internally if there is an actual `connect ` happening.

[curl_easy_setopt](https://curl.se/libcurl/c/curl_easy_setopt.html)(curl, [CURLOPT_RESOLVER_START_FUNCTION](https://curl.se/libcurl/c/CURLOPT_RESOLVER_START_FUNCTION.html), start_resolve_cb);

[curl_easy_setopt](https://curl.se/libcurl/c/curl_easy_setopt.html)(curl, [CURLOPT_OPENSOCKETFUNCTION](https://curl.se/libcurl/c/CURLOPT_OPENSOCKETFUNCTION.html), opensocket_cb);

When `opensocket_cb` is called, we try to acquire  the lock for `rcl_parallel_connects` and when the connect is done we release it.

in the callback to `CURLOPT_OPENSOCKETFUNCTION` we can also implement `check_blacklist_rule([bl_name], ip[, port [, proto]])` [opensips check_blacklist](https://www.opensips.org/Documentation/Script-CoreFunctions-3-5#check_blacklist_rule)
