### ISSUE TITLE
[BUG] JSON failing loop iterate.

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#3492]
Version

```
opensips -V
version: opensips 3.4.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
unknown revision: unknown
main.c compiled on 00:00:00 Jan 26 2024 with gcc 13
```

Issue 
Rest API call completes 200OK and output is added to json var. 
Trying to list all keys and values in json, but loop failing.

Log 

```
Oct 10 10:23:57 dev1-msg opensips[486027]: [OSIP-250-SMPP] [486027]: DBG:rest_client:rest_easy_perform: CURLcode: 0, HTTP response: 200
Oct 10 10:23:57 dev1-msg opensips[486027]: [OSIP-250-SMPP] [486027]: NOTICE:[DST_LOOKUP] [MESSAGE] [855] Rest API Get $var(rc)|1 $json(lookup)|{"valid":true,"number":"16134570114","local_format":"6134570114","international_format":"+16135291112","country_prefix":"+1","country_code":"CA","country_name":"Canada","location":"KanataStittsville","carrier":"","line_type":"landline"} $var(retrive)| $var(rcode)|200
Oct 10 10:23:57 dev1-msg opensips[486027]: [OSIP-250-SMPP] [486027]: DBG:core:comp_scriptvar: int 20: 200 / 200
Oct 10 10:23:57 dev1-msg opensips[486027]: [OSIP-250-SMPP] [486027]: DBG:json:pv_json_iterate: Can only iterate over arrays or objects
Oct 10 10:23:57 dev1-msg opensips[486027]: [OSIP-250-SMPP] [486027]: DBG:json:pv_get_json_ext: Failed to iterate
Oct 10 10:23:57 dev1-msg opensips[486027]: [OSIP-250-SMPP] [486027]: DBG:core:destroy_avp_list: destroying list 0x7fc01c442070

```

To reproduce 

```
route[DST_LOOKUP] {
        $json(lookup) := "{}";
        $var(key) = "api key";
        $var(dst_number) = $rU;
        $var(data) = "access_key=" + $var(key) + "&number=" + $var(dst_number) + "&format=0";
        #async(rest_get("http://apilayer.net/api/validate?$var(data)", $json(lookup), $var(retrive), $var(rcode)), DST_LOOKUP_RESUME);
        $var(rc) = rest_get("http://apilayer.net/api/validate?$var(data)", $json(lookup), $var(retrive), $var(rcode));
        xlog("[DST_LOOKUP] [$rm] [$cfg_line] Rest API Get $$var(rc)|$var(rc) $$json(lookup)|$json(lookup) $$var(retrive)|$var(retrive) $$var(rcode)|$var(rcode)\n");
        # API return data
        if($var(rcode)==200) {
                for ($var(k) in $(json(lookup.keys)[*])) {
                        xlog("[DST_LOOKUP_RESUME] [$rm] [$cfg_line] dst number $$var(dst_number)|$var(dst_number) retrived key $$var(k)|$var(k)\n");
                }
        }
        exit;
}
```

Expected 
That will be possible to go over all key values and set appropriate action. 
Might be as improvement  will be nice to have  ability to iterate over loop similar in lua 

```
for k, v in ipairs(t) do

```

**Comment by liviuchircu** [comment]
Hi @volga629-1,

Can you please provide a [minimal, complete, verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example that reproduces this looping issue?  For example, I have the following unit tests in place which are still passing and suggest that the for-loop is working fine over the JSON keys and values:

```
    $json(foo) := "{\"a\": 1, \"b\": 2, \"c\": 3}";
    $var(keys) = "";
    for ($var(k) in $(json(foo.keys)[*]))
        $var(keys) += $var(k) + "|";
    assert ($var(keys) == "a|b|c|", "test-json-iter-1");

    $var(vals) = "";
    for ($var(v) in $(json(foo.values)[*]))
        $var(vals) += "" + $var(v) + "|";
    assert ($var(vals) == "1|2|3|", "test-json-iter-2");
```

Thank you!

**Comment by volga629-1** [comment]
In my case JSON var  is API call output, not static entries. I can provide you API key to try. 

```
$json(lookup) := "{}";
$var(rc) = rest_get("http://apilayer.net/api/validate?$var(data)", $json(lookup),

```

**Comment by liviuchircu** [comment]
Two issues here, I think I know what's going on now:

* if you pass `$json(lookup)` to `rest_get()`, it will lead to simple assignment operator `=`, instead of `:=` which is preferable by json module.  I'm not sure what happens then, but for now, I think you must copy the data into a separate `$var(x)`, then parse it with `:=` op into a JSON
* Inside the keys loop, try accessing the value like this: `$json(foo/$var(k))`.  This should fix your 2nd problem with the feature request - it's a nice-to-have, as there is a workaround currently.

**Comment by volga629-1** [comment]
Thank you clarification . The issue if I output JSON into just var it going break key value structure where will be not possible to set appropriately. Is this correct ?

**Comment by liviuchircu** [comment]
Glad to hear that, @volga629-1!  I will close here, as "invalid".  After a second thought on whether the JSON should be automatically parsed when passed to `rest_get()`, the following examples should make it clear that the current behavior is the correct one (just using `=` simple assignment, not `:=`):

* when you pass `$json(lookup)` as `rest_get()` output, you may prefer either of the `:=` and `=` operators
* when you pass `$json(lookup/result)` as `rest_get()` output, you expect `=` operator (simple assignment!)

Since the function cannot detect your intention based on so little information, the current `=` behavior will have to do.
