### ISSUE TITLE
OpenSIPS leaks version

### ISSUE THREAD

**Issue by gremaudc** [OpenSIPS/opensips#417]
OpenSIPS server leaks version and this information may help to conduct an attack. I propose to add a parameter in the configuration to control which information is displayed. For example, Apache has settings to manage this.

- ServerToken which can be set to Prod mod
- ServerSignature can be set to Off
- expose_php can be set to Off

This information can be easily found with a tool like nmap.

**Comment by bogdan-iancu** [comment]
@gremaudc , by leaked information you mean the description in the "server" or "ua" headers ? or something more ?

**Comment by gremaudc** [comment]
@bogdan-iancu For example when a scan is made by a tool like nmap, the openSIPS version is displayed.

**Comment by liviuchircu** [comment]
That is simply due to the *Server:* header from the OPTIONS reply. You can control the degree of information that is returned by your OpenSIPS in the scan replies on two levels:

* No information at all (just turn off the [server_signature](http://www.opensips.org/Documentation/Script-CoreParameters-2-1#toc80) global parameter)
* Some information, but not any specific version (specify the content using the [server_header](http://www.opensips.org/Documentation/Script-CoreParameters-2-1#toc79) global parameter)

**Comment by rgagnon24** [comment]
Reference: http://www.opensips.org/Documentation/Script-CoreParameters#toc74

Example:
Put one of these near the beginning of your configuration file, outside of any routes.

Do not send a Server: header
```
server_signature=no
```
or, send a custom header:
```
server_header="Server: MyGateway(1.2.3.4)"
```
