### ISSUE TITLE
sip_resolvehost srv logic

### ISSUE THREAD

**Issue by jarrodb** [OpenSIPS/opensips#482]
This may be a non-issue, but I have been using `sip_resolvehost` in an attempt to create fall-through scenarios based on protocol preference, so I am just trying to understand the logic.

When a protocol is specified (`tls` for example), but a port is omitted when calling `sip_resolvehost`, an attempt is made to resolve the SRV record (`_sips._tcp.domain.com`).  If the SRV record does not exist, it simply tries to resolve the A record for the domain, but then preserves the attempted protocol and default port for that protocol in the return.

Here is a pseudo example of the flow:

1) sip_resolvehost(*name="opensips.org", *port=0, *protocol=PROTO_TLS)
2) attempt to find srv record _sips._tcp.opensips.org
3) no record exists
4) set the port to 5061 (the default for PROTO_TLS)
5) resolve the A record for opensips.org
6) return the results

It seems it would be better, if falling through to an A (or AAAA) record to set the port and protocol to a default:

```
diff --git a/resolve.c b/resolve.c
index 86ac6e5..8a5686c 100644
--- a/resolve.c
+++ b/resolve.c
@@ -1835,7 +1835,7 @@ do_srv:
                LM_WARN("domain name too long (%d),"
                        " unable to perform SRV lookup\n", name->len);
                /* set defaults */
-               if (port) *port = (is_sips)?SIPS_PORT:SIP_PORT;
+                if (port) *port = SIP_PORT;
                goto do_a;
        }
 
@@ -1876,7 +1876,7 @@ do_srv:
        LM_DBG("no valid SRV record found for %s, trying A record lookup...\n",
                tmp);
        /* set default port */
-       if (port) *port = protos[*proto].default_port;
+       if (port) *port = SIP_PORT;
 
 do_a:
        /* do A record lookup */
```

Or, if requesting a **specific** protocol, which was **not** found, then return 0 so a decision could be made upstream.

I may be way off base, just trying to see if this was the intended result.

**Comment by bogdan-iancu** [comment]
@jarrodb , the sip_resolvehost() takes the proto parameter as a must. Whatever proto is requests by upper layer must be obey. This function must not change the proto (for whatever reasons) .
If the upper layer wants TLS (because of forced from script, or because the the URI indication), the function must find (DNS based) a destination for TLS. If an SRV record is not present should be an error - maybe there is a simple setup where SRV is not used. But the service accepts TLS via A record + default SIP port.
For having proto fallback, the whole logic of the function + upper layer must be changed. The fallback (like enabling and potential options) should be dictated by the upper layer (or some mid layer function) and the sip_resolvehost() just to perform the actual DNS lookup (with an eventual break if some records are not present and indicated so).

**Comment by jarrodb** [comment]
Thank you for your time and comments.  I think I have a better understanding now of what was being attempted after this post and our chat on IRC.
