### ISSUE TITLE
sqlite avpdb queries are broken

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#625]
master
commit: 079de59850d9b9e199c5ff5285ba11600a8d2faf

avp_dbquery using sqlite is broken.

see the following gist:
https://gist.githubusercontent.com/etamme/262ff6c7aa2c4889b2af/raw/7a445ee329784e467623eaa7401cc9537671309b/gistfile1.txt

**Comment by ionutrazvanionita** [comment]
https://github.com/OpenSIPS/opensips/commit/779996d9b37ad11f01420961ac708c6daa4d2828 the problem was that sqlite3_column_metadata was using the table name from the connection structure, but on raw queries no table name was set. So i parsed the query to search for the keyword 'FROM', case insesitive, then got the table name and set it for the connection.

**Comment by liviuchircu** [comment]
Seems like SQLite does not support subqueries in the FROM clause [1], so the idea behind the commit seems to be a good one.

[1]: http://www.tutorialspoint.com/sqlite/sqlite_sub_queries.htm

**Comment by ionutrazvanionita** [comment]
fixed with https://github.com/OpenSIPS/opensips/commit/ab0e7c461ecb7be5d2a8246c706203c096d3acd4 and https://github.com/OpenSIPS/opensips/commit/bf1d08994f23667a10be1673f53ca7970f79010c
