### ISSUE TITLE
OpenSips crash 10 times in 10 seconds

### ISSUE THREAD

**Issue by Madkonix** [OpenSIPS/opensips#666]
Hi Guys,

We had somme issues a few days ago. We noticed about 10 coredumps created by opensips  in 10 seconds. Our redundancy plan worked and we didn't face noticeable downtime. But as you can see in the link below, the core dumps seems incomplete. We are not able to investigate why thesystem crashed in first place (so many times in a row).

http://pastebin.com/UjXpbGqZ

Thank you,
Mamadou Koné

**Comment by bogdan-iancu** [comment]
Hi @Madkonix - was this an isolated event ? Do you have some external tool that kills opensips ? this may be the reason why the core is incomplete - opensips process is killed before being able to write down the corefile.
Maybe the crash occurs at a failed startup  - some monitoring tool of yours is keep restarting it.

Do you see any way to continue the investigation of this crash ?

**Comment by bogdan-iancu** [comment]
BTW, what opensips version you use ?

**Comment by zonkeyteam** [comment]
Hi @bogdan-iancu , we had that situation once and it didn't happen again after.

No, there is no such tool on the server that would trigger a kill on the opensips process, but we do have Monit configured to make sure opensips runs on the server and start it otherwise.

As you pointed, monit may be the reason the process kept restarting after each crash, but still no clue about the crashes origin.

We have been using 1.11 for a few month when the issue happened, it is still the version we use.

Regards,
Mamadou Koné

**Comment by Madkonix** [comment]
Hi @bogdan-iancu , we had that situation once and it didn't happen again after.

No, there is no such tool on the server that would trigger a kill on the opensips process, but we do have Monit configured to make sure opensips runs on the server and start it otherwise.

As you pointed, monit may be the reason the process kept restarting after each crash, but still no clue about the crashes origin.

We have been using 1.11 for a few month when the issue happened, it is still the version we use.

Regards,
Mamadou Koné

**Comment by bogdan-iancu** [comment]
@Madkonix, with the current info there is no way to throubleshoot what happened. Let us close this report and if something similar happens again, please open a new report, hopefully with more info. Thanks, Bogdan
