### ISSUE TITLE
Package memory leak in  context.c: context_alloc, line 125

### ISSUE THREAD

**Issue by 46labs** [OpenSIPS/opensips#850]
version: opensips 2.3.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 8ffd592
main.c compiled on 15:46:05 Apr  6 2016 with gcc 4.8

Memory debugging enabled, pb of memory sampling.

Leaking in [context.c: context_alloc, line 125]

http://pastebin.com/MEhWuz4U
http://pastebin.com/X25kg3bE
http://pastebin.com/wi9nLFxh

**Comment by 46labs** [comment]
tested with qm_malloc, fmalloc + optimizations, and hp_malloc, All leak.

**Comment by jarrodb** [comment]
Could this result from *ctx memory not being freed when a parse error occurs in the function `receive_msg` ?

When `parse_msg` fails at `receive.c:137`, then `goto parse_error` is called which passes over the `end:` label that handles destroying the context.  Perhaps that could be an issue because we're seeing lots of `Unable to parse msg received from` messages as well.

**Comment by liviuchircu** [comment]
A very nice report!

This is a 2.2-specific leak, I managed to confirm it myself. It has to do with commit 7464a86e1, and I'm already working on a fix.

**Comment by liviuchircu** [comment]
Just pushed [a fix](https://github.com/OpenSIPS/opensips/commit/731719a2b10) on the `master` branch which seemed to get the job done on my setup.

**Comment by liviuchircu** [comment]
Backported to `2.2`. Closing.
