### ISSUE TITLE
avpops: memory corruption during async db query

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#873]
Occasionally, using async mysql db queries, the results are corrupted.
The culprit seems to be the call to mysql_free_result(CON_RESULT(_h)) in db_mysql_async_raw_resume().
Before the call to db_mysql_async_raw_resume(), the returned data from the db query is valid.
After the call to db_mysql_async_raw_resume(), the returned data from the db query is bogus.

**Comment by liviuchircu** [comment]
I doubt `mysql_free_result()` has anything to do with this behavior, because any results we work with at script level are duplicates of the initial results from *libmysqlclient*, done by `db_mysql_store_result()`. This means that we should be able to free the data from *libmysqlclient*, unless `db_mysql_store_result()` has a quiet flaw in its duplication logic.

How often is **"occasionally"**? Could you offer some basic help into reproducing this issue? Personally, I've thrown hundreds of unique async MySQL queries at it, per second, and have yet to see it crack.

**Comment by liviuchircu** [comment]
Bug confirmed with @ovidiusas, and we also fixed it with [a quick, but inefficient solution](http://opensips.org/patches/db_mysql_fix_async_results.patch).

However, I'd like to come up with a better patch, with zero added overhead - most likely it will involve a change in the DB API.

**Comment by liviuchircu** [comment]
@ovidiusas, I managed to finish the above-mentioned patch by extending the DB API with a `db_async_free_result` function. Now we are able to delay the `mysql_free_result` function call, make use of the mysql results, and free them, as well as other internal data structures, by calling the newly added API function.

I tested patch with both "db_virtual" (over "db_mysql") and plain "db_mysql" modules in async mode. Behaved well, with no memory leaks.

Please test it out on your system as well - especially since the invalid memory read only seems to lead to crashes mostly over there!

**Comment by ovidiusas** [comment]
@liviuchircu, I have applied the patch and I will let you know of any issues.

Thanks,
Ovidiu
