### ISSUE TITLE
SIP message id ($mi) no longer consistent (incremented) when async routes are used

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#885]
The SIP message id core variable was very useful in correlating logs belonging to the same SIP message. This is no longer the case as the SIP message id is incremented every time an async route is invoked.

**Comment by bogdan-iancu** [comment]
@ovidiusas, the msg ID is internally used in several places to check if different ops are done over the same SIP msg structure (usually this is used in validate the content of some global holders - basically to invalidate them when we start handling anther SIP msg).
Shortly, that's an ID of the sip_msg structure and not of the SIP message (at SIP level).
Similar to the async jumps, in failure route, the sip_msg has a different ID rather than in request route - and this behavior is there since the origins of TM :) .
I would say your expectations on that ID are false, not to mention that the "consistency" was not there even before async.

**Comment by bogdan-iancu** [comment]
Hi @ovidiusas , any thoughts on the above ? should we close this report ?

**Comment by ovidiusas** [comment]
Somehow I missed both your posts ... sorry about that.
I see your point here. We should make this clear in the documentation/wiki.

Question: in reply_route/failure_route, the $mi is relative to the original request or to the received reply?

It would help to have some sort of correlation between logs belonging to the same transaction or to the same request|reply. Can we have a new core variable that can achieve this?

**Comment by bogdan-iancu** [comment]
Why not using the callid ? for the integration with sipcapture/homer, we use the callid as correlation ID between the opensips logs and the SIP captured traces.

**Comment by ovidiusas** [comment]
I could, but it's really long :)
I guess we can rest this issue, we just need to enhance the documentation.

**Comment by bogdan-iancu** [comment]
Well, there is no other good (not even closer) alternative. Unless we consider adding something new.

About docs, could you point out the docs that need to be "fixed" ?

**Comment by ovidiusas** [comment]
http://www.opensips.org/Documentation/Script-CoreVar-2-3#toc50

Based on the description, my understanding was that each SIP request or reply has a unique id per process.
