### ISSUE TITLE
2.2 tls_mgm and proto_wss not included in packaging rules

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#931]
Hi,
When using make deb on ubuntu proto_wss and tls_mgm modules are not included.
It would be my suggestion to include tls_mgm to the TLS package and a new package PROTO_WSS for wss. I can't figure out why proto_ws is within the packages, but it has been included by make deb. although i can not find it in packaging/debian/rules.

**Comment by razvancrainea** [comment]
Hi, Rik!

The `proto_ws` module is included in the default deb because it does not have extra dependencies to run. However, `proto_tls`, `tls_mgm` and `proto_ws` depend on the openssl library, that's why they are not included in the default package.
I will look into the reason why there are no packages for these modules, and create them. Will keep you updated.

Best regards,
Răzvan
